### ISSUE TITLE
BUG: Content overflow on Home page

### ISSUE THREAD

**Issue by Amruta7203** [mdazfar2/HelpOps-Hub#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Home page has a content overflow below 1024px 

[home.webm](https://github.com/user-attachments/assets/daa8230d-f22d-48af-896f-2a8ff59ad5c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Amruta7203 go ahead and try to also implement this on responsive of homepage make sure there should not be any problem with desktop view.

**Comment by mdazfar2** [comment]
hi @Amruta7203 did you start working on it or I should have to give it to another one

**Comment by Amruta7203** [comment]
> hi @Amruta7203 did you start working on it or I should have to give it to another one

I have started working on it..
