### ISSUE TITLE
BUG:No validation for Edit user can add anything in it

### ISSUE THREAD

**Issue by UtkarshBirla28** [mdazfar2/HelpOps-Hub#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://github.com/user-attachments/assets/ab923e8e-4fb4-415c-83ba-6f815941a525

hey @mdazfar2 user can add anything in there profile let me fix it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by UtkarshBirla28** [comment]
@mdazfar2 assign please

**Comment by mdazfar2** [comment]
@UtkarshBirla28 please wait and will let you know after some time.

**Comment by UtkarshBirla28** [comment]
@mdazfar2 Okayyy
