### ISSUE TITLE
Feat: Making Blog's Page Responsive

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#1020]
### Describe the feature

The Blog Page isn't currently responsive on small screens, which affects the user experience. I plan to make the page fully responsive, ensuring it adjusts seamlessly to fit all screen widths. This will improve readability and navigation on mobile devices and smaller screens, providing a better overall user experience. I'll also optimize the layout and design elements to maintain aesthetic appeal and functionality across different devices.

### Add ScreenShots

![Screenshot (326)](https://github.com/user-attachments/assets/96cbedd9-a6c3-4dd1-a406-7722d0a6b6ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
Hey @shreyash3087 , if you and @mdazfar2 permit, can I work on this as I have already raised an issue #942 for it

**Comment by shreyash3087** [comment]
@Asymtode712 Sure Sure,Since I changed the Whole UI for the Blog's Page,so i raised the issue,I hope you didn't start working on it already,since now you have to make this new UI responsive instead of the old one,if you have started any work on the old UI's Responsiveness,that might go in drain.

**Comment by Asymtode712** [comment]
> @Asymtode712 Sure Sure,Since I changed the Whole UI for the Blog's Page,so i raised the issue,I hope you didn't start working on it already,since now you have to make this new UI responsive instead of the old one,if you have started any work on the old UI's Responsiveness,that might go in drain.

No I haven't started yet, as you were working on it I waited till you complete your work, I will start making it responsive now
