### ISSUE TITLE
Feat: Backend Integration of Book Marked Blogs and Search Bar

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#1021]
### Describe the feature

The current Bookmarked Blogs section is not functional and requires backend integration to work properly. Additionally, the search bar is also non-functional and needs to be able to search through the blogs effectively. I'll address these issues to ensure both features are fully operational and enhance the user experience.

### Add ScreenShots

![Screenshot (327)](https://github.com/user-attachments/assets/053a4a5e-9c79-47a1-98fe-402a98c23c94)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 You are assigned.
