### ISSUE TITLE
Feat: Want to add the text editor for text formatting in the input field  and want to fix bugs with the input fields 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1028]
### Describe the feature

I want to add the text editor for the input field so that user can do the text formatting 
Like their are bugs like on pressing ctrl+v it is not working for the text 
The height of the title will not increasing automatically as text 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/49355e88-86b0-4c74-8afa-5b963a6b5d63)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you are assigned.
