### ISSUE TITLE
[Feature Request] : ✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage

### ISSUE THREAD

**Issue by TheNikhilRaj** [mdazfar2/HelpOps-Hub#1031]
### Describe the feature

Idea Contribution
 I have read all the feature request issues.
 I'm interested in working on this issue
 I'm part of GSSOC organization

Explain feature request

Hey @mdazfar2  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Explain your solution

### Add ScreenShots

![343870881-7f17e9d3-41c5-4fb0-a558-caf334552764](https://github.com/user-attachments/assets/48e8f245-1656-47db-b632-d584e87df939)

@mdazfar2 
Could you please assign me this issue under gssoc'24 ?

GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Oohho @TheNikhilRaj, I guess last time you asked the same thing about that feature, but I said we don't need this for our website. Our website is for E-learning, so please don't raise such issues again and again if I have already refused them. Hope you understand.
