### ISSUE TITLE
Feature 🧑‍💻✨: Add progress bar in scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [mdazfar2/HelpOps-Hub#1032]
### Describe the feature

Describe the feature
Hey @mdazfar2  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no progress bar in the scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.

Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Describe the solution you'd like
@mdazfar2  ,Could you please assign me this issue under gssoc'24 ?

GSSOC'24

Describe alternatives you've considered
Add progress in scroll to top button!

### Add ScreenShots

![343755959-404f8025-9ca5-4dbc-b660-cac20005d1c3](https://github.com/user-attachments/assets/71cbf24d-2e08-4d0f-a113-3a5abc1eeedb)

@mdazfar2 
/assign

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @TheNikhilRaj As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
