### ISSUE TITLE
Topic: Integrating Docker into the project

### ISSUE THREAD

**Issue by Ratangulati** [mdazfar2/HelpOps-Hub#1042]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

Docker is a must for open-source projects nowadays as it has its benefits.

Use Case
Dockerfile has many benefits but consistency and isolation stand out the most.

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit is that it runs in its environment without interfering with other applications or the host system.

I will also be updating the docs for it.

### How many and what types of DevOps tools are you adding?

I amm adding dockerfile and docker-compose.yml file into the project

### How many years of experience do you have in the DevOps field?

1.5 years

### Could you share some screenshots or a video of your previous DevOps work?

![Screenshot 2024-07-07 at 8 06 11 PM](https://github.com/user-attachments/assets/9f2a1f26-ff89-457d-a994-321ce07f9f0d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I'm DevOps professional
- [ ] Soon, I'll complete it and create a Pull Request.
- [ ] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
@Ratangulati in what name you are creating folder for your documentation?
