### ISSUE TITLE
Feat: implementation of pagination on resourse page

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#1060]
### Describe the feature

@mdazfar2 
### Add ScreenShots

![Screenshot 2024-06-26 152737](https://github.com/user-attachments/assets/f59e96f6-f7d4-4fbb-8e97-f82bdbb570cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
You are assigned @pandeyji711
