### ISSUE TITLE
Feat: Upgrading the design of the About page

### ISSUE THREAD

**Issue by ayush-848** [mdazfar2/HelpOps-Hub#1062]
### Describe the feature

I am not going to change the theme.
I will try a different style and layout

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b710ee4d-0661-4816-be2e-64835af43184)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@mdazfar2 please assign this to me. I will try to upgrade the UI and make it attractive

**Comment by mdazfar2** [comment]
Can you please elaborate, @ayush-848, on how you plan to upgrade? I assigned it to you, and you made changes that I don't like. Your work might be wasted, so please clarify how you will upgrade it.

**Comment by ayush-848** [comment]
> Can you please elaborate, @ayush-848, on how you plan to upgrade? I assigned it to you, and you made changes that I don't like. Your work might be wasted, so please clarify how you will upgrade it.

i will change the layout and text spacing
I will also try to shorten the text but not making them devoid of info
but my main focus will be **layout**

**Comment by mdazfar2** [comment]
Okay @ayush-848 go ahead and try to make it more attractive and also make it more enhance that it would be scroll down also hope you understand work like that it is your own website means it is your own project. Here in the below i will give you some section of about page for adding:


## Why HelpOps-Hub?

HelpOps-Hub was created to prevent anyone from getting stuck in the DevOps field. Our founder, Azfar Alam, experienced firsthand the challenges and frustrations of resolving DevOps issues alone. To save others from similar struggles, he established HelpOps-Hub as a platform where people can find quick solutions, share their experiences, and learn from each other.

> like that hope you understand :)

**Comment by ayush-848** [comment]
> Okay @ayush-848 go ahead and try to make it more attractive and also make it more enhance that it would be scroll down also hope you understand work like that it is your own website means it is your own project. Here in the below i will give you some section of about page for adding:
> 
> ## Why HelpOps-Hub?
> HelpOps-Hub was created to prevent anyone from getting stuck in the DevOps field. Our founder, Azfar Alam, experienced firsthand the challenges and frustrations of resolving DevOps issues alone. To save others from similar struggles, he established HelpOps-Hub as a platform where people can find quick solutions, share their experiences, and learn from each other.
> 
> > like that hope you understand :)

Sure

**Comment by ayush-848** [comment]
@mdazfar2 Do I have to do anything for backend while setting up this project??
Or the setup is just exactly like the one written in Contribution.md

**Comment by mdazfar2** [comment]
@ayush-848 what do you do backend for about us page?

**Comment by ayush-848** [comment]
> @ayush-848 what do you do backend for about us page?

some projects need to set up a .env file.
I thought this was too when I saw that  admin folder

**Comment by mdazfar2** [comment]
> > @ayush-848 what do you do backend for about us page?
> 
> some projects need to set up a .env file. I thought this was too when I saw that admin folder

Yes, actually this is already integrated with the backend, and we have an admin page which is only accessible to maintainers and the founder.

**Comment by ayush-848** [comment]
> > > @ayush-848 what do you do backend for about us page?
> > 
> > 
> > some projects need to set up a .env file. I thought this was too when I saw that admin folder
> 
> Yes, actually this is already integrated with the backend, and we have an admin page which is only accessible to maintainers and the founder.

Ok

**Comment by ayush-848** [comment]
@mdazfar2 may I add colors??

**Comment by mdazfar2** [comment]
> @mdazfar2 may I add colors??

@ayush-848 do what you want but it looks attractive.
