### ISSUE TITLE
Feat: Want to add the fade up and fade in animation for the resources page  And to fix bugs like user can change the url and go to create lbog page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1064]
### Describe the feature

I want to add the fade up and fade in aniamtion for the resources page
Like in this animation when the resources comes in the view port of the user then i will looks like popping up which will looks attractive 

### Add ScreenShots

https://github.com/user-attachments/assets/2e619b37-06b7-432f-bdac-a5de139faadf

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
You are assigned @Ayushmaanagarwal1211
