### ISSUE TITLE
Feat: Implement Dark theme for About Us page entirely

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#1072]
### Describe the feature

Currently, the dark mode theme for About Us page is partially implemented......I would like to totally implement Dark mode for this page

### Add ScreenShots

![Screenshot (100)](https://github.com/user-attachments/assets/0e11cd11-1b08-44a7-bea4-f95cb26b7107)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
You are assigned @Asymtode712
