### ISSUE TITLE
Feat: Enhancing Discover Page UI

### ISSUE THREAD

**Issue by AshmitaBarthwal** [mdazfar2/HelpOps-Hub#1084]
### Describe the feature

Since the page looks very simple I would like to make it more attractive for the users.
Will add effects to it as well.

### Add ScreenShots

![Screenshot 2024-07-19 000755](https://github.com/user-attachments/assets/afa2f94a-4e9a-4aaf-90fe-7de72c4dea8d)

WILL WORK ON THIS PAGE UI

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by AshmitaBarthwal** [comment]
@mdazfar2 Please assign this issue to me.
also add labels to my issue.

**Comment by mdazfar2** [comment]
@AshmitaBarthwal I have an idea about this section. Here is the demo video: after scrolling down and coming into this section, the animation appears like this:

<br>


https://github.com/user-attachments/assets/27c9f877-c51b-4527-a7ed-3c844de9a724

**Comment by AshmitaBarthwal** [comment]
okay I will try to make it like that.

**Comment by AshmitaBarthwal** [comment]
assign this issue to me with labels !
i will work on it.

**Comment by mdazfar2** [comment]
@AshmitaBarthwal you are assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

**Comment by AshmitaBarthwal** [comment]
@mdazfar2 I am unable to find the main html and css file related to this section.
however when i made changes while inspecting the file online in chrome they came out to be nice.
but i cant find those files in the folder.

HERE THE DEMO OF CHANGES I MADE ONLINE WHILE INSPECTING

https://github.com/user-attachments/assets/a3e814ff-8cfc-4469-b480-3e3afa8e1ad2

**Comment by mdazfar2** [comment]
@AshmitaBarthwal this is good, but I need the whole animation that appears after scrolling down, including the movement of coins and all. You did only 10% of the changes. Please look at the demo video again.

**Comment by AshmitaBarthwal** [comment]
I am unable to locate these circles of the website during inspection

**Comment by AshmitaBarthwal** [comment]
when I forked the repository i couldn't find this particular CSS file could you help me in that

**Comment by mdazfar2** [comment]
> when I forked the repository i couldn't find this particular CSS file could you help me in that


@Ayushmaanagarwal1211 Can you help her out?

**Comment by Ayushmaanagarwal1211** [comment]
Yes please wait i will check this out

**Comment by Ayushmaanagarwal1211** [comment]
@AshmitaBarthwal  in this file Spline is used 
![image](https://github.com/user-attachments/assets/41cc4169-2e5d-49c3-803c-03f96eb3793c)

and you fill find this in the Homepage.jsx on line 335 where Spline is used for this 
![image](https://github.com/user-attachments/assets/2a6aaf40-bb17-4e5b-a904-ebca98a964cf)

**Comment by mdazfar2** [comment]
Hey @AshmitaBarthwal, you didn't even reply if you understand the codebase after Ayushmaan's response. I don't know why you didn't reply; it means you are not interested in working on this issue. You should at least reply as I have been waiting for your response. So, I have to close this issue for now! Thank you.

**Comment by AshmitaBarthwal** [comment]
@mdazfar2 I was busy with my technical work so didn't got time to work upon the issue on immediate basis.
Thank you.
