### ISSUE TITLE
Feat: Modifying Solve page's UI

### ISSUE THREAD

**Issue by AshmitaBarthwal** [mdazfar2/HelpOps-Hub#1085]
### Describe the feature

Since the UI of solve page looks simple.I would like to make it more attractive and visually appealing for users.

### Add ScreenShots

![Screenshot 2024-07-19 001244](https://github.com/user-attachments/assets/26882023-53cd-4a8f-bb65-3a6df91c8797)

WILL MODIFY THIS SECTION

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by AshmitaBarthwal** [comment]
@mdazfar2 Please assign this issue to me.
also assign the labels to my issue.

**Comment by mdazfar2** [comment]
@AshmitaBarthwal can you please elaborate it how can you make is more attractive

**Comment by AshmitaBarthwal** [comment]
@mdazfar2 I will create a glass like affect around the txt and will add effects to make it dynamic,change the fonts,will also try to add a good background.

**Comment by mdazfar2** [comment]
@AshmitaBarthwal It would be great if you share some demo video. It will help me to assign you.
