### ISSUE TITLE
Feat: Backend Integration for likes on a particular comment 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1088]
### Describe the feature

I want to integrate the liking feature so that user can able to do like on any comment did by any user 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/eb41bdb0-cda4-47d4-90da-53102ede6289)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
You are assigned @Ayushmaanagarwal1211
