### ISSUE TITLE
Feat: Make Blog Post page responsive

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#1091]
### Describe the feature

Currently, our Blog Post page is not responsive for smaller screens, I would like to add responsiveness for the same

### Add ScreenShots

https://github.com/user-attachments/assets/bd184dfd-5650-4151-b11f-98a252dc65d7

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 Issue acknowledged! You are assigned.

**Comment by mdazfar2** [comment]
Hey @Asymtode712, the blog page is working fine as usual. Can you please start working on making it responsive?
