### ISSUE TITLE
Feat: Backend Integration for  adding  reply to comment feature 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1093]
### Describe the feature

I want to add the replies to comment feature where user can give reply to the comment 
Any user can reply to the comment of anyone user 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/8539503c-7955-432c-99a4-6f3ba0e7645e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
