### ISSUE TITLE
Feat:Add some scale on get-started and start now button  

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#1095]
### Describe the feature

![image](https://github.com/user-attachments/assets/214a6a78-f78e-4fee-8202-3bed26308f4c)

![image](https://github.com/user-attachments/assets/930c4e73-5292-468e-950a-1253112ebed9)

I will add some scale so user can feel button.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Please assign me this task !

Thank You !

**Comment by mdazfar2** [comment]
@zalabhavy can you please show some demo video

**Comment by zalabhavy** [comment]
@mdazfar2 check it 
https://www.loom.com/share/55c4af1484c04ad794f730d7fc8d3f18

**Comment by mdazfar2** [comment]
You are assigned @zalabhavy
