### ISSUE TITLE
Feat: Want to add the toolptip for all icons on blogpost , want to fix bugs like dark mode in create blog , image not displaying in comment ,

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1096]
### Describe the feature

I want to add the tooltip to every icon near the image like reaction , save , share and comment 
I want to fix bugs like the placeholder color is not changing in dark mode 
The comments sectino can't accessing the image 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1683dcff-c5a8-4b5a-b417-be0ae339763b)

https://github.com/user-attachments/assets/4ab0c89f-b8e3-44da-9735-aa4b08960a35

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
