### ISSUE TITLE
Feat:we can add admin dashboard

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#1099]
### Describe the feature

we can add admin dashboard where display all the detail like top contributor,contact detail....

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ddd1dd08-e7ab-4829-b258-85b7d2f6b669)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@mdazfar2 ,if you want these type feature then assign me

**Comment by mdazfar2** [comment]
@Varsani2520 we also have an admin dashboard, but the admin dashboard button is only visible to me.

- Please find any other issue or bugs that really need attention on our website. Thank you!
