### ISSUE TITLE
Feat: Add an about us page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#110]
### Describe the feature

I will add an about us page for the website 

### Add ScreenShots

It will users to get an abstract view of the website .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 could you please share the screenshot. It is help me to assign you

**Comment by Ayushmaanagarwal1211** [comment]
Ya sure i attached a screenshot below i will create an about page by adding appropriate information of the website and also add some animation .

![pasted-image-0-1](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/0f5a9820-10a0-444a-9b75-7e50b146bd95)

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 You are assigned ✔️

[HelpOps-Hub PDF.pdf](https://github.com/user-attachments/files/15535159/HelpOps-Hub.PDF.pdf)

- Go through the PDF; it can help you learn more about HelpOps-Hub. And create accordingly.

**Comment by Ayushmaanagarwal1211** [comment]
Ok
