### ISSUE TITLE
Topic: Setting Up Continuous Deployment with ArgoCD on Kubernetes 

### ISSUE THREAD

**Issue by Aditi22Bansal** [mdazfar2/HelpOps-Hub#1102]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

Include comprehensive guides on CI/CD, containerization, infrastructure as code, monitoring and logging, cloud platforms, and DevOps best practices. 

### How many and what types of DevOps tools are you adding?

- Kubernetes
- ArgoCD

### How many years of experience do you have in the DevOps field?

3 months

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by Aditi22Bansal** [comment]
@mdazfar2 
Kindly assign me this issue

**Comment by mdazfar2** [comment]
@Aditi22Bansal As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
