### ISSUE TITLE
Feat:Add Hover on About Cards.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#1105]
### Describe the feature

I want to add hover effects that increase the scale and tap effects that decrease the scale so the user can feel the interaction.

### Add ScreenShots

**Demo Video**

https://www.loom.com/share/edf9c40e6f874f0a923e1f5eabbe4361

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Please assign me this task !

Thank You !

**Comment by mdazfar2** [comment]
@zalabhavy As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
