### ISSUE TITLE
Topic: Automating Dockerization of Springboot application with GitHub actions

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [mdazfar2/HelpOps-Hub#1106]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

I am going to build the application, create a Docker image, and push it to a Docker registry (like Docker Hub). I will automate these entire process using GitHub actions for ensure that every code change triggers a consistent build and deployment process.

### How many and what types of DevOps tools are you adding?

Docker, Docker hub, GitHub actions, Spring boot

### How many years of experience do you have in the DevOps field?

2 months

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by DharshiBalasubramaniyam** [comment]
@mdazfar2, kindly assign this issue to me

**Comment by mdazfar2** [comment]
@DharshiBalasubramaniyam great issue raised, we need it.

- Create folder `Dockerize Spring-boot with Github-Actions`
- Add each and everything after hands-on 
- Also add screenshots of all steps how you do it and explanation also with `markdown`
- please don't copy and paste from anywhere
- Create in your own language
- try to write it with some emojis to enhance the user interface.

  - **The documentation you have created will help many people 🚀**
