### ISSUE TITLE
Feat: Custom scroll bar and cursor

### ISSUE THREAD

**Issue by mehrun171** [mdazfar2/HelpOps-Hub#1107]
### Describe the feature

I want to add a Custom Scroll bar and Cursor which will fit the Websites UI

### Add ScreenShots

[
![Screenshot 2024-07-20 215127](https://github.com/user-attachments/assets/f0f7aa3b-a091-4af0-93d8-3fb1fe86aec0)
](url)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@mehrun171 according to our website color, I think there is no need to add a custom scroll bar. It looks weird after adding it. Please search for another issue and raise it, which I'm happy to assign to you. :)
