### ISSUE TITLE
Feat: Want to add unique username for each user and backend integration for each username

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1109]
### Describe the feature

I want to add the username for each user 
Like with username we can maintain the uniqueness of the data and also get the profile of the user uniquely 

### Add ScreenShots

Example like discord .It will provide you unique username 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
