### ISSUE TITLE
Feat: Add Contact Us page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#111]
### Describe the feature

I will add a Contact Us page for the website it will help users to share their views 

### Add ScreenShots

I will implement it using email js for mailing functionality 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  shall i start working on contact page or faq's page first

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 sure

**Comment by Ayushmaanagarwal1211** [comment]
Ok working on it

**Comment by Ayushmaanagarwal1211** [comment]
Hii @mdazfar2  when i update my fork to latest as yours  i noticed that someone did work on contributors section and did some changes because of that in my laptop it is not responsive as previous can you please check .

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/52a09a12-2ced-48be-b7c7-60637c797234
