### ISSUE TITLE
BUG: Fix cursor style, image hover and shadow effect

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hover and shadow issues on images and cursor issue on the images in card 

https://github.com/user-attachments/assets/b31d6224-a53f-4304-a4d2-1b7b8d33915e

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes go ahead.
