### ISSUE TITLE
Feat: Enhance the view button on resources page

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1117]
### Describe the feature

![image](https://github.com/user-attachments/assets/2460ac03-0b64-4073-8219-2788d4dfe20d)

Change the view buttons to a single button and enhance the design
When user clicks on list view, the view changes and the button text changes to grid view and vice versa

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2460ac03-0b64-4073-8219-2788d4dfe20d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes issue acknowledged! You are assigned.
