### ISSUE TITLE
BUG: unnecessary padding in about responsvie

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this out,
![image](https://github.com/user-attachments/assets/c00f4e24-4d4c-4d5d-97aa-b60a4b8555a3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Great issue found @dhruv8433 

- you are going to be assigned.
- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).

**Comment by dhruv8433** [comment]
Thank you
