### ISSUE TITLE
BUG:Spell error

### ISSUE THREAD

**Issue by AkhilaSunesh** [mdazfar2/HelpOps-Hub#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/140897461/5e1506cb-aa58-4318-9092-7a8b41459386)

Its Open-source
Location: Contributors page
Kindly assign me this issue. I am new to open-source.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AkhilaSunesh** [comment]
@mdazfar2 you haven't added me to the "Assignees" column

**Comment by mdazfar2** [comment]
@AkhilaSunesh go ahead
