### ISSUE TITLE
Feat: Edit Banner Option in Profile Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#1124]
### Describe the feature

The current banner on the profile page looks great, but it would be beneficial to give users the ability to customize it. Implementing this feature would allow users to edit and upload their own banners, providing a more personalized experience. This enhancement would involve adding options for users to upload their preferred images and modify the banner to their liking, ensuring they can create a profile that truly reflects their individuality.

### Add ScreenShots

![screencapture-helpopshub-profile-2024-07-21-21_32_20](https://github.com/user-attachments/assets/e4357a44-83d6-42f7-a136-f80d0ead2c9c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
You are assigned @shreyash3087
