### ISSUE TITLE
Feat: Enhancing few section of home page

### ISSUE THREAD

**Issue by ayush-848** [mdazfar2/HelpOps-Hub#1127]
### Describe the feature

I have added the link below

### Add ScreenShots

https://www.awesomescreenshot.com/video/29752082?key=38c776a7fb713f78de7d720e275e55af
https://www.awesomescreenshot.com/video/29752156?key=da511afdade1871d7ad59914ed3e5c42

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@mdazfar2 i have added scrolling effects to these 2 parts. Do you need it??

**Comment by mdazfar2** [comment]
@ayush-848 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
