### ISSUE TITLE
Feat: Add bookmarks feature.

### ISSUE THREAD

**Issue by abckhush** [mdazfar2/HelpOps-Hub#1134]
### Describe the feature

Right now you cannot bookmark any blog. I can make the bookmark feature functional.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f899b6e7-e174-4e51-95fe-a932294ac06b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@abckhush It is already implemented. Please search for another issue and raise it, which I'm happy to assign to you. Thank you!
