### ISSUE TITLE
Topic:  add base.css

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [mdazfar2/HelpOps-Hub#1136]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

Continuous Integration/Continuous Deployment (CI/CD): Tools and practices for automating the software release process.
Infrastructure as Code (IaC): Technologies for managing and provisioning infrastructure through code.
Containerization and Orchestration: Insights into Docker, Kubernetes, and related technologies for managing containers.

### How many and what types of DevOps tools are you adding?

Jenkins
Docker
Kubernetes
Terraform
Ansible
Prometheus
Grafana
GitLab CI/CD
AWS CloudFormation
Azure DevOps

### How many years of experience do you have in the DevOps field?

6 months+

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
@AKSHITHA-CHILUKA I apologize, but I need to close this issue because your title and description are completely different. Sorry, I cannot accept it. By the way, thanks for your issue. Please don't be discouraged.
