### ISSUE TITLE
To organize content of the organizing page

### ISSUE THREAD

**Issue by ananyag309** [mdazfar2/HelpOps-Hub#114]
### Describe the feature

i will like to modify the content to a bit professional. and change the style of the contributors

![issues 1](https://github.com/mdazfar2/HelpOps-Hub/assets/145869907/7b809074-4392-4c1a-b5f7-63cef8f6d331)

### Add ScreenShots

i have added ss above. I will make the contributor size small

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ananyag309** [comment]
@mdazfar2 sir please assign me this issue

**Comment by mdazfar2** [comment]
@ananyag309 you are assigned ✔️

**Comment by ananyag309** [comment]
@mdazfar2 thank you sir also please add gssoc label.

**Comment by ananyag309** [comment]
@mdazfar2 sir i have made some changes, and raised pull req. please have a look, if there is something more you were expecting then do let me know. 

Updated the content of the page.
Update contributor.js

made enhance the readability, maintainability, and efficiency of your code.
1) In the old code, you directly appended HTML strings to create contributor cards. In the new code, I have dynamically created HTML elements and manipulated them, which is a cleaner approach and makes the code more maintainable.
2) created img, a, and span elements dynamically and set their attributes accordingly.
3) In the old code, there was a variable var cheak = 0; which seems unused and has been removed in the new code.
4) corrected a typo in the p tag where it says "Open-sourec contributor" to "Open-source contributor".
5) made minor adjustments to the structure and styling of the contributor cards, such as removing commented-out HTML and fixing indentation.

and a few more changes.
