### ISSUE TITLE
BUG: Position of the Myinfo section and the heart shape in not aligned properly.

### ISSUE THREAD

**Issue by TaeMochi12** [mdazfar2/HelpOps-Hub#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://www.helpopshub.com/resourcesdetails?folder=kubernetes%20Installation&htmlUrl=https://github.com/mdazfar2/HelpOps-Hub/tree/main/kubernetes%20Installation&isLike=false

![Screenshot 2024-07-23 011038](https://github.com/user-attachments/assets/c6077c6f-e9e4-4101-bce6-3f9abe99e5c9)

I would fix the positioning of Myinfo and the heart to the bottom of the guide.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by TaeMochi12** [comment]
@mdazfar2 Please assign me this issue!

**Comment by mdazfar2** [comment]
@TaeMochi12 issue acknowledged! You are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Comment by mdazfar2** [comment]
Hey @TaeMochi12, it's been two days and you didn't respond. Please let me know if you want to work on this issue or if I should assign it to someone else.

**Comment by TaeMochi12** [comment]
@mdazfar2 Yes sir I've started working on it. I'll do it.

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2 if it is not completed can I do that

**Comment by mdazfar2** [comment]
Sorry @TaeMochi12, it's been two days and you didn't respond. It seems you are not interested in working on this issue. Please don't be discouraged. I have to unassign it from you. Please try to create another issue and I will definitely assign you. Thank you so much! :)

**Comment by TaeMochi12** [comment]
@mdazfar2 It's ok sir.
