### ISSUE TITLE
BUG: Horizontal Scroll in Resource page

### ISSUE THREAD

**Issue by anisharma07** [mdazfar2/HelpOps-Hub#1146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

There is horizontal scrolling when cards view changed to list view

https://github.com/user-attachments/assets/52288860-a765-405c-ad4d-0c473927fe76

![image](https://github.com/user-attachments/assets/c67a7a16-641f-4655-afe1-fc0cd2796a51)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @anisharma07 issue acknowledged! You are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Comment by mdazfar2** [comment]
Hey @anisharma07 issue acknowledged! You are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo
