### ISSUE TITLE
Feat: Backend Integration of DevopsForum Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#1147]
### Describe the feature

Since the frontend for the DevOpsForum page is ready, integrating it with the backend is now a priority. This integration is crucial to ensure that the user interface interacts seamlessly with the server, enabling data fetching, posting, and real-time updates.

### Add ScreenShots

![screencapture-helpopshub-devopsforum-2024-07-23-01_33_35](https://github.com/user-attachments/assets/78852e42-e692-47ce-ac24-829a60b2501b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 go ahead.
