### ISSUE TITLE
Feat: Adding UI for Individual Forum Page in DevopsForum

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#1148]
### Describe the feature

There is a need to finalize and add the frontend UI for the DevOpsForum page to provide a user-friendly interface for DevOps enthusiasts. The UI should be visually appealing,and intuitive.I would Design and Complete the whole UI for Individual page of DevopsForum Page

### Add ScreenShots

![screencapture-preview-themeforest-net-item-docy-documentation-and-knowledge-base-html5-template-with-helpdesk-forum-full-screen-preview-30855501-2024-07-23-00_28_25](https://github.com/user-attachments/assets/6337edb3-36f2-4e04-abcd-559d7f363274)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned.
