### ISSUE TITLE
Feat: Add icon for every cards

### ISSUE THREAD

**Issue by ayush-848** [mdazfar2/HelpOps-Hub#115]
### Describe the feature

The cards are rather plain and simple looking now.
Therefore I want to add  logos to each and every cards

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126975547/82f9c173-0809-457f-9d4d-b80ebd6dc554)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@ayush-848 Nice idea💡If new topics are added in future then what will we do?

**Comment by ayush-848** [comment]
> @ayush-848 Nice idea💡If new topics are added in future then what will we do?

Well then we have to do it manually.

**Comment by ayush-848** [comment]
Well @mdazfar2 can you tell me what components you have in mind for your website??

**Comment by mdazfar2** [comment]
> Well @mdazfar2 can you tell me what components you have in mind for your website??

<br>

**Full responsivenes on phone📱 **

**Comment by ayush-848** [comment]
> > Well @mdazfar2 can you tell me what components you have in mind for your website??
> 
> 
> **Full responsivenes on phone📱**

Oh ok

**Comment by ayush-848** [comment]
For now, if you like it please assign this issue to me

**Comment by mdazfar2** [comment]
@ayush-848 as of now, we think we don't need this, will let you know in future, if there is need

**Comment by ayush-848** [comment]
@mdazfar2 ok sure
