### ISSUE TITLE
Feat: Want to create a fully responsive Forums Page And Dark mode for that 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1153]
### Describe the feature

The forums page is nice but lacks in responsiveness 
Like it is not responsive for medium and small screen sizes so i want to make it responsive 
And i also want to implement the dark mode for forums page 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/795946bb-de34-4f46-9c49-3c32a860d5e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you are assigned
