### ISSUE TITLE
Feat: adding typewriter text effect in heading

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#1166]
### Describe the feature

adding typewriter text effect in text headline

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fb9e6522-16ce-45bf-a373-367b50c9b713)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhairyagothi As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
