### ISSUE TITLE
Feat: Backend Integration for completely dynamic dashboard where we will fetch original details for comments , views , top blogs and Reacted Blogs 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1169]
### Describe the feature

I want to integrate the backend for Dynamic dashboard 
Like currently we have the UI of the dashboard but i want to make it completely dynamic like from their i will fetch the original details From the backend and make it completely dynamic 
 And want to fix the bug with the blogs comment field it is not adjusted for dark mode 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4c405aae-b682-4c44-ad91-5cb189fcea46)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
