### ISSUE TITLE
Add image adding guidelines in contributing guidelines document

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

For better SEO, we should use specific format of images, this should be added in contributing guidelines for all the contributors to know to maintain the image format throughout the website 
- also fix the non visible images in readme file

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
you are assigned @vansh-codes

**Comment by vansh-codes** [comment]
Completed 🥳
