### ISSUE TITLE
Feat: hover effects on card in about us page 

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#1178]
### Describe the feature

i would like to add some hover effects on cards of about us page

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a70f0bfe-9b7f-4de5-ada7-6b25bc9c4d40)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @dhairyagothi as of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
