### ISSUE TITLE
Feat: Want to do forum Questions page responsive and dark mode optimised

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1179]
### Describe the feature

I want to make the Particular question page responsive 
I also want to create the dark mode for that 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ccbbaeb1-b0f6-4c3a-bff2-4a61bf4248e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned.
