### ISSUE TITLE
Feat: Fashionable cursor

### ISSUE THREAD

**Issue by Khushi-Pushkar** [mdazfar2/HelpOps-Hub#1185]
### Describe the feature

I would like to add fashionable cursor

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @Khushi-Pushkar Thank you so much for your raising issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
