### ISSUE TITLE
Feat: Modify the font style of the entire website .

### ISSUE THREAD

**Issue by meetarora10** [mdazfar2/HelpOps-Hub#1186]
### Describe the feature

Current font style of the website is ordinary one and not much attractive . Assign this task to me and I can change it to a much better font such as Poppins .

### Add ScreenShots

![Screenshot (849)](https://github.com/user-attachments/assets/c1c9862e-9963-4554-8905-df6dcf7e0bf3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @meetarora10 Thank you so much for your raising issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you
