### ISSUE TITLE
BUG: Fix dark mode for devopsForum page

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/71263ac9-3777-4902-b51e-cc232c932b45)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
