### ISSUE TITLE
BUG: Change .png images to .webp and restructure the folder which contains images

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- As seen in the image below, the image folder in getting messed up with a new folder inside the public folder creating confusion for the contributors, I will organize this folder, remove duplicate images with .png images and keeping only .webp format of images. 
- Also many contributors have added images in .png or .jpg format which is not good in terms of SEO, I would like to convert this images to .webp

![image](https://github.com/user-attachments/assets/c55a7f45-1361-45c1-a20e-e7a7a7e994bf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes go ahead.
