### ISSUE TITLE
[Feat]: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#12]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

![Close Old PRs](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/ee245b98-c684-493e-b7fe-bed647c53d2e)

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
You are assigned @Asymtode712
