### ISSUE TITLE
BUG: `Remove` unwanted output statements from the console 

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

We can see many statements in the console which **hampers** the performance of the website, also there are statements which leak private data of the user. This can be a potential risk to user's data as a **smart hacker** can use this to steal the data and misuse.
We contributors add console statements to check the working of the features/functionalities but many contributors have forgot to remove this statements. 

**I want to remove all such console logs which are not required and causes performance issues and privacy risk too**

![image](https://github.com/user-attachments/assets/f6b71a9c-fe03-4bc0-b6cf-7e0308cf5edf)
![image](https://github.com/user-attachments/assets/3dbdc1db-305f-4edc-9954-3af2de33a634)
![image](https://github.com/user-attachments/assets/9f96fd3b-002b-4531-863a-b2f0ecde938e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes issue acknowledged! you are assigned.
