### ISSUE TITLE
Feat: `Add` robots.txt file in the parent directory for SEO optimization

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1202]
### Describe the feature

A robots.txt file tells search engine crawlers which URLs the crawler can access on your site. This is used mainly to avoid overloading your site with requests

This is an example of robots.txt file
![image](https://github.com/user-attachments/assets/a7bb6a42-3e77-4102-aa45-a9827e32d7ff)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/bf5e26a1-b4f7-41d4-adc1-9c0986d7a028)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes Yes we need you are assigned.
