### ISSUE TITLE
Feat: Want to create a modal UI for users involved in questions on hovering with dark mode enabled 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1205]
### Describe the feature

I want to create a which will be shown when user hovered on any user image those are involved in the questions
I will also create dark mode for that

### Add ScreenShots

![image](https://github.com/user-attachments/assets/50222a4a-022e-4d69-9ef6-102c57a2b0cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 issue acknowledged! Uou are going to be assigned.
