### ISSUE TITLE
Feat:Designing and Addition of Ask Question for Forum Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#1213]
### Describe the feature

**Description:**

The "Ask Question" page for the forum needs to be designed and developed to offer users an efficient and user-friendly platform for posting their questions on the DevOps forum of HelpOpsHub's website
I would like to design and implement the whole frontend for "Ask Question" page for the forum page.

### Add ScreenShots

![Ask Your Question](https://github.com/user-attachments/assets/dc68f99b-9500-4f33-8c86-62b16a558cab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned.
