### ISSUE TITLE
Feat: Add and Enhance: Make the website Progressive Web Application (PWA) and SEO modifications

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#1215]
### Describe the feature

A `Progressive Web App (PWA)` is a type of web application that combines the best features of both web and native apps. PWAs leverage modern web technologies to deliver a user experience that is fast, reliable, and engaging, even under unreliable network conditions.

**Key Characteristics of PWAs**
- Offline Capabilities: Using service workers, PWAs can cache assets and data, allowing the app to function offline or in areas with poor connectivity.
- App-like Experience: PWAs provide a user experience similar to native apps, including smooth navigation and interactions, full-screen mode, and more.
- Installable: Users can add PWAs to their home screen without going through an app store. Once installed, PWAs appear and function like native apps.
- Linkable: PWAs can be shared via URL, making them easily discoverable and shareable.

**Benefits of PWAs**
- Improved Performance: By caching assets and data locally, PWAs reduce load times and provide a smoother user experience.
- Increased Engagement: Features like push notifications, home screen installation, and offline capabilities keep users engaged.
- Lower Development Costs: PWAs eliminate the need to develop separate apps for different platforms, reducing development and maintenance costs.
- Broader Reach: Since PWAs are web-based, they are accessible to a wider audience, including users on different devices and platforms.
- No App Store Dependence: PWAs can be installed directly from the web, bypassing the need for app store approval and updates.

By making this changes, users will be able to install the website as an `app`, this also enhances SEO for the website.

Users will get download icon like this shown below after the changes⬇️ 
![image](https://github.com/user-attachments/assets/8e466f2b-aab5-46df-bdbd-387e643817fd)

**SEO Modifications:**
- Add more relevant keywords 
- Add appropriate meta tags and description keeping SEO in mind which will be visible on google search 
- Add multiple aspect ratio logos for different screen sizes
- Add multiple aspect ratio logos for different screen sizes for apple devices like iPad, iPhone and mac laptops
- Add canonical link

### Add ScreenShots

Added screenshots above

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes go ahead
