### ISSUE TITLE
Feat: Want to add auto filling of details in the Profile Modal 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1216]
### Describe the feature

I want to add the auto filling feature where details will be autofilled automatically when user will open the edit modal 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3546032d-a5f7-44aa-9ed2-25ca24e3a531)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned
