### ISSUE TITLE
Error on fetching contributons data 

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 I have look that  error no fetching contributors data
please assign me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 you are assigned
