### ISSUE TITLE
Feat:  updating inedex.html

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [mdazfar2/HelpOps-Hub#1220]
### Describe the feature

Use more semantic HTML elements for better structure and accessibility.
Add meta tags for SEO and social media sharing

### Add ScreenShots

HTML document will be more accessible, maintainable, and optimized for both users and search engines.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@AKSHITHA-CHILUKA, check the previous reply on your PR and issue as well. I noticed that you create issues and PRs directly, which doesn't make any sense. Thank you.
