### ISSUE TITLE
Feat:add styles.css

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [mdazfar2/HelpOps-Hub#1222]
### Describe the feature

add styles.css in [Ansible Httpd Docker](https://github.com/mdazfar2/HelpOps-Hub/tree/main/Ansible%20Httpd%20Docker)

### Add ScreenShots

Add meta tags for SEO and social media sharing. 
Use flexible units and remove fixed heights to improve responsiveness

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@AKSHITHA-CHILUKA, please don't create issues again and again. I saw you created a pull request without assigning your issue. As I mentioned in the previous PR, please try to check GitHub notifications also.
