### ISSUE TITLE
Feat: Want to create the complete Report  Componenet UI for the admin panel and want to implement the Structure for graph

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1224]
### Describe the feature

I want to create a complete UI of the Report for admin panel
I also want to implement the structure for the graph 

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
