### ISSUE TITLE
Add 'back to top' button

### ISSUE THREAD

**Issue by PDBharadwaj** [mdazfar2/HelpOps-Hub#1232]
### Describe the feature

I would like to add "back to top" button in home page which enables the user to return to top position of the page in the website.
I would like to work on this issue. Please assign it to me.

### Add ScreenShots

![Screenshot 2024-07-29 100357](https://github.com/user-attachments/assets/c511f3b6-d041-42ac-8a44-2b54eaead71f)
Here, 'back to top' button is missing. Then, it becomes time consuming for the user to return to the topmost position of the page. So, I would like to add this feature.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@PDBharadwaj thank you for your issue.

As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
