### ISSUE TITLE
Feat: Add hovering effects for devopsforum Footer links and icons for both the themes

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#1237]
### Describe the feature

Currently, our website's Devops Forum page's footer doesn't have any hovering effects for the icons and links present in it, I would like to add hovering effects for them for both the themes - light and dark theme

### Add ScreenShots

https://github.com/user-attachments/assets/4a5ee7ff-ebd4-4f77-b21d-9aa3955c1684

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Asymtode712 assigned
