### ISSUE TITLE
Feat: Complete Backend Integration for votes for the forums single question and want to fix bug text formatter is not showing 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1243]
### Describe the feature

I want to Implement the complete backend Integration for the  upvotes and downvotes for the forums single question 
With the help of that user is able to do real time like if he likes the question and can dislike if he doesn't like that question 
I also want to fix the bug in the text formatter like it is not showing in the deployed version 

## For @sanjay-kv  sir 
Sir i am mentioning you here to clear some points so that i will not have to suffer again 
Sir by seeing likes , comments you may thought that its for blogs but the forum page is available for everyone from more than one week and no one did that so i just mentioned you here to inform you  that only two days are left so  i will implement these likes and comments functionality  for that question forums page 
![image](https://github.com/user-attachments/assets/fb7b124b-26f0-437d-b904-3e50bae17315)

So please don't consider it as a duplicate for the blogs likes and comments that are totally different things from that 
The code i have to write is completely different from each other 

### Add ScreenShots

bug 
![image](https://github.com/user-attachments/assets/14e4e76c-2f47-47b8-8d8a-b35e1a77c99f)

Original 
![image](https://github.com/user-attachments/assets/26506e81-032c-4171-8dfe-94042b3536dc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 issue acknowledged! You are assigned.
