### ISSUE TITLE
There is a overlap of text and logo

### ISSUE THREAD

**Issue by GAGGZ1** [mdazfar2/HelpOps-Hub#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When viewing the webpage/application, a bug has been observed where there is an overlap of text and logo elements. This overlap occurs when certain conditions are met, such as specific screen resolutions, browser types, or device orientations. The text and logo, which are intended to be displayed separately and clearly, appear to be positioned on top of each other, leading to a visual clutter and potentially hindering the readability of the text or the visibility of the logo. This issue can detract from the overall user experience and may need to be addressed to ensure proper displa
![WhatsApp Image 2024-06-04 at 02 18 31_e99b0c8f](https://github.com/mdazfar2/HelpOps-Hub/assets/81284966/fd779631-b884-43a5-aaa6-8dd17b91449c)
y and functionality across different viewing environments.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GAGGZ1** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@GAGGZ1 Great issue find 👏

- You are assigned ✔️

**Comment by mdazfar2** [comment]
@GAGGZ1 try to remove background white image of logo
