### ISSUE TITLE
Topic: Agile and Scrum Practices in DevOps

### ISSUE THREAD

**Issue by sreevidya-16** [mdazfar2/HelpOps-Hub#1256]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

Agile and Scrum Practices in DevOps
@mdazfar2, assign me this issue under GSSOC'24

### How many and what types of DevOps tools are you adding?

Agile and Scrum Practices in DevOps

### How many years of experience do you have in the DevOps field?

2 months

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
Hey @sreevidya-16 

Thank you for creating issue.

- I saw that you created 4 issues continuously, which is not a good practice in open source. It shows that you are contributing just to get points.

- You said you have 2 months of experience in DevOps, but I visited your GitHub and LinkedIn and found nothing related to DevOps. How can you create documentation that really helps others? Also, there's no need to create a PR with AI-generated prompts.

- Sorry, I apologize. Don't be discouraged, but I cannot assign all 4 issues to you that you created.

**Comment by sreevidya-16** [comment]
Devops was there in our academics(this semester)
That's the reason, I have kept 2 months experience @mdazfar2

**Comment by sreevidya-16** [comment]
"I saw that you created 4 issues continuously, which is not a good practice in open source. It shows that you are contributing just to get points."

Sorry I don't know about this

**Comment by mdazfar2** [comment]
@sreevidya-16

Experience is gained by practicing, which you have not practiced anywhere as I saw. I guess you have good experience in DSA, AI/ML, and databases, but there is no DevOps experience mentioned on your profile.

**Comment by mdazfar2** [comment]
> "I saw that you created 4 issues continuously, which is not a good practice in open source. It shows that you are contributing just to get points."
> 
> Sorry I don't know about this


<br>

I'm talking about GSSOC'24 points and nothing else. Thank you! @sreevidya-16
