### ISSUE TITLE
Feat: Header Improvements

### ISSUE THREAD

**Issue by sau-mili** [mdazfar2/HelpOps-Hub#1259]
### Describe the feature

Currently. when we scroll down, the Navbar gets hidden so it is not visible.
I wish to add functionality to the header such that when page is scrolled, the header stays on top using javascript function.

### Add ScreenShots

currently when scrolled:
![image](https://github.com/user-attachments/assets/ffc35fab-95fd-4173-a576-e5c5eec163ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @sau-mili thank you for creating the issue.

- But when you scroll up a little, you get the navbar. While scrolling down, we hide the navbar so the user doesn't feel weird seeing it. I apologize, but I need to close this issue for now. Please don't be discouraged!
