### ISSUE TITLE
Add new page for Help

### ISSUE THREAD

**Issue by mahek0620** [mdazfar2/HelpOps-Hub#1271]
### Describe the feature

In this we will add the FAQs part provide option for Need more help and also feedback form

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @mahek0620 thank you for creating the issue.

As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
