### ISSUE TITLE
Feat: Adding Chatbot to the website.

### ISSUE THREAD

**Issue by Ojas-Arora** [mdazfar2/HelpOps-Hub#1276]
### Describe the feature

@mdazfar2 I want to add chatbot to the website. Kindy assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-16 001942](https://github.com/user-attachments/assets/223f49fd-cbe6-49a6-97ba-1a4756f0e5a8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @Ojas-Arora Tha k you for raising the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
