### ISSUE TITLE
Feat: Add hover effects on the cards on the about us page similar to other pages . 

### ISSUE THREAD

**Issue by meetarora10** [mdazfar2/HelpOps-Hub#1284]
### Describe the feature

I want to add hover effects on the cards on the about us page similar to other pages . 

### Add ScreenShots

![Screenshot (919)](https://github.com/user-attachments/assets/8c7219b0-26e9-4e6d-8fab-4511cdfc0e38)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@meetarora10 Thank you for raising the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
