### ISSUE TITLE
NOT Visible on hover

### ISSUE THREAD

**Issue by Utsavladia** [mdazfar2/HelpOps-Hub#1285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/be34fe72-428d-4bf0-bb90-a31069ce8ece)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Utsavladia Not visible on hover what? Please elaborate which I'm happy to assign this issue to you.

**Comment by Utsavladia** [comment]
@mdazfar2 
The loogin and sposor buttons are not visible properly on hover

**Comment by mdazfar2** [comment]
@Utsavladia 

The sponsor button is visible well even the login/signup is not visible

**Comment by Utsavladia** [comment]
@mdazfar2 
In the screenshot you can see the buttons is not visible properly on hover it should have hover with some background

![image](https://github.com/user-attachments/assets/a8f0e8e0-f839-4609-a69e-f1bad3515fa2)
![image](https://github.com/user-attachments/assets/82544ee7-1417-418d-9d7b-527c3fe081aa)

**Comment by mdazfar2** [comment]
@Utsavladia issue acknowledged! You are going to be assigned.
