### ISSUE TITLE
Feat: Add Zoom and Box Shadow Hover Effect on Cards in "Benefits of HelpOps-Hub" Section on About Page

### ISSUE THREAD

**Issue by AsmitaMishra24** [mdazfar2/HelpOps-Hub#1286]
### Describe the feature

I would like to suggest adding a hover effect that includes a zoom and box shadow to the cards in the "Benefits of HelpOps-Hub" section on the about page. This enhancement will improve the user experience by making the interactive nature of the cards more apparent. Currently, the cards in the "Benefits of HelpOps-Hub" section do not have any hover effect, making it unclear if they are meant to be interactive.

### Add ScreenShots

![Screenshot 2024-08-02 124229](https://github.com/user-attachments/assets/224f13db-6c5c-4de8-a20b-642bc1919b90)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @AsmitaMishra24 thank you for raising the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
