### ISSUE TITLE
Topic: want to add docker python and java example 

### ISSUE THREAD

**Issue by NAVJOT-786** [mdazfar2/HelpOps-Hub#1289]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

i want to add docker java and docker python example with commands in the docker knowledge it will make the docker understanding easy

### How many and what types of DevOps tools are you adding?

I want to add 2 examples of how docker create and process images 

### How many years of experience do you have in the DevOps field?

1 year

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [ ] Soon, I'll complete it and create a Pull Request.
- [ ] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
Hey @sreevidya-16 

Thank you for creating issue.

- You said you have one year of experience in DevOps, but I visited your GitHub and LinkedIn and found nothing related to DevOps. How can you create documentation that really helps others? Also, there's no need to create a PR with AI-generated prompts.

- Sorry, I apologize. Don't be discouraged, but I cannot assign all 4 issues to you that you created.
