### ISSUE TITLE
[Project] Deploying netflix with DevSecOps part 1(Containerization with Dockers,orchestration with kubernetes)

### ISSUE THREAD

**Issue by litesh1123** [mdazfar2/HelpOps-Hub#13]
In this part of  project I will be demonstrate how to Deploy Netflix clone with DevSecOps .
In this part of project I would deploy netflix using 
>containerization with docker
>orchestration with kubernetes

**Comment by mdazfar2** [comment]
@litesh1123  go ahead to the project, Create folder `Deploying Netflix Clone with DevSecOps` in the root directories.

**Comment by litesh1123** [comment]
@mdazfar2 OK thank you
