### ISSUE TITLE
BUG: Feedback form issues.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- The feedback form does not display a message after submission and reloads automatically, which is problematic.
- The form allows submission without checking if the rating input is filled.
- I want to solve these two bugs using JavaScript.
- I aim to provide this solution at a level 2 complexity, if possible.

https://www.loom.com/share/b9863b559b2647a0897c3ad2608a6781

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy You are assigned

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
