### ISSUE TITLE
Feat: Want to add about JIRA

### ISSUE THREAD

**Issue by sreevidya-16** [mdazfar2/HelpOps-Hub#1314]
### Describe the feature

I want to add topics on JIRA
 - What is JIRA ?
 - How is it used in software development projects?
 - How does Jira support Agile methodologies ?
 - What are the advantages of using Jira for tracking issues and bugs in a DevOps ?
 - What is a Jira workflow ?
 - How do you monitor and report on the progress of a DevOps project using Jira?
 - How does Jira integrate with Git?
 - What is JIRA workflow ?

I have basic level understanding in the domain - "Devops"
But during my academics, I have gained knowledge regarding Software Engineering, Agile methodoligies and some basic Devops concepts.

So I will explore and gain the best content to write into this article.

@mdazfar2, could you please assign me this issue under GSSOC'24 ?

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sreevidya-16 Thank you so much for raising the issue, but I think it is not needed, so please don't be discouraged. I have to close this issue. If you want to share documents related to DevOps, please create an issue in the `DevOps-Topics` template.
