### ISSUE TITLE
Topic: 3P's of Devops

### ISSUE THREAD

**Issue by sreevidya-16** [mdazfar2/HelpOps-Hub#1318]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

I want to add about Three P's of Devops 

### How many and what types of DevOps tools are you adding?

NA, it's document updation

### How many years of experience do you have in the DevOps field?

I have only basic understanding in devops.
But during my academics, I have gained knowledge regarding Software Engineering, Agile methodoligies and some basic Devops concepts.

So I will explore and gain the best content to write into this article.

@mdazfar2, assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
@sreevidya-16 as of now we don't need this. If you want to work on another issue, please raise any other issue except DevOps documentation. You already had 7-8 issues closed, which is not a good thing. It seems you are raising issues just to get GSSOC'24 points and nothing else. Please contribute to issues that our website really needs and can help with SEO. Thank you!
