### ISSUE TITLE
Feat: No Repository Found text display

### ISSUE THREAD

**Issue by SrinivasDevolper** [mdazfar2/HelpOps-Hub#132]
### Describe the feature

When the user searches the wrong text in the search bar then there should be the **No Repository Found** text display and The search bar should have the wrong icon button

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

### Add ScreenShots

<img width="721" alt="wrong butotn" src="https://github.com/mdazfar2/HelpOps-Hub/assets/121508628/3f57072e-3257-4c8e-85f9-6198e5dde11b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@SrinivasDevolper You are assigned ✔️

- Great issue, but instead of repository, you have to write Topics, meaning `No Topics Found`, and also change the name from `search repository` to `search topics...`
