### ISSUE TITLE
Topic : Add Prometheus cheatsheet

### ISSUE THREAD

**Issue by Pujan-sarkar** [mdazfar2/HelpOps-Hub#1321]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

Prometheus Cheatsheet: Suggested Topics
Installation and Setup

Topics: Basic installation steps for Prometheus on different platforms (Docker, Kubernetes, standalone).
Content: Commands and configuration steps to get Prometheus up and running.
Prometheus Configuration

Topics: Configuring Prometheus using the prometheus.yml file.
Content: Key configuration sections like global, scrape_configs, alerting, and rule_files.
Metric Types

Topics: Understanding different Prometheus metric types like Counters, Gauges, Histograms, and Summaries.
Content: Descriptions, use cases, and example PromQL queries for each metric type.
PromQL Basics

Topics: Introduction to Prometheus Query Language (PromQL).
Content: Basic syntax, operators, and functions used in PromQL. Example queries to illustrate concepts.
Alerting Rules

Topics: Creating and managing alerting rules.
Content: How to define alerting rules in Prometheus, configuring Alertmanager, and common alerting patterns.
Service Discovery

Topics: Integrating Prometheus with various service discovery mechanisms.
Content: Configuring Prometheus to automatically discover targets in Kubernetes, AWS, or other environments.
Exporters

Topics: Using exporters to collect metrics from various services.
Content: Common exporters like Node Exporter, Blackbox Exporter, and how to set them up.
Dashboards and Visualization

Topics: Integrating Prometheus with Grafana for visualization.
Content: Setting up Grafana with Prometheus as a data source, creating basic dashboards, and best practices.
Prometheus Best Practices

Topics: Tips for efficient use of Prometheus.
Content: How to optimize queries, manage high cardinality metrics, and ensure reliable monitoring.
Troubleshooting

Topics: Common issues and how to resolve them.
Content: Tips for debugging Prometheus configurations, performance issues, and alerting problems.

### How many and what types of DevOps tools are you adding?

Suggested Tools for the Prometheus Cheatsheet:
Prometheus (Core tool)
Node Exporter (Metrics collection from *nix systems)
Blackbox Exporter (Endpoint probing)
Alertmanager (Alert management)
Grafana (Metrics visualization)
Kubernetes (Service discovery and orchestration)
Consul (Service discovery)
Vault (Security and secrets management)

### How many years of experience do you have in the DevOps field?

6 months+

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
Hey @Pujan-sarkar  

Thank you for creating the issue.

- As you create an issue with a description that doesn’t make sense, it verifies that you created the issue with the help of any AI prompt (ChatGPT, Bard, etc.). This is not a good practice. If you create issues using AI prompts, how can you create good documentation, which is essential for DevOps enthusiasts?

- You said you have 6 months + of experience in DevOps, but I visited your GitHub and LinkedIn and found nothing related to DevOps. How can you create documentation that really helps others? Also, there's no need to create a PR with AI-generated prompts.

- Sorry, I apologize. Don't be discouraged, but I cannot assign your issue to you that you created.
