### ISSUE TITLE
Feat: Want to create the Terms and conditions page  from Scratch

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1322]
### Describe the feature

I will create a terms and conditions page from scratch 

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by KiranBaliga** [comment]
Is it okay for me to start working on this issue?

**Comment by mdazfar2** [comment]
> Is it okay for me to start working on this issue?

Sure @KiranBaliga, go ahead.

- You are now going to be assigned.
- Create a Terms & Conditions page that is clean and beautiful, and matches our website.
- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)
