### ISSUE TITLE
Feat: Adding Animation

### ISSUE THREAD

**Issue by harshmishra19** [mdazfar2/HelpOps-Hub#1324]
### Describe the feature

Your Home page already looks fantastic, but incorporating animations on the laptop image could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.
An animation on the image of your home page which will keep on moving and will make you page look more Appealing

### Add ScreenShots

![helpops](https://github.com/user-attachments/assets/024fcbd8-9b93-41b9-823b-64d1d688d831)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@harshmishra19 If you share a demo video according to your experience, it will help me assign this issue to you.

**Comment by harshmishra19** [comment]
https://github.com/user-attachments/assets/bb1a8137-b71a-4877-920e-fd4f3eb1f21e

**Comment by harshmishra19** [comment]
@mdazfar2

**Comment by mdazfar2** [comment]
@harshmishra19 Actually, we already implemented this in the past, but we removed this feature as it didn't look nice and professional. Please search for another issue and raise it, which I'm happy to assign to you.

---

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo
