### ISSUE TITLE
Contributing under GSSOC'24. Adding docx having implementation of basic commands in linux

### ISSUE THREAD

**Issue by rugved0102** [mdazfar2/HelpOps-Hub#1325]
![image](https://github.com/user-attachments/assets/1336bc2e-c178-4199-b6c3-c0e8a24e1bf2)

**Comment by rugved0102** [comment]
I have a docx full of basic cmds for linux bash shell, I think it will be very helpful for a beginner who is interested in learning bash scripting.

**Comment by mdazfar2** [comment]
Hey @rugved0102, thank you for creating the issue.

As it is not needed, it is already done by someone else. Please search for another issue and raise it, which I'm happy to assign to you.
