### ISSUE TITLE
Feat: Adding a Proper Footer to the Project

### ISSUE THREAD

**Issue by lovelymahor** [mdazfar2/HelpOps-Hub#1334]
### Describe the feature

I need to add a properly designed footer to my website project. The footer should include the following elements:

Social media links with corresponding icons (e.g., Facebook, Twitter, LinkedIn)
A newsletter subscription section
Contact information
A copyright notice
Quick links to important pages (e.g., Home, About, Services, Contact)

### Add ScreenShots

![Screenshot (344)](https://github.com/user-attachments/assets/0602fffb-d33f-42dd-ae78-9848e3de802a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
@HelpOps-hub
I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by mdazfar2** [comment]
Hey @lovelymahor,

Thank you so much for creating the issue. As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
