### ISSUE TITLE
Use placeholder API key

### ISSUE THREAD

**Issue by bukinoshita** [mdazfar2/HelpOps-Hub#1339]
I don't know if this API key is still valid or not, but it would be good to not expose real API keys and use a placeholder one or add behind an environment variable.

If it's a valid API key, I'd also recommend going into resend and rotate that API key.

https://github.com/mdazfar2/HelpOps-Hub/blob/5ac463d270939bef5b1a5b8f6041b22029fe2129/website3.0/src/app/api/login/route.js#L9

**Comment by mdazfar2** [comment]
@bukinoshita Thank you for letting me know. I will get it done as soon as possible.
