### ISSUE TITLE
Makeover of contributor page 

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

fixing of 
 alligment in hadder , 
added loading animation that is takel form javascript , 
short name of contributor for better alligment , fixed card over flow 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 you are assigned
