### ISSUE TITLE
Want to enhance the CONTRIBUTING.md file documentation

### ISSUE THREAD

**Issue by muhafiz5814** [mdazfar2/HelpOps-Hub#1351]
There are some typos and some incomplete sentences I found while reading the contribution guide. Also there is some improvement in git commands.
I have already fixed these in my forked repo and will create a PR once you assign me this issue and will work on any review you provide.

**Comment by mdazfar2** [comment]
Hi @muhafiz5814,

Thank you for raising the issue! Could you please specify the changes you'd like to make and where you'd like to implement them? This information will help me assign the issue effectively.

**Comment by mdazfar2** [comment]
@muhafiz5814 Can you please raise issue for [Ezyshop](https://github.com/mdazfar2/ezyshop) because we don't have any contributing guidelines please visit  [Ezyshop](https://github.com/mdazfar2/ezyshop). Thank you!
