### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by archanasingh11** [mdazfar2/HelpOps-Hub#1354]
### Description

**Description:**

The HelpOps-Hub website currently lacks a **"Scroll to Top"** button, which is a key feature for enhancing user experience, especially on pages with extensive content. Without this button, users have to manually scroll back to the top of the page, which can be inconvenient and time-consuming.

Implementing a **"Scroll to Top"** button would:
- Improve the website's accessibility and usability.
- Provide a smoother navigation experience, particularly on long articles or blog posts.
- Align the user interface with modern design practices.

I recommend adding a floating "Scroll to Top" button that becomes visible as users scroll down the page.

Please @mdazfar2 assign me this task with labels "GSSOC-Ext", "Hacktoberfest-accepted" and "level1".

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @archanasingh11, thank you for creating the issue.

As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue, and I’m happy to assign it to you.
