### ISSUE TITLE
[BUG] active page is not highlighted 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/HelpOps-Hub#1368]
### Description

the active page is not highlighted in the list of pages in navbar in desktop view and sidebar in mobile view

### Screenshots
![image](https://github.com/user-attachments/assets/32832cb8-4c7b-4939-b728-416a1ccee3ee)

![image](https://github.com/user-attachments/assets/d401712e-967b-481b-886c-1a68b1664a82)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by ShivanshPlays** [comment]
ok thanks!!
