### ISSUE TITLE
[BUG] loader not showing in the blogs page

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/HelpOps-Hub#1369]
### Description

when we refresh the blogs page, there is no loader present, it appears for a moment and then there is only blank section and then blogs appear, this is bad ui.

Please assign me this issue under level2 gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

### Screenshots

![image](https://github.com/user-attachments/assets/9783ee19-97d1-44bb-b0aa-cec111145538)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays You are assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

**Comment by ShivanshPlays** [comment]
I'm on it, thanks :)

**Comment by harish08102004** [comment]
Hey @mdazfar2 I have worked on similar issue, if no one is working on this I can work.
