### ISSUE TITLE
Feat: Full Responsive website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#137]
### Describe the feature

I will make the whole website  fully responsive that is responsive for all devices .

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/29edc9c1-7859-4be0-a638-f326ae0633f8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 You are assigned ✔️

- Please share similar demo video while create pull reques.

**Comment by Ayushmaanagarwal1211** [comment]
Sure
