### ISSUE TITLE
[BUG] Mark as solve button showing for every user 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#1370]
### Description

The mark as solve is showing for all users 
It must be shown to only author of that question 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ShivanshPlays** [comment]
I will be happy to work on this issue!

**Comment by mdazfar2** [comment]
Hey @Ayushmaanagarwal1211 great issue found! You are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).

- Don't forget to join our official [Discord server](https://discord.gg/KfpCHPW5).
- And also follow us on [Linkedin](https://linkedin.com/company/helpops-hub/)
- And please ⭐ our repo
