### ISSUE TITLE
Text overflow in mobile view in qna section 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/HelpOps-Hub#1372]
### Description

Please assign me this issue under gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

### Screenshots

![IMG_7534](https://github.com/user-attachments/assets/306dbcd3-5c61-4de0-a58c-6939a939f8e8)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays, Issue acknowledged! you are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).

- Don't forget to join our official [Discord server](https://discord.gg/KfpCHPW5).
- And also follow us on [Linkedin](https://linkedin.com/company/helpops-hub/)
- And please ⭐ our repo
