### ISSUE TITLE
Banner of blog not displaying correctly

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/HelpOps-Hub#1373]
### Description

The banner is trimmed from the sides at smaller screen sizes.

Please assign me this issue under level2 gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

### Screenshots

![IMG_7531](https://github.com/user-attachments/assets/de8f9967-2661-483f-8bd4-2215620fab17)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays go ahead.

- Don't forget to give our repository a star and let me know once you've done it.
