### ISSUE TITLE
Grow your reach page, UI, breaking at smaller screen sizes

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/HelpOps-Hub#1374]
### Description

As you can see in the attached screenshot, the user interface is baking at a mobile screen size

Please assign me this issue under level2 gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

### Screenshots

![IMG_7533](https://github.com/user-attachments/assets/ef1b21fd-9856-4af9-af59-24b027d83330)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.

- Don't forget to give our repository a star and let me know once you've done it.

**Comment by harish08102004** [comment]
Hey @mdazfar2 if this issue still open, I can work on this.

**Comment by mdazfar2** [comment]
Hey @harish08102004 This issue was raised by Shivansh, so I would suggest asking him to assign it to you. If he permits, I can then assign the issue to you to work on it. _Thank you!_

**Comment by harish08102004** [comment]
Hey since you are this project's admin, So I guess you have the right to assign if somebody is not closed their issue even after 5 days.
