### ISSUE TITLE
Unnecessary spacing in active filter marker

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/HelpOps-Hub#1375]
### Description

As you can notice in the attached screenshot that the border bottom marking the active filter has an unnecessary space, which does not look good in mobile view of the application.

Please assign me this issue under level2 gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

### Screenshots

![IMG_7532](https://github.com/user-attachments/assets/766d3b1a-f8ba-4058-9754-b4238acf3a46)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.

**Comment by roushan-code** [comment]
could you assign it to me? 
I would like to work on it.

**Comment by mdazfar2** [comment]
Hey @roushan-code This issue was raised by Shivansh, so I would suggest asking him to assign it to you. If he permits, I can then assign the issue to you to work on it. Thank you!

**Comment by roushan-code** [comment]
I think, As a project admin you have authority to assign issue. 

 # According to GSSoC guideline
reference(https://gssoc.girlscript.tech/info)

- The contributors are free to choose & contribute to multiple projects but they need to submit PRs to the assigned issues within the fixed time bar set by the particular project; failing to do so shall result in reassigning of the issue to someone else.

**Comment by mdazfar2** [comment]
Hey @ShivanshPlays, is it okay with you if I assign Roushan? It's been a long day since you raised the issue and left it as is, and you still have not responded. 

Let me know if you will continue your work on that issue or if I should assign it to Roushan.

**Comment by mdazfar2** [comment]
@roushan-code you are assigned.


- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)
