### ISSUE TITLE
[BUG] Add Zoom Effect on Card in Opportunity page

### ISSUE THREAD

**Issue by iamsohelx** [mdazfar2/HelpOps-Hub#1377]
## Description
hey @mdazfar2  We need to improve Cards in About page add some transition and smooth animation to improve user experience.
We can add a smooth zoom effect on user hover on it.

## Screenshot
![zoomScale](https://github.com/user-attachments/assets/218e552e-b79e-4e68-b167-e36934870c9c)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by iamsohelx** [comment]
Hiii @mdazfar2 Could you please assign me this task. I wanted to work on this please.

**Comment by mdazfar2** [comment]
@iamsohelx The effect doesn't look good everywhere. We have not decided on adding it like this. Thank you for raising the issue.
