### ISSUE TITLE
[Feat] Add a Scroll on top button

### ISSUE THREAD

**Issue by devarsheecodess** [mdazfar2/HelpOps-Hub#1379]
### Description

 want to add a scroll on top button to this website which will scroll the page on top when clicked. @mdazfar2 , assign me this issue under gssoc-ext, hacktoberfest-accepted and level2 labels

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@devarsheecodess As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
