### ISSUE TITLE
[BUG] TYPO in error message

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/HelpOps-Hub#1381]
### Description

charachter - > character

### Screenshots

![Screenshot 2024-10-07 190208](https://github.com/user-attachments/assets/149888a0-817e-4997-9d50-d5ff69d7592d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by NitishKumar525** [comment]
Hey @mdazfar2, I completed these changes as I see that it has been open for 12 hours and other issues have occurred. Please assign this issue to me, and I will raise a PR for it.

**Comment by mdazfar2** [comment]
You are assigned @NitishKumar525

**Comment by ShivanshPlays** [comment]
Bro I dont think this is fair, I spend time searching for bugs and the cool down period is 3-4 days as @sanjay-kv sir said!
