### ISSUE TITLE
[BUG] Add Portfolio Link with Icon to Founder Card

### ISSUE THREAD

**Issue by NitishKumar525** [mdazfar2/HelpOps-Hub#1382]
### Description

On the team page of the HelpOps-Hub repository, I noticed that the founder card currently displays a GitHub icon with a link to the GitHub profile. To enhance the representation, I would like to replace the GitHub icon with a portfolio link that includes a suitable portfolio icon. This will give users direct access to the founder's portfolio, showcasing their work in a more professional and visually appealing way.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@NitishKumar525 you are assigned.
