### ISSUE TITLE
Optimize an existing feature

### ISSUE THREAD

**Issue by Trumilnasit** [mdazfar2/HelpOps-Hub#1389]
I want to add labels when it's hover on various dev-ops technology for better understanding and also wants to try to solve an issue when we go start now to anyone blogs it's showing an error to check the error in console of this web-site.
@mdazfar2 :-can you assign it to me with all badges and level3 or level2.

**Comment by mdazfar2** [comment]
@Trumilnasit, can you please describe clearly? I don't understand what you are trying to say. Please share a screenshot or any demo video related to what you mean so that I can understand and assign accordingly.
