### ISSUE TITLE
Banner is missing on contrubutor card

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Screenshot 2024-06-04 121247](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/09f7ade5-80ea-4909-aa45-00a1b681fbec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 assigned ✔️
