### ISSUE TITLE
Add mini chatbot to the website

### ISSUE THREAD

**Issue by say-het** [mdazfar2/HelpOps-Hub#1390]
Hey @mdazfar2 I have a great Idea.

 - Adding a mini AI based chatbot to website.

I am already working on this, please assign me this under gssoc-ext so I can raise a PR.

Little about me: I am an experienced contributor as I have successfully completed GSSoC-2024, Hacktoberfest-2020 and Hacktoberfest-2023.

**Comment by mdazfar2** [comment]
Hello @say-het, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by mdazfar2** [comment]
Hey @say-het, that's a great idea.

Is it possible to add a chatbot specifically for DevOps? I mean, when any DevOps professional or enthusiast asks queries related to DevOps, it should provide the correct answers. Hope you understand what I mean. Let me know if it’s possible.

**Comment by say-het** [comment]
Ya ya Its possible that the chatbot is specified for devops only.

**Comment by say-het** [comment]
Hey @mdazfar2 please assign me this issue.

**Comment by mdazfar2** [comment]
Hey @say-het, sorry for the late reply. I was actually busy somewhere. Can you please tell me where you placed the chatbot mini and what type of UI you want to use? Please let me know if it's working fine. I'm really serious about this project, so work on it as if it's your own.

**Comment by say-het** [comment]
Hey @mdazfar2,
Ya ya I would love to contribute as if its is my own project.
The UI I am thinking:
![image](https://github.com/user-attachments/assets/779ad0c3-c94d-4fa5-84af-76a251f47e1a)

It will show like a button on bottom left!
