### ISSUE TITLE
[BUG] "Delete Your Account" Popup Stuck on Light Theme Despite Dark Theme Selection

### ISSUE THREAD

**Issue by sezallagwal** [mdazfar2/HelpOps-Hub#1391]
### Description
@mdazfar2 
When clicking the "Delete Your Account" button, the popup modal does not switch to the selected dark theme. The popup only appears with light theme styling, even when the dark theme is selected. I have verified that the rest of the application follows the theme correctly, but the popup remains styled for the light theme.

I tried switching between light and dark themes multiple times, but the popup continues to use the light theme styling.

### Screenshots

![image](https://github.com/user-attachments/assets/b7920680-cce6-46fc-8f33-014cd4c78f08)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@sezallagwal You are assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)
