### ISSUE TITLE
Topic: EXTRA SPACES PRESENT IN CONTENT OF ABOUT SECTION.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [mdazfar2/HelpOps-Hub#1392]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

THE " What is HelpOps-Hub? " SECTION HAS EXTRA SPACES ADDED.

### How many and what types of DevOps tools are you adding?

space reduction. Documentation problem.

### How many years of experience do you have in the DevOps field?

beginner

### Record

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd.

**Comment by mdazfar2** [comment]
Hey @ABHISIKTAcommits, please describe it clearly. I guess your issue is not being raised on the correct issue template. Please choose the correct one and share a screenshot of what you exactly want to contribute. ***Thank you!***
