### ISSUE TITLE
[Feat] DevOps Workflow Simulator

### ISSUE THREAD

**Issue by muskan171105** [mdazfar2/HelpOps-Hub#1395]
### Description

A DevOps Workflow Simulator that allows users to simulate common DevOps workflows such as setting up CI/CD pipelines, container orchestration, automated testing, and infrastructure deployment. This feature will provide hands-on experience and help users understand the lifecycle of a DevOps process by guiding them through mock scenarios with popular DevOps tools.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @muskan171105 create issue with good template this issue is not matching the issue template.
