### ISSUE TITLE
"Join Us Now" Button Should Be Centered

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/HelpOps-Hub#1399]
### Description

The "Join Us Now" button is currently not positioned in the center of its container, which negatively impacts the visual alignment and overall user experience. Centering the button can enhance its prominence and make it more appealing to users.

### Current Behavior
- The "Join Us Now" button is misaligned and does not occupy a central position within its section, which can confuse users and detract from the design.

### Expected Behavior
- The "Join Us Now" button should be horizontally centered in its container to improve visibility and accessibility.

### Screenshots

![Screenshot 2024-10-15 150647](https://github.com/user-attachments/assets/57f1f1fe-834c-451b-a4da-8016abcd3dea)

### Any additional information?

- **Browser Compatibility**: This issue has been observed on Chrome and Firefox, but not tested on Safari.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace, issue acknowledged! You're going to be assigned.

Please ensure the `Join Us Now` button is centered, as highlighted in the red box in the screenshot.


![{4E42286F-8E55-4EC9-8C7E-4BBD019E4753}](https://github.com/user-attachments/assets/875ed0e6-f6a4-4656-8981-bf9a2f030eb4)
