### ISSUE TITLE
Load More Button Should Be Center-Aligned

### ISSUE THREAD

**Issue by Manikant69** [mdazfar2/HelpOps-Hub#1401]
### Description

The **Load More** button is currently misaligned, making the layout appear unbalanced. For a more aesthetically pleasing and user-friendly experience, the **Load More** button should be centered on the page, maintaining consistency with the overall design.

#### Steps to Reproduce:
1. Scroll down to the section containing the **Load More** button.
2. Observe the button's current alignment – it is not in the center of the page.

### Screenshots

![image](https://github.com/user-attachments/assets/c24d02ae-9c55-4a2a-a32f-fc3e800b31ea)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Manikant69 you are assigned.
