### ISSUE TITLE
[Feat] Logout option in menu bar

### ISSUE THREAD

**Issue by meghanakn473** [mdazfar2/HelpOps-Hub#1402]
### Description

Adding logout option to logout from their account wen they dont use it.

### Screenshots

@mdazfar2 please assign me this issue on level 3, gssoc-extd and Hacktoberfest 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @meghanakn473,

That's a great observation! While it's essential for most websites to have a logout feature, But this logout feature already available on our website. Please see the attached screen recording for proof.

<br>


https://github.com/user-attachments/assets/ab776087-e642-46a7-b44c-6b0b7e91961c

<br>

**After logging in**, click on your `profile` button. In the left-side menu at the bottom, you'll find the `Settings` button. Clicking on that will reveal the `logout` and `delete account` options.

- Please raise another issue, and I’ll be happy to assign it to you. Please review all aspects of the website, and I apologize if I said anything out of line.

- Don't forget to join our official [Discord](https://discord.gg/Gk9vTsNZ) Server
- Follow us on [Linkedin](https://www.linkedin.com/company/helpops-hub/)


***Thank You!***
