### ISSUE TITLE
Update the footer Ui

### ISSUE THREAD

**Issue by NK-Works** [mdazfar2/HelpOps-Hub#1404]
![image](https://github.com/user-attachments/assets/1a7ff34d-42a9-4e0a-886e-4a84eda828da)
The current footer is not very good and professional...
I make make it modern and professional

**Comment by mdazfar2** [comment]
@NK-Works, how can you make the footer more attractive? Do you have any design ideas for it?

**Comment by askarthikey** [comment]
heyy @mdazfar2 i am interested to work on this issue. Please assign me this

**Comment by NK-Works** [comment]
![image](https://github.com/user-attachments/assets/56da3d93-5f1b-4f02-af3e-a4fda66521d1)
I can make it something like this... (Minimalistic and clear)

**Comment by mdazfar2** [comment]
@NK-Works I think the UI of the footer is good according to our website. Please raise any other issue that is really needed for our website. As of now, I am closing this issue. Please don't be discouraged, I really appreciate your enthusiasm in open source. Keep going! **Thank you!**
