### ISSUE TITLE
Contact Us Backend

### ISSUE THREAD

**Issue by raj-mistry-01** [mdazfar2/HelpOps-Hub#1409]
@mdazfar2 

There is no backend for contact us 

How the website will keep track of what user wants (by reaching the website through the contact us but no backend)

I hope you will assign this issue to me under **hactoberfest** , Solution is that integrating the mongoDB with react further we can make it to MERN stack.

Thank you

**Comment by mdazfar2** [comment]
Oo Wow @raj-mistry-01, what an issue you found! Did you check from your side by filling out the form?

If you filled out the form, all the data would obviously come to my database. Please check correctly before contacting us on the "Contact Us" page, and make sure to enter a valid email address, okay? Thank you for raising the issue. If you understand, please close this issue as complete. If you still have doubts, feel free to mention me.

**Comment by raj-mistry-01** [comment]
My Mistake So Sorry for wasting your time , So sorry Really
