### ISSUE TITLE
Project Proposal:  Hiding Important Credentials

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#141]
### Overview

Hii I see that an api key is printed on the console but IMO it should be kept under .env file and i will also check for other credentials as well .

![Screenshot 2024-06-04 124217](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/76b401ac-6845-48e0-b939-1000b144ec6a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this project proposal

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 You have to work on the feedback form. I will remove the console log from my side.

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
