### ISSUE TITLE
[Feat]Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mdazfar2/HelpOps-Hub#1413]
### Description

I want to add multi language support system to the website which can help us understand in their native language.
@mdazfar2 can you assign me this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@T-Rahul-prabhu-38, the same issue I closed earlier has been raised again. Please don't do that.

**Comment by T-Rahul-prabhu-38** [comment]
sdorry , i wasnt aware of that , mb
