### ISSUE TITLE
Enhance the UI of the footer secction

### ISSUE THREAD

**Issue by T-Fathima** [mdazfar2/HelpOps-Hub#1419]
### Description

Issue Title:
Enhance the UI of the Footer Section

Description:
I would like to improve the design and visual appeal of the footer section on the website

### Screenshots

![image](https://github.com/user-attachments/assets/4276781b-0b1d-4ce2-a6a3-e5afdbd9888d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@T-Fathima I think the UI of the footer is good according to our website. Please raise any other issue that is really needed for our website. As of now, I am closing this issue. Please don't be discouraged, I really appreciate your enthusiasm in open source. Keep going! ***Thank you!***
