### ISSUE TITLE
[ENHANCEMENT] : Dark Mode

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#142]
### Describe the feature

I think i can enhance dark mode of the website that IMO is not looking good like somewhere the color combinations are not well suited according to the mode and the background color of some containers are not changed accordingly .

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/ad703d40-f570-4d7b-b6be-7145b8df216d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/b3a493ef-de89-4984-8bad-b089a7838c70)

<br>

**- @Ayushmaanagarwal1211 Everything is fine.**
