### ISSUE TITLE
[Feat] Enhanced UI Subscribe to our newsletter section

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [mdazfar2/HelpOps-Hub#1420]
### Description

In the 'Subscribe to our newsletter' section, I want to implement border animation for the placeholder and add a hover effect with stylish animation to the button to enhance the subscription appeal.

### Screenshots

![UI -fix](https://github.com/user-attachments/assets/80f2d1f6-e91d-403a-bac4-1f41702d2812)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@biswajit-sarkar-007 I think the UI of the newsletter section is good according to our website. Please raise any other issue that is really needed for our website. As of now, I am closing this issue. Please don't be discouraged, I really appreciate your enthusiasm in open source. Keep going! ***Thank you!***
