### ISSUE TITLE
Adding Terms and Conditions

### ISSUE THREAD

**Issue by AswaniBolisetti** [mdazfar2/HelpOps-Hub#1421]
@mdazfar2 
I would like to add Terms and Conditions option at the bottom, so that when we click it, Terms and Conditions will be opened
I will make it to align with the website styling
Could you please assign it to me

**Comment by mdazfar2** [comment]
@AswaniBolisetti, you are creating issues in a very incorrect way. I have mentioned this before—please raise issues using the issue template. I don’t understand why you keep raising blank issues again and again. Please don’t do that.
