### ISSUE TITLE
[Feat]Adding scroll to top

### ISSUE THREAD

**Issue by AswaniBolisetti** [mdazfar2/HelpOps-Hub#1422]
### Description

@mdazfar2 
I would like to add scroll to top feature 
Could you please assign it to me

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@AswaniBolisetti As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
