### ISSUE TITLE
[Feat] Adding Deployment link 

### ISSUE THREAD

**Issue by harshpardeshi09** [mdazfar2/HelpOps-Hub#1426]
### Description

i will add deployment link of project in project name in readme.md file

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @harshpardeshi09, this is not a good practice. You raised the issue without checking properly. How can you add the deployment link when it is already added? You must check the whole repository and website before raising an issue. I am happy to assign valid issues. Please don't be discouraged, but I am closing this issue for now.


![image](https://github.com/user-attachments/assets/761c049d-8c41-45ab-aec0-a7bfa35ac7b0)
