### ISSUE TITLE
[Feat] Navbar Redesign.

### ISSUE THREAD

**Issue by dev129** [mdazfar2/HelpOps-Hub#1427]
### Description

**Issue Title:** Navbar Design Discrepancy Affecting Landing Page Aesthetics

**Description:**
The current design of the navbar does not align well with the overall aesthetics of the landing page. While the landing page itself looks visually appealing, the navbar detracts from its design and impacts the user experience negatively. 

**Steps to Reproduce:**
1. Navigate to the landing page.
2. Change the navbar current design .
3. Note the contrast and visual misalignment with the landing page.

**Expected Outcome:**
A navbar design that complements the landing page, enhancing the overall visual appeal.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@dev129 Please share a demo video or screenshot showing how you improved our navbar.

**Comment by dev129** [comment]
This is your navbar which is good 
![image](https://github.com/user-attachments/assets/0391c7b9-c761-4cb0-9f72-b044b6b55dfd)
and this is the navbar I created :
![image](https://github.com/user-attachments/assets/ebd49d52-f814-4391-bb84-574a3de8d6d3)

Now since i haven't been assigned the label I ahven't deisgned your navbar , but I can assure you , if you assign me the proper labels , yu will get your navbar ready before 31 october, 3:00 p.m.

**Comment by mdazfar2** [comment]
Hey @dev129, sorry, I shouldn't say it like that, but it doesn't look good to me as our current navbar suits the website well, so I think there's no need to update the navbar.
