### ISSUE TITLE
[Feat] Adding testimonial Carousel in the About page.

### ISSUE THREAD

**Issue by IkkiOcean** [mdazfar2/HelpOps-Hub#1428]
### Description

We need to enhance the About page of HelpOps Hub by adding a testimonial carousel. This feature will display user testimonials in an engaging and visually appealing manner, helping to build trust and credibility with potential users.

### This is a demo, I will implement it according to the UI  and context of HelpOps Hub.

https://github.com/user-attachments/assets/a4bd7473-133c-4272-beac-b4f61ca79724

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@IkkiOcean As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
