### ISSUE TITLE
Topic :  Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [mdazfar2/HelpOps-Hub#1429]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

Wanted to do the following changes :-

1) Enhance the project structure
2) Add code of conduct section
3) Add star our repository section
4) Add need help with the basics section
5) Add first pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the thank you section

### How many and what types of DevOps tools are you adding?

docker , git

### How many years of experience do you have in the DevOps field?

Less than 1 years

### Record

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
@milansamuel609, firstly, I would like to say that the issue you raised is not using the correct issue template.

Another thing I noticed is that you raised the same issue in my other repository. Did you really copy and paste your issue description across all the repositories in GSSoC? Please don't do that.

It's not the correct way to work on open source. Please try to raise valid issues and contribute genuinely.

Avoid spamming, please.

***Thank you!***
