### ISSUE TITLE
[BUG] Cards in Team Section Not reflecting Dark Theme

### ISSUE THREAD

**Issue by sezallagwal** [mdazfar2/HelpOps-Hub#1430]
![image](https://github.com/user-attachments/assets/667684bc-ffeb-47b7-b207-8ce70b3a4d7a)

### Description
The cards on the page are not adapting to the dark theme, resulting in a mismatch between the background and card colors. This disrupts the overall visual consistency of the dark theme.

### Steps to Reproduce
1. Enable the dark theme on the application.
2. Navigate to the section where cards are displayed.
3. Observe that the cards maintain a light color scheme, not matching the dark theme background.

### Expected Behavior
The cards should adhere to the dark theme by adopting dark background colors and light text colors, blending seamlessly with the rest of the dark-themed UI.

### Possible Solutions
- Update card component styles to use the dark theme color variables for background, text, and borders.
- Ensure that all nested elements within the cards also follow dark theme colors.
- Consider using CSS variables or theme-specific classes to dynamically adjust the card colors based on the active theme.

### Additional Context
This issue affects user experience as it creates a visual inconsistency within the application.

> Please assign labels `gssoc-ext` and `hacktoberfest` to this issue.

**Comment by mdazfar2** [comment]
@sezallagwal, Great issue found. You are going to be assigned.

- Read our [Contributing guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md) and contribute accordingly.

- Don't forget to give 🌟 to our repository.

- Follow us on [LinkedIn](https://linkedin.com/company/HelpOps-Hub).


**Thank you!**
