### ISSUE TITLE
Add hover effects to Cards in benefit section

### ISSUE THREAD

**Issue by sezallagwal** [mdazfar2/HelpOps-Hub#1431]
![image](https://github.com/user-attachments/assets/3bcce9cf-5525-4a40-b274-f9ad52501af7)

I will add transition effects which will make the cards slightly grow in size when hovered over 
please assign me this issue under `gssoc-ext` `hacktoberfest` labels

**Comment by mdazfar2** [comment]
Hey @sezallagwal, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/HelpOps-Hub) a star and let me know once you've done it.
