### ISSUE TITLE
### Bug Report: Terms and Conditions Page Not Opening

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/HelpOps-Hub#1435]
### Description

When clicking on the "Terms and Conditions" page link, the page does not open as expected. This issue prevents users from accessing the terms and conditions, which may cause confusion and impact the user experience.

#### Current Behavior
Currently, clicking on the "Terms and Conditions" link does not open the page, preventing users from accessing its content.

#### Expected Behavior
The "Terms and Conditions" page should open when clicked, allowing users to view the relevant information.

### Screenshots

https://github.com/user-attachments/assets/30730c9e-5f25-48ac-9ab1-2438f4c8081d

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace you are now assigned. ✅

Make sure the terms & condition page aligns with our HelpOps-Hub concept, matching both the functionality and the UI of our website, which is very important.

**Comment by inkerton** [comment]
@mdazfar2 Can I work on this? Please assign it to me.
