### ISSUE TITLE
Bug: Privacy Policy Page Not Opening on Click

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/HelpOps-Hub#1436]
#### Issue
When clicking on the **Privacy Policy** page link, the page is not opening as expected. This prevents users from accessing the privacy policy content, impacting the user experience and transparency of the site.

#### Expected Behavior
The **Privacy Policy** page should open when clicked, allowing users to view the policy.

### Screenshots

https://github.com/user-attachments/assets/b4b71b32-f0d7-42a3-b1de-96d9d3a8b8c8

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace Thank you for raising this issue. I was actually thinking about it, and you are now assigned.

Make sure the privacy and policy page aligns with our HelpOps-Hub concept, matching both the functionality and the UI of our website, which is very important.

**Comment by inkerton** [comment]
@mdazfar2 Can I work on this It has been 5 days since previous assignment. I'll be sure to make a page matching the UI.
