### ISSUE TITLE
Adding Bottom to top Button

### ISSUE THREAD

**Issue by Molza01** [mdazfar2/HelpOps-Hub#1437]
### Description

Adding a feature which will help the user to redirect him/her to bottom to top.

So please assign me this issue under
Name : Sandesh Shinde
Label : gssoc

### Screenshots

![Screenshot 2024-10-31 163636](https://github.com/user-attachments/assets/2faa2746-515e-4e1e-8e10-11356ee0338d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Molza01 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
