### ISSUE TITLE
Encoding of api fetch call to hide api credencial

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#144]
### Describe the feature

Encoding api fetch 

### Add ScreenShots

![Screenshot 2024-05-30 180932](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/aea66011-2c49-40c7-9164-bd138eda02c2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 go ahead
