### ISSUE TITLE
[Feat]: Bottom to Top Button

### ISSUE THREAD

**Issue by Molza01** [mdazfar2/HelpOps-Hub#1440]
### Description

By adding a bottom to top button this will help the user to scroll up easily and fast.

So please assign me this issue under gssoc-ext level 1 .

### Screenshots

![Screenshot 2024-11-02 003118](https://github.com/user-attachments/assets/96ae39b7-8481-4aeb-8699-7c3c90ea898d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lade6501** [comment]
Is it still open for work ?

**Comment by mdazfar2** [comment]
Yes, @lade6501, it is open, and you can work on it. Make sure the button you add matches the website UI.


- Read our [Contributing guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md) and contribute accordingly.

- Follow us on [LinkedIn](https://linkedin.com/company/HelpOps-Hub).
