### ISSUE TITLE
[Feat] add dynamic copyright section,check description 

### ISSUE THREAD

**Issue by AE-Hertz** [mdazfar2/HelpOps-Hub#1441]
### Description

Add a copyright section year that automatically updated.

### Screenshots

![Screenshot_2024-11-03-09-54-57-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/bc90044c-b174-4d20-b194-a429ec15c592)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by AE-Hertz** [comment]
@mdazfar2 can you please assign me this issue

**Comment by mdazfar2** [comment]
Hey @AE-Hertz, can you please describe it clearly so I can understand exactly what you want to contribute? It will help me assign this issue to you easily.

**Comment by AE-Hertz** [comment]
> Hey @AE-Hertz, can you please describe it clearly so I can understand exactly what you want to contribute? It will help me assign this issue to you easily.

In this issue, I will add 
- a copyright year which is currently missing,
- ©️ (year) <- I will add this.
- but the process will be automated so no need to change year manually each year.

I will implement this.

**Comment by mdazfar2** [comment]
@AE-Hertz Issue acknowledged! You are going to be assigned.

- Read our [Contributing guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md) and contribute accordingly.

- Don't forget to give 🌟 to our repository.

- Follow us on [LinkedIn](https://linkedin.com/company/HelpOps-Hub).


***Thank you!***
