### ISSUE TITLE
[Feat] add a hero section ui improvements, check description 

### ISSUE THREAD

**Issue by AE-Hertz** [mdazfar2/HelpOps-Hub#1442]
### Description

Add a hero section background to match the current theme because right now it's looking so empty and room for improvements. 

### Screenshots

![Screenshot_2024-11-03-10-00-50-12_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/9b29f41b-310e-43fd-87d3-44b030aeaf1d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by AE-Hertz** [comment]
@mdazfar2 please assign me this issue

**Comment by AE-Hertz** [comment]
@mdazfar2 hey can you assign me

**Comment by mdazfar2** [comment]
Hey @AE-Hertz, it looks good on our side. Check out the screenshot below for proof. Please don’t be discouraged, but I need to close this issue for now. _Thank you._
