### ISSUE TITLE
[Feat] add a blog section with automation

### ISSUE THREAD

**Issue by AE-Hertz** [mdazfar2/HelpOps-Hub#1443]
### Description

I will implement a blog section which already exists but needs following improvements.
- the feature to automatically update the articles, right now it's not
- this will be supported by backend to facilitate this feature
- by the the user will be in loop with current technologies.
- the whole thing will not replace the current section but it will be under a new section 'explore/discover' that will show blogs from all over world.

Check screenshot.

I expect a level3 for this.

### Screenshots

![Screenshot_2024-11-03-10-12-14-27_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/b1f4c04d-46b9-4a25-9bf4-21e982841671)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by AE-Hertz** [comment]
@mdazfar2 can you please assign me this issue.

**Comment by AE-Hertz** [comment]
@mdazfar2 can you assign me

**Comment by mdazfar2** [comment]
That's amazing, @AE-Hertz :) You mean you’re adding automation so that only DevOps blogs will be fetched from somewhere for knowledge? If that’s possible, it would be really, really good. Am I right that this is exactly what you want to do?

**Comment by AE-Hertz** [comment]
> That's amazing, @AE-Hertz :) You mean you’re adding automation so that only DevOps blogs will be fetched from somewhere for knowledge? If that’s possible, it would be really, really good. Am I right that this is exactly what you want to do?

yes, we are same page, but i would like to point out one thing before hand, it would be DevOps articles. and i think this will improve the functionality of exploration and keep user engaging.

**Comment by mdazfar2** [comment]
> @mdazfar2 yes, we are on same page, but i would like to point out one thing before hand, it would be DevOps articles. and i think this will improve the functionality of exploration and keep user engaging.

<br>

Alright, @AE-Hertz that's really good! If you implement it successfully, it will help engage users and drive traffic to our website. Hope you understand—let's work together to take HelpOps-Hub to the next level. 🚀 You are now assigned!

**Comment by AE-Hertz** [comment]
@mdazfar2 hey i dont know i should i ask this or not, but can you share env , i dont know why its happening i tried to run with my credentials its not working as development node environment is not available in current app and implementing it would take time. thats i came to this. here is my discord id: hertz.1999 pls. dm me.

**Comment by mdazfar2** [comment]
> @mdazfar2 hey i dont know i should i ask this or not, but can you share env , i dont know why its happening i tried to run with my credentials its not working as development node environment is not available in current app and implementing it would take time. thats i came to this. here is my discord id: hertz.1999 pls. dm me.

Hey @AE-Hertz, sorry I cannot give you the credentials of the environment because it's all on the deployment site. If you test anything, it could cause problems with the site's real-time database. I hope you understand. You must set up the environment variables to run the backend locally.

**Comment by mdazfar2** [comment]
> @mdazfar2 yes, its understandable, so can you help me with setting the variable and solving initial error?

Sure, what error you are facing with

**Comment by AE-Hertz** [comment]
> > @mdazfar2 yes, its understandable, so can you help me with setting the variable and solving initial error?
> 
> Sure, what error you are facing with?

yes, i am facing issue with login, and without logging in how can i go to blog page, and google signin is giving me this response.
![Screenshot 2024-11-09 140110](https://github.com/user-attachments/assets/f89be60b-6458-408a-a641-6f5e617b89d2)

**Comment by AE-Hertz** [comment]
and noraml otp email is responding as user already exist./

**Comment by mdazfar2** [comment]
@AE-Hertz there is an issue with the Google auth token. Please try to set up from Google on how to create a Google auth token and all; it would be helpful for you.
