### ISSUE TITLE
[Feat] Add User Testimonial Carousel Section at Home Page

### ISSUE THREAD

**Issue by IkkiOcean** [mdazfar2/HelpOps-Hub#1445]
### Description

**Description**  
To enhance the HelpOps Hub homepage experience, we need to add a "User Testimonial Carousel" section. This section will display user testimonials in a visually appealing carousel format, allowing visitors to quickly see feedback from satisfied users. This addition aims to build trust and increase user engagement on the platform.

**Feature Requirements**  
1. **Carousel Component**  
   - Create a responsive carousel to showcase user testimonials.
   - Each slide should display a testimonial, including the user’s name, profile picture, and feedback text.
   
2. **Testimonials Content**  
   - Add sample testimonials for testing. Each testimonial should include:
      - User’s name
      - Profile picture
      - Short feedback (limited to 200 characters)
      - Rating

3. **Responsive Design**  
   - Ensure the carousel looks good on all screen sizes (desktop, tablet, and mobile).

4. **Animation and Transitions**  
   - Smooth transitions between testimonials.
   - Autoplay functionality with the option to pause on hover (for desktop view) or tap (for mobile view).

### Screenshots

https://github.com/user-attachments/assets/aed7833f-8aad-4907-99a7-28c73af57c44

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@IkkiOcean, you are assigned.

But make sure to add quality user testimonials that align with our HelpOps-Hub concept.

Here's a brief overview to help you understand exactly what HelpOps-Hub does:

# HelpOps-Hub: Your DevOps Companion

Welcome to **HelpOps-Hub** – the ultimate platform for DevOps practitioners and enthusiasts alike. Whether you’re facing a complex technical issue, need quick tips, or want to expand your understanding of DevOps, HelpOps-Hub is here to make DevOps simpler and more collaborative.

## What is HelpOps-Hub?

HelpOps-Hub is an open-source DevOps platform designed to connect professionals, provide insightful resources, and enable collaborative problem-solving. It serves as a centralized Q&A hub where developers, engineers, and teams can share knowledge, troubleshoot issues, and contribute to an ever-growing knowledge base of DevOps topics.

## Key Features

- **Community-Driven Q&A:** Post questions and find answers to DevOps-related queries across a variety of tools and technologies.
- **Blog and Articles:** Access in-depth articles, tutorials, and resources contributed by industry experts.
- **Topic-Specific Threads:** Engage in discussions categorized by tools, frameworks, and DevOps best practices.
- **Product Hunt and GSSoC Involvement:** HelpOps-Hub participates in global initiatives, including Product Hunt, Hacktoberfest, and the Girl Script Summer of Code, fostering a broader reach and impact in the DevOps community.

**Comment by IkkiOcean** [comment]
@mdazfar2 okay sure!
