### ISSUE TITLE
[Feat] Navbar is not Mobile Responsive 

### ISSUE THREAD

**Issue by IkkiOcean** [mdazfar2/HelpOps-Hub#1448]
### Description

As I was scrolling through the website I found that we can access the navbar toggle button (which is supposed to be only present in mobile or small screen) is visible which leads to **two navbers** present at a time on the site

I propose to make the navbar responsive for all screen size and prevent problems like this in future.

### Screenshots

https://github.com/user-attachments/assets/315b2424-7ce9-474b-a1a2-9f916bf37776

<img width="1256" alt="Screenshot 2024-11-05 at 11 20 16 PM" src="https://github.com/user-attachments/assets/7fee3444-57b9-41d4-89df-f6446333608e">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@IkkiOcean I don’t understand exactly what you’re trying to say. In the screen recording you shared above, you just open and close the navbar, which doesn’t clarify your point. Please explain it in more detail.

**Comment by IkkiOcean** [comment]
> @IkkiOcean I don’t understand exactly what you’re trying to say. In the screen recording you shared above, you just open and close the navbar, which doesn’t clarify your point. Please explain it in more detail.

there is option to open mobile navbar even in the desktop. that's two navbar in the application at the same point. there should be only one. it works for other screen sizes but not responsible for all

**Comment by mdazfar2** [comment]
> there is option to open mobile navbar even in the desktop. that's two navbar in the application at the same point. there should be only one. it works for other screen sizes but not responsible for all

Again I am not understand @IkkiOcean

**Comment by IkkiOcean** [comment]
@mdazfar2 

<img width="1280" alt="Screenshot 2024-11-08 at 2 04 47 AM" src="https://github.com/user-attachments/assets/13a96d95-2a51-4f3c-8a8b-e38ebf2e7f8e">

As you can see there are two navbars present on the screen. one vertical  and one horizontal. vertical one should be there only if the device is a mobile device or the screen size is too small for horizontal one. But both navbars are present at the same time even tho it should be only horizontal navbar

**Comment by mdazfar2** [comment]
Óhw, now I understand @IkkiOcean. Thanks for acknowledging. You are going to be assigned now.

**Comment by mdazfar2** [comment]
Óhw, now I understand @IkkiOcean. Thanks for acknowledging. You are going to be assigned now.
