### ISSUE TITLE
Add table of contents in readme

### ISSUE THREAD

**Issue by T-Fathima** [mdazfar2/HelpOps-Hub#1456]
### Description

I would like to propose to add table of contents section in the readme file for easier navigation and enhance the user experience.
@mdazfar2 I want to work on it.
Please assign it to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@T-Fathima you raise the same issue many times on this repo please don't do that
