### ISSUE TITLE
[BUG] What Our Community Says section width is too much in the mobile version

### ISSUE THREAD

**Issue by Hemraj-7** [mdazfar2/HelpOps-Hub#1457]
### Description

**_What Our Community Says_** section width is too much in the mobile version. it is not looking good.

### Screenshots

![Screenshot 2024-11-09 191852](https://github.com/user-attachments/assets/b3fd2cc0-4f24-4870-af72-f29a9bc6cd32)

### Any additional information?

I want to work on this issue.
Assign me

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Hemraj-7 go ahead

**Comment by Hemraj-7** [comment]
Sorry bro, but don't worry, I will work on this tomorrow.
