### ISSUE TITLE
THERE IS NO SEARCH ICON 

### ISSUE THREAD

**Issue by GAGGZ1** [mdazfar2/HelpOps-Hub#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

THERE IS NO SEARCH ICON in the website

![WhatsApp Image 2024-06-04 at 14 55 42_6bc3add8](https://github.com/mdazfar2/HelpOps-Hub/assets/81284966/21d3df37-cc2c-47c6-899e-f6ff005abff6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GAGGZ1** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
**Nice issue you found @GAGGZ1** 
- you are assigned ✔️

**Comment by mdazfar2** [comment]
> @mdazfar2 Please Assign it to me.

Sure @Dark-S8uL
