### ISSUE TITLE
Feat: Organizing project directory structure 

### ISSUE THREAD

**Issue by Khushalsarode** [mdazfar2/HelpOps-Hub#148]
### Describe the feature

Proper folder for types of file and updating the code for including file .

### Add ScreenShots

![Screenshot_20240604_153129_Chrome](https://github.com/mdazfar2/HelpOps-Hub/assets/105520366/dcfeb9bf-df46-4970-a5a1-f440f6b206ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Khushalsarode I'll put the tag of `let you know`. This means that you should have waited a little. I would have told you whether to work in it or not. I was a little busy with someone issues. This isn't the way of open-source.

**Comment by Khushalsarode** [comment]
Hey, I thought you dont require this changes, somebody might have been doing this! that's why!
and also you didn't assign label of 'gssoc' felt like issue is not required.
i saw most of the let you know issue are not assigned.

**Comment by Khushalsarode** [comment]
Can you assign this?
