### ISSUE TITLE
Feat: add some animations in the front cards

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#149]
### Describe the feature

add some animations in the front cards

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/09ff8bab-5f64-417c-9cf5-6ac962362747)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal which animation you are talking about could you please elaborate it?

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 
Aos.js - when elements are coming 
And some scrolling animation.

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal you are assigned ✔️ 

- send demo video while creating pull request.
