### ISSUE TITLE
Feat: Adding Footer and Adding Feedback in Footer 

### ISSUE THREAD

**Issue by Dark-S8uL** [mdazfar2/HelpOps-Hub#152]
### Describe the feature

Creating a Footer for the Website and Adding the existing feedback form to it. I can Add Social Media links to it as well.

### Add ScreenShots

![Screenshot (284)](https://github.com/mdazfar2/HelpOps-Hub/assets/167284441/21e04ee4-c95e-402a-95ff-ea178c1ec526)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
