### ISSUE TITLE
BUG: Dark mode is not working in contributiors page

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Screenshot 2024-06-04 182145](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/0309f86d-3bf2-4708-a577-72280c6c205f)
Please assign me this issue!!

![Screenshot 2024-06-04 182453](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/83138233-ac8a-4b6a-909c-0d5b7094496a)

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 You are assigned ✔️

- Try to also change the icon of dark mode.

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/2a96b293-262f-4796-b369-bdbcad59a3b7)

**Comment by pandeyji711** [comment]
ok
