### ISSUE TITLE
Feat: Contributor Section Responsiveness

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#154]
### Describe the feature

I will make the contributor section responsive for all devices 

### Add ScreenShots

![Screenshot 2024-06-04 183328](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/3d051a81-9453-4515-a8fe-93dfd6ea96a2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 You are assigned ✔️

- send demo video while creating pr.

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/364d72d2-268c-49aa-89fe-e78c7c6cc524

@mdazfar2  please check the video if it is correct then i will make pr
