### ISSUE TITLE
Feat: Add NGINX Reverse Proxy Guide to Documentation 📝

### ISSUE THREAD

**Issue by thevijayshankersharma** [mdazfar2/HelpOps-Hub#156]
### Describe the feature

The documentation currently lacks guidance on configuring NGINX as a reverse proxy server, a critical aspect for improving security and performance in various infrastructures. To address this gap, we propose adding a comprehensive NGINX Reverse Proxy Guide to the documentation.

Feature Details:

The guide will include detailed step-by-step instructions for installing NGINX and configuring it as a reverse proxy.
It will cover prerequisites, installation steps, and configuration of reverse proxy settings, including SSL termination, load balancing, and caching.
Clear explanations, accompanied by code snippets, will be provided to ensure ease of understanding and implementation by users of varying skill levels.
Hands-on tasks will be incorporated to provide users with practical experience in configuring NGINX for various use cases.
This addition aims to enhance the documentation by providing users with a valuable resource for effectively implementing NGINX as a reverse proxy server to optimize their infrastructure's security and performance.

### Add ScreenShots

No response

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@thevijayshankersharma go ahead!

- create folder `NGINX Reverse Proxy Guide`

- Remember that don't copy paste write in your own language with emoji. Last time you sent pull request, it was all copy paste and the documentation did not make any sense to learn anything.
- Create documentation from your own side with two - three times hands-on with your own desktop screenshots.

 - **Your documentation can make someone's life easier in DevOps 💙**
