### ISSUE TITLE
Feat: feedback form backend

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#170]
### Describe the feature

feedback form backend
we can use tech stacks like node, javascript, MongoDB.....

### Add ScreenShots

feedback form backend

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 i want to work upon it please assign it  to me

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal you are assigned ✔️

**Comment by mdazfar2** [comment]
Hii @RamakrushnaBiswal Are you working on this or do I have to assign this issue to someone else, let me know

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 I am working upon it
