### ISSUE TITLE
ENHANCEMNET of FAQ's Page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#171]
### Describe the feature

I will enhance the faq's page by adding attractive question and answers 

### Add ScreenShots

![Screenshot 2024-06-05 084611](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/f1fbffa0-82e3-49be-b7e6-96f8ff82ebce)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Try to explain the answers of old questions in more detail.

**Comment by Ayushmaanagarwal1211** [comment]
Yes i will make answers of old questions more attractive and also try to add some more question
