### ISSUE TITLE
Low quality Image

### ISSUE THREAD

**Issue by Apurv7777** [mdazfar2/HelpOps-Hub#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/65327303/04e4eb1e-43f2-4d70-8317-2976524cdc29)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Apurv7777 assigned ✔️

- add high quality image instead of current
