### ISSUE TITLE
Navbar Fixing

### ISSUE THREAD

**Issue by Apurv7777** [mdazfar2/HelpOps-Hub#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/65327303/557e3f64-f921-4bd5-905f-b29aed1557de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Apurv7777 It helps me more to assign you, when you share the screenshot of the result.

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
