### ISSUE TITLE
Dark Mode Issue

### ISSUE THREAD

**Issue by Apurv7777** [mdazfar2/HelpOps-Hub#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/65327303/b74ef200-4288-4b03-b2ce-2cfe2df284ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Apurv7777 Could you make it, so that when users enable dark mode on the homepage, it automatically enables on all pages?

**Comment by Apurv7777** [comment]
> @Apurv7777 Could you make it, so that when users enable dark mode on the homepage, it automatically enables on all pages?

Yes

**Comment by mdazfar2** [comment]
@Apurv7777 assigned ✔️
