### ISSUE TITLE
Feat: Add A Pre-Loader and a Custom Cursor

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#176]
### Describe the feature

A Pre-Loader and a custom curosor would make the UI of the website much better as it gives an engaging user experience and uplifts the overall feel of the website.

### Add ScreenShots

**Screenshot-**

![screencapture-127-0-0-1-5500-Official-Website-index-html-2024-06-05-09_12_30](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/b30e7bc8-8640-418c-82d6-ff77d089d3c5)

**Video-**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/9c7a2c0c-9096-4f57-a44e-d5e45cc6f53e

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 can you assign this to me,i have the feature ready,just need to be assigned,and i'll make a pr right away

**Comment by mdazfar2** [comment]
@shreyash3087 Will this custom cursor be present on all pages or only on the homepage?

**Comment by shreyash3087** [comment]
all pages

**Comment by shreyash3087** [comment]
> @shreyash3087 Will this custom cursor be present on all pages or only on the homepage?

It would be present on all pages

**Comment by mdazfar2** [comment]
@shreyash3087 create pr

- This loading effect should kept only on the home page, the mouse cursor should be present on all the pages, do you understand what i want to say?

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
