### ISSUE TITLE
BUG: FAQ's answers are not visible in mobile veiw and animation also creating issue as it collapse multiple times

### ISSUE THREAD

**Issue by agastya3636** [mdazfar2/HelpOps-Hub#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124435030/e6c2a3f8-0d87-4090-bce9-bcdc64afd160)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@agastya3636 could you please elaborate it you just sent screenshot and leave further.
