### ISSUE TITLE
Feat: Searchbar in Dark Mode feature

### ISSUE THREAD

**Issue by Parth20GitHub** [mdazfar2/HelpOps-Hub#179]
### Describe the feature

I would improve the searchbar in dark mode. Please assign me this issue

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142086512/0809954f-b71f-4760-8c98-5b4f8708aeff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Parth20GitHub which issues are related to, please mention

**Comment by Parth20GitHub** [comment]
The search Bar should be completely  white but text line is black in above screenshot

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
