### ISSUE TITLE
Feat:Fixing navbar to the top on scroll

### ISSUE THREAD

**Issue by Stiffpixels** [mdazfar2/HelpOps-Hub#181]
### Describe the feature

- If the navbar is fixed to the top when user scrolls its easier to navigate the site from any part of the page.
- Also navbar wraps to two rows on mobile.

### Add ScreenShots

navbar not fixed to the top on scroll:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/32983571/ddb5c11a-f9c3-409e-a38f-7daf5bdc7adc)

navbar wraps on mobile:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/32983571/900929f6-a04a-4333-9698-ff6806794227)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Stiffpixels as of now, we think we don't need this, will let you know in future, if there is need

- & please don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!

**Comment by mdazfar2** [comment]
@Stiffpixels @iamrudhresh 
- sure, you guys can work together. While create pull request please send demo video.
- & please don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by Stiffpixels** [comment]
> @Stiffpixels I'm confused, what you want to say, please send demo video

I was asking my partner which subissue does he want to fix. Since you assigned this issue to us both

**Comment by mdazfar2** [comment]
> > @Stiffpixels I'm confused, what you want to say, please send demo video
> 
> I was asking my partner which subissue does he want to fix. Since you assigned this issue to us both

@Stiffpixels I am not able to assign to your partner, so please tell your partner to please comment here so that I can assign it to him.

**Comment by Stiffpixels** [comment]
> > > @Stiffpixels I'm confused, what you want to say, please send demo video
> > 
> > 
> > I was asking my partner which subissue does he want to fix. Since you assigned this issue to us both
> 
> @Stiffpixels I am not able to assign to your partner, so tell your partner to please comment here so that I can assign it to him.

What I am saying is that you assigned this issue to two people right? So I was just asking the other person which part of this issue he wants to work on.
