### ISSUE TITLE
BUG:Navbar Icons dont redirect to intended Pages

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

The Navbar Icons - Discord and LinkedIn dont Redirect to the intended URL

**Expected Behaviour-**

- Discord Redirects to -https://discord.com/invite/UWTrRhqywt
- LinkedIn to - https://www.linkedin.com/company/helpops-hub/

**Actual Behaviour-**

- Discord Redirects to- Discord.com
- Linkedin - LinkedIn.com

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/1923ffa5-be2e-49b7-a965-3afd64ab1b80

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 You are assigned ✔️
