### ISSUE TITLE
BUG:redirect issue

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

user click on logo then redirect the home page is missing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@mdazfar2 ,this is screenshots:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/93832ffb-d1b6-40b4-bea3-9490a9301bfe)
here redirect not working 

please assign this issue

**Comment by mdazfar2** [comment]
@Varsani2520 you are assigned ✔️ 
- and also try to add hover effect on logo
- & please don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by Varsani2520** [comment]
ok @mdazfar2
