### ISSUE TITLE
BUG: Console Errors And Missing ScrollToTop Button

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

The HelpOps Website has a lot of console errors which i think is because of a previous merge of scrollToTop Button, also due to the errors the scroll to top button is missing from the website.

I can fix all the console errors,make the console clean,and make sure that the website features a scroll to top button which when clicked brings the user back on top.

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/ba53808f-27b5-43a3-ac48-6ac86589bb9b

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 assigned
