### ISSUE TITLE
Feat:Create an About page button in the Header

### ISSUE THREAD

**Issue by AkhilaSunesh** [mdazfar2/HelpOps-Hub#198]
### Describe the feature

Create an About page button in the Header For the Home page

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/140897461/e133e324-e42e-4229-919b-957899d059c2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@AkhilaSunesh about oage button inside FAQ please check

**Comment by AkhilaSunesh** [comment]
I know, but its better if it present in the home page too.

**Comment by mdazfar2** [comment]
@AkhilaSunesh as of now, we think we don't need this, will let you know in future, if there is need
