### ISSUE TITLE
[Feature] : Implement the proper UI

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#200]
### Describe the feature

- In this project `Ui change` doesn't proper in the project.
- I will `search` to the project in the Dark mode the `container` change to the `Light` mode.
- please assign me..
- i will ready to work on it..

### Add ScreenShots

[Screencast from 2024-06-05 21-01-35.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/2237d821-7aec-4bb7-8bc9-050ad18c3157)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sivaprasath2004 you are assigned ✔️
