### ISSUE TITLE
[Feature] : Feedback form change to proper Ui

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#201]
### Describe the feature

- In this `Feedback` form in `Dark` mode can be same `Light` mode of the white color showed.
- I will recommand for `Dark ` mode Dark theme apply 
- please assign me..

### Expected behaviour

![Screenshot from 2024-06-05 21-13-30](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/86f71c9c-ef7e-4b95-aafc-bff905b41401)

### Actual behaviour
![Screenshot from 2024-06-05 21-08-55](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/d257d3a9-6ce1-4130-acec-8d34ee0a0f3b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sivaprasath2004** [comment]
Hello @mdazfar2,please assign me..

**Comment by mdazfar2** [comment]
> Hello @mdazfar2,please assign me..
> 

@sivaprasath2004 You are making this form completely dark. which doesn't look good
