### ISSUE TITLE
BUG:Theme Issue

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in about page and faq page theme is not work ,
i think in few contributor only apply theme only index file 

that's not proffesional work
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/96ec4d4f-b6ff-45a3-98db-7c9bc018facf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@mdazfar2 ,assign this issue

**Comment by Varsani2520** [comment]
Yes i can do it ,if you assign level 3

**Comment by mdazfar2** [comment]
> Yes i can do it ,if you assign level 3 @mdazfar2

@Varsani2520 sure

**Comment by Varsani2520** [comment]
ok @mdazfar2

**Comment by mdazfar2** [comment]
hi @Varsani2520 Are you working on this or do I have to assign this issue to someone else, let me know

**Comment by Varsani2520** [comment]
already i complete this issue ,few changes are remain @mdazfar2
