### ISSUE TITLE
BUG:contact form

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in dark theme contact background and text not changed ,
in dark theme whole theme change with a contact page

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/94dac93a-a103-4d82-a492-df3497be1270)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Varsani2520 go ahead send screenshot alse while creating pr.

**Comment by Varsani2520** [comment]
ok @mdazfar2
