### ISSUE TITLE
Feat: Adding Home button

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#207]
### Describe the feature

I want to add home button in navbar so that user can directly transfer from any page to home page .

### Add ScreenShots

Use case scenario : 
1. When user first go to about page
2. then from their goes to the faq's page
3. then From FAQ's user goes to contact page
4. Then atlast when user wants to move to the home page then he have to click the browser back button 3 or 4 times that i think is not good .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 click the logo and it will redirect to the `homepage` try it once.

- find other issue.
