### ISSUE TITLE
Feat: 404 Not found

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#208]
### Describe the feature

I am thinking that user should be route to 404 page on entering unwanted path

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/1f5c2c2b-63b3-40da-8ccc-ce2c7aaf5aff

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 how you can resolve this??

**Comment by shubhammjha22** [comment]
@mdazfar2 hey i would like to work on this issue, and i think we can resolve this by either using Js and making routes defined in that so whenever a user enters a path which doesnt exist it will redirect them to the homepage instead. 

For example if user enters - https://helpops-hub.vercel.app/random
it will be redirected to -  https://helpops-hub.vercel.app/

**Comment by mdazfar2** [comment]
@shubhammjha22 as of now, we think we don't need this, will let you know in future, if there is need

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  actually i found some ways to do this on internet  using js to get the route an if the route is invalid then move to 404page.html

**Comment by mdazfar2** [comment]
> @mdazfar2 actually i found some ways to do this on internet using js to get the route an if the route is invalid then move to 404page.html

@shubhammjha22 @Ayushmaanagarwal1211 
assigned, go ahead

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by shubhammjha22** [comment]
@mdazfar2 Hey, it doesn't seem necessary to assign two people to this issue. Since  @Ayushmaanagarwal1211 was the first one to raise this issue i think he should be assigned .

**Comment by mdazfar2** [comment]
@shubhammjha22 you are good man I'm unassigning you

**Comment by Ayushmaanagarwal1211** [comment]
> @mdazfar2 Hey, it doesn't seem necessary to assign two people to this issue. Since @Ayushmaanagarwal1211 was the first one to raise this issue i think he should be assigned .

Thanks bro for your kindness
