### ISSUE TITLE
Feat: Notify User when not found anything on search 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#209]
### Describe the feature

When i search anything that is not present then the feedback form is showing that IMO is not good so i want to add any container that notifies the user that the search query is not found  .

### Add ScreenShots

![Screenshot 2024-06-05 225947](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/a76d520b-c04b-469b-92c0-cbec8d2491f6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned
