### ISSUE TITLE
BUG: Search bar is breaking in mobile view

### ISSUE THREAD

**Issue by mondalsurojit** [mdazfar2/HelpOps-Hub#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Screenshot (344)](https://github.com/mdazfar2/HelpOps-Hub/assets/114282267/bda620ad-4a31-4638-81d1-bb3a1b32f6d6)

The search bar is not looking proper in mobile view. This make the user experience for the mobile users bad, and needs attention. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@mondalsurojit Try to make responsive only search bar nothing else.

**Comment by mondalsurojit** [comment]
@mdazfar2 ok...
