### ISSUE TITLE
Feat: Linking contact form with google sheet

### ISSUE THREAD

**Issue by mondalsurojit** [mdazfar2/HelpOps-Hub#218]
### Describe the feature

I was planning to link contact form with google sheet, if such feature already doesn't exist...

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@mondalsurojit Could you please elaborate it. It will help me to assign you when you share the screenshot.

**Comment by mondalsurojit** [comment]
@mdazfar2 Sir whenever someone will fill the form, the data will be stored in the google form. For each time, one new row will be created, with each cell having data like name, email, comment and rating....

[This is a demo, how it will look](https://blog.golayer.io/uploads/images/builder/image-blocks/_w916h515/How-To-Use-Google-Sheets-As-A-Database-Database-for-Blog-Site-example.png)


Its like using a free database as a service from google...

**Comment by mdazfar2** [comment]
@mondalsurojit you are assigned ✔️

- btw, let me tell you. This is not a contact form. This is a feedback form in which you are going to work now.

- but which google sheet will you put? You will give me my google sheet, right?

**Comment by mondalsurojit** [comment]
@mdazfar2 Yes, my bad...thats a feedback form...

And first I will use my gmail to test, and if everything goes alright...I will add yours...

If I face any doubts inbetween, I will surely reach you out on discord...

**Comment by mdazfar2** [comment]
> @mdazfar2 Yes, my bad...thats a feedback form...
> 
> And first I will use my gmail to test, and if everything goes alright...I will add yours...
> 
> If I face any doubts inbetween, I will surely reach you out on discord...

@mondalsurojit sure

**Comment by mondalsurojit** [comment]
@mdazfar2 Hello, actually I have already made this feature...But due to some ongoing work pressure, I was not able to make a PR...I hope you will reopen this...
