### ISSUE TITLE
[Feature] Ansible comamnds ,playbook cheatsheet

### ISSUE THREAD

**Issue by litesh1123** [mdazfar2/HelpOps-Hub#22]
In this issue I would like to throw light on ansible  
>what exactly ansible is
>ansible use cases
>when asnible is used
>commands of ansible 
>about ansible playbokk
>explanation of ansible commands

**Comment by mdazfar2** [comment]
@litesh1123 You are assigned

- Create folder `Ansible Cheatsheet` in the root directory

**Comment by litesh1123** [comment]
@azfar-2 thank you sir
