### ISSUE TITLE
Feat: Backend Setup for form validation

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#222]
### Describe the feature

I will set up backend for form submission 

### Add ScreenShots

![Screenshot 2024-06-06 125734](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/82f2d5b5-fa67-4c6c-9e77-1d2b58af9a5d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Which tech stack you are going to setup for backend?

**Comment by Ayushmaanagarwal1211** [comment]
Node js with express and i will use Node mailer
If you want i can also try with email js for form control

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned ✔️
- Please do it carefully and do not do anything that causes major problem on the website.

**Comment by Ayushmaanagarwal1211** [comment]
Ok  first i am using email js if it works correctly if not then i will do it by setting up backend

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 It is up to you, you decide how you want to do it.

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  I've created that using i am attaching the video below  please check it then i will make pr by removing the credentials because then the messages will come on my email but if you want your email then please provide me credentials or enter by yourself .


https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/cb434c6d-60d7-466e-b37d-f568690b0f5c

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  can you please check it

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
But i added my api key so messages will come on my email

**Comment by mdazfar2** [comment]
after some time add my api key of my mail guide me on [discord](https://discord.gg/UWTrRhqywt) or [linkedin](https://www.linkedin.com/in/md-azfar-alam/) that how can i get api key from my mail.

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am making pr
