### ISSUE TITLE
BUG: In About page scroll to top button is not working and size also big

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this out, 

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/b0600fe2-ced4-4b8b-a768-6edf4e281336)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 It is working but, the size is too big go ahead

**Comment by dhruv8433** [comment]
@mdazfar2 

thank you :)
