### ISSUE TITLE
BUG: In Responsive, maintainor card overlap on contributors

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this out,
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/bfc744ec-05f4-4443-a059-164a4a5c17e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 as of now, we think we don't need this, will let you know in future, if there is need

**Comment by dhruv8433** [comment]
@mdazfar2 

sure
