### ISSUE TITLE
BUG: FAQ's Answer open two times and not have close arrow

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this ,
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/ea4a3a0b-147c-4f46-ab2c-3aa8238ce96c)

try to open faqs answer in responsive 
there is no close arrow

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 assigned

**Comment by dhruv8433** [comment]
@mdazfar2 

Thank you :)
