### ISSUE TITLE
BUG: Links Open in the Same Tab Instead of a New Tab

### ISSUE THREAD

**Issue by shubhammjha22** [mdazfar2/HelpOps-Hub#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When navigating through the website, I've noticed that links open in the same tab instead of opening in a new tab.  This  disrupts the user experience. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shubhammjha22 could you please share demo video what is the exact bug which you are talking about?

**Comment by shubhammjha22** [comment]
@mdazfar2 Sure here is the video -

https://github.com/mdazfar2/HelpOps-Hub/assets/68507333/f845f5f8-d85a-4c20-bb61-2291f81f6956

**Comment by mdazfar2** [comment]
@shubhammjha22 assigned ✔️

**Comment by shubhammjha22** [comment]
@mdazfar2 i have raised the PR , kindly review it . Also i would request you to add the apt label in the PR as well. 
Thank you
