### ISSUE TITLE
BUG: Feedback is not responsive

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this out,
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/01f57c55-922c-4fba-aa40-3c53cb62d0eb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 go ahead
- but try to make responsive only on Feedback nothing else

**Comment by dhruv8433** [comment]
@mdazfar2 

ok
