### ISSUE TITLE
setup of banner at footer of contributor page

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#233]
### Describe the feature

@mdazfar2 
your contributor page need banner in footer 

### take a look
![Screenshot 2024-06-06 015508](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/b85dc34d-dcbc-434a-87d1-d590c47bf4dc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 assigned
