### ISSUE TITLE
[BUG] : Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- In this project mobile site `400` to `500` doesn't proper responsive this is can outsited of the screen `overflow`.
- please assign me...
- I will ready to work on it... :rocket: 

[Screencast from 2024-06-06 12-08-30.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/8e8cc571-45df-459b-b96e-e2a38ce7fbd0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sivaprasath2004** [comment]
hello @mdazfar2, please assign me

**Comment by mdazfar2** [comment]
@sivaprasath2004 make full responsive of homepage
