### ISSUE TITLE
[Feature]Docker inside Docker

### ISSUE THREAD

**Issue by litesh1123** [mdazfar2/HelpOps-Hub#24]
With this issue I would like to throw light on Steps and methods to setup Docker inside Docker. 
>This would be great concept for beginners .
>As this would  help understand Docker more deeply
>this would enhance user understanding and application

**Comment by mdazfar2** [comment]
@litesh1123 You are assigned.
- Do it hands-on 2 to 3 times and then make it step-by-step so that people will understand it well.
