### ISSUE TITLE
BUG: Missing Scroll to top button

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this out
there are no scroll to top button
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/86034d3b-ea55-46cf-b94b-453eaf56876d)

we can add it in right bottom

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 assgined ✔️

**Comment by dhruv8433** [comment]
@mdazfar2 

Thank you :)
