### ISSUE TITLE
Feat: In Responsive we can add burger menu

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#243]
### Describe the feature

@mdazfar2 

we can add burger menu in responsive design and all social media icon move to footer

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/8f99e241-3bed-42fd-9908-397b33d47a85)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 could you please send me the screenshot

**Comment by dhruv8433** [comment]
@mdazfar2 

Sure
check this out

burger menu something like this
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/f52f959f-0137-47d9-9daa-1b0523d2e21d)

and footer somethiing like this
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/502b303b-dd3c-486f-a4a4-7921ba1e381a)

we can also add some important link in footer

**Comment by mdazfar2** [comment]
@dhruv8433 assigned ✔️
- checkout the deployed link now it is work fine in dark mode in every pages.

**Comment by dhruv8433** [comment]
@mdazfar2 

Thank You
