### ISSUE TITLE
Feat: We can display empty state for not foudn

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#246]
### Describe the feature

@mdazfar2 

check this out
when i try to search something and if it not found we can display not found empty state

currenlty there are nothing shown if search result not found

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/b096c52d-fd86-4eb3-977c-0d4d25bf8466)

we can add something like this

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/f19f6208-e3ea-4484-becb-49725013f400)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 assigned
