### ISSUE TITLE
BUG: Search input have extra padding

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this out,
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/4e0e42e4-0388-4844-a9a0-0c6f206049d1)

search input have extra padding form top in resopnsivve

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 try to do both on one pr feedback and search as well because the manager of gssoc eyes on my repo

**Comment by dhruv8433** [comment]
@mdazfar2 
ok
