### ISSUE TITLE
Bug: Feedback is not responsive

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#249]
@mdazfar2 

feedback form is not resposnsive 
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/4de3c23b-30a8-44b6-90ec-81026dfc91ea)

**Comment by mdazfar2** [comment]
@dhruv8433 this is not feedback this is FAQ you wrote feedback and shared FAQ screenshot?

**Comment by dhruv8433** [comment]
@mdazfar2 

oh sorry
i change screenshort

**Comment by mdazfar2** [comment]
create pr
