### ISSUE TITLE
BUG:add animated img instead of static

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

i want to add some animation in feedback img fot user interaction  :
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/b7202394-af62-4af3-adb9-ae2daca6ce25)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@mdazfar2 assign this issue

**Comment by mdazfar2** [comment]
if this have animation please share the demo video

**Comment by Varsani2520** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/c2bef5fb-9604-4483-8a4f-48267cd4501d

@mdazfar2

**Comment by mdazfar2** [comment]
@Varsani2520 It doesn't looks good to me
