### ISSUE TITLE
BUG:design bottom to top button

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

here issue is button is look like a very big ,so i want to small and also rounded type and some background 
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/b7b81fce-4f9b-4a65-aa90-4fd0f4b1bb3e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Varsani2520 assigned and also try to make it responsive

**Comment by Varsani2520** [comment]
ok @mdazfar2
