### ISSUE TITLE
BUG:trophy section

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

we can add trophy section 
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/c10dc7dc-bd2c-45c2-83a1-817ffe2fc435)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/d2fea7c2-bb06-450a-9295-c2e7d372dc69)

**Comment by Varsani2520** [comment]
because of that issue is closed, i have to create new pr

**Comment by mdazfar2** [comment]
@Varsani2520 now it is back thanks for effort :) I have an another issue for you can you please work on that?

**Comment by Varsani2520** [comment]
Yes

**Comment by Varsani2520** [comment]
tell me what to do @mdazfar2

**Comment by mdazfar2** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/8208805c-3324-4692-ae46-c377430a0d0e)

<br>

See the highlight red i want that all the contributors card will come from here do you understand what i want to say

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/91c5d19e-c2c3-4860-a5b7-5dd0b94bf44f)


also try to remove this one

**Comment by Varsani2520** [comment]
yes @mdazfar2

**Comment by mdazfar2** [comment]
@Varsani2520 please create or as soon as possible

**Comment by Varsani2520** [comment]
ok @mdazfar2

**Comment by mdazfar2** [comment]
Remove this @Varsani2520

**Comment by Varsani2520** [comment]
ok @mdazfar2

**Comment by mdazfar2** [comment]
@Varsani2520 what is the status

**Comment by Varsani2520** [comment]
Hey @mdazfar2  check the PR #257
