### ISSUE TITLE
Feat:Add Hover and Transition effect on Icons.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#256]
### Describe the feature

I will add CSS for hover and Transition effects on Icons.
That will create better look.
Create more attractive to website.
User Friendly.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/8dd79b1e-3be0-4d7b-acf4-faa0672ab9d2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy go ahead and create pr as soon as poosible

**Comment by zalabhavy** [comment]
@mdazfar2 PR done please check it !!
