### ISSUE TITLE
BUG: aligment of banner at bottom is not correct  and redesign of team button

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 
### Issue 1: Alignment of Banner at the Bottom
Problem Description:
The banner at the bottom of the webpage is not correctly aligned. This could manifest in various ways, such as the banner being off-center, not flush with the edges of the screen, or overlapping with other elements on the page.
### Issue 2: Redesign of Team Button
Problem Description:
The "Team" button needs a redesign. This might include changes in color, size, font, hover effects, and overall placement.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 go ahead
