### ISSUE TITLE
Feat: enhance the home page Ui

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#271]
### Describe the feature

we should re design the home page need i will better than 

i know you like it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
we should enhance the ui of toggle button like sun and moon instead of simple button like this :
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/5124bc3c-2dfb-4d56-ade4-74a8532d961f)
how is it ? if you like it assign this issue i will design the new home ui

**Comment by mdazfar2** [comment]
@Varsani2520 great dark and night mode you are assigned go ahead and work on this

**Comment by mdazfar2** [comment]
@Varsani2520 please remove the cover image of website and change the title

**Comment by Varsani2520** [comment]
ok @mdazfar2

**Comment by mdazfar2** [comment]
> ### Describe the feature
> we should re design the home page need i will better than
> 
> i know you like it
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/137641079/337538971-3a1f3c30-e5b5-4090-93f9-195bccc00c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjE5MjcsIm5iZiI6MTcxNzc2MTYyNywicGF0aCI6Ii8xMzc2NDEwNzkvMzM3NTM4OTcxLTNhMWYzYzMwLWU1YjUtNDA5MC05M2Y5LTE5NWJjY2MwMGM1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxMjAwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjhjOTk0ZmQ2MGVkYTM2YjlhMDYyMDk3NDJjNmJlZTJmMTE4NDNkNmNjMWM2M2M3OTIzMjMyMzI2YzIwMjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0em5ZWmo_cADfWrRTVmNoTYgbQmZ_jS1YKjG0FedDhM)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

@Varsani2520 remove this, you are leaking our idea

**Comment by Varsani2520** [comment]
ok

**Comment by Varsani2520** [comment]
Hi @mdazfar2 ,

my task is dark and light theme .
anything else?

**Comment by mdazfar2** [comment]
@Varsani2520 fine i think you shared theme of our web
