### ISSUE TITLE
Makeover of homepage

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#276]
### Describe the feature

@mdazfar2  your website need makeover of home page 

That gives vibrent look

### Add ScreenShots

![Screenshot 2024-06-07 164414](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/0398b82a-3f53-4a40-86a5-e7e6def1b291)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
> i would like to work on this issue please assign me

@dhruv8433 i'm mention you to work on logo not in website
