### ISSUE TITLE
Feat: Redesign Project Cards 

### ISSUE THREAD

**Issue by dhruv8433** [mdazfar2/HelpOps-Hub#277]
### Describe the feature

@mdazfar2 

we can redesign project cards with new ui

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/5c9258fd-afd3-42b2-9380-9ba65386d840)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhruv8433 Please don't copy and paste. After deploying the project, we will ask you to add something. Not now. You are leaking our Figma design, which is not good.
