### ISSUE TITLE
BUG: Text not visible in dark mode

### ISSUE THREAD

**Issue by Saimanjari777** [mdazfar2/HelpOps-Hub#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The text at footer is not visible
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/130165687/40f2dc00-9ce8-4d96-87f6-bb15696e6830)
Please assign this issue to me @md

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Saimanjari777 go ahead 

- & don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
