### ISSUE TITLE
Feat: Upgrading Our Mission section

### ISSUE THREAD

**Issue by Parth20GitHub** [mdazfar2/HelpOps-Hub#285]
### Describe the feature

I will upgrade Our Mission section and align the css part of it .

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142086512/8adcb66c-1081-4161-926b-d959d91cf9e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Parth20GitHub assigned

- & don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
