### ISSUE TITLE
Feat: Add github 

### ISSUE THREAD

**Issue by Meetjain1** [mdazfar2/HelpOps-Hub#287]
### Describe the feature

Add github icon also with embedded link to show this repo to the user in the home page 

### Add ScreenShots

![help](https://github.com/mdazfar2/HelpOps-Hub/assets/133582566/25c7336f-4fed-47df-8401-c40c08607544)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Meetjain1 I am watching you. You are creating issues again and again. It is not a good way to work on open source. Why don't you describe all your issues in just one?

- & don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by Meetjain1** [comment]
> @Meetjain1 I am watching you. You are creating issues again and again. It is not a good way to work on open source. Why don't you describe all your issues in just one?
> 
> * & don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
> * And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

Actually was adding right after I find any bug

**Comment by mdazfar2** [comment]
@Meetjain1, try to visit the whole website at once and then create an issue with all the bugs.
- Join our Discord; we will give issues when we find anything.

**Comment by Meetjain1** [comment]
> @Meetjain1, try to visit the whole website at once and then create an issue with all the bugs.
> 
> * Join our Discord; we will give issues when we find anything.

sure @mdazfar2 but please let me assign in rest issues , then will create additional if I find more
