### ISSUE TITLE
Feat: copyright section enhancement 

### ISSUE THREAD

**Issue by Meetjain1** [mdazfar2/HelpOps-Hub#288]
### Describe the feature

copyright year is not there currently in our website , I see many tried to work on this but not able to fix it , I will write a code in it to fetch dynamically the current year for copyright rather than copy pasting the year using html.
@mdazfar2 assign this issue to me I will fix it

### Add ScreenShots

![help2](https://github.com/mdazfar2/HelpOps-Hub/assets/133582566/d02e0083-58b4-4587-92eb-12ff765568b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Meetjain1 elaborate it more

**Comment by Meetjain1** [comment]
> @Meetjain1 elaborate it more

By writing a js code it will auto fetch the current year and will display it on website like © 2024 HelpOps-Hub
