### ISSUE TITLE
Project Proposal: Monitoring and Logging Using Grafana

### ISSUE THREAD

**Issue by Apurv7777** [mdazfar2/HelpOps-Hub#290]
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this project proposal

**Comment by mdazfar2** [comment]
@Apurv7777 I am watching you. You are creating issues again and again. It is not a good way to work on open source. Why don't you describe all your issues in just one?
