### ISSUE TITLE
Proposal of New conributors page

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#300]
### Describe the feature

@mdazfar2
### Add ScreenShots

![Screenshot 2024-06-08 155231](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/257bfe85-1f3a-49a0-afb4-dd08a38969b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 assigned!
