### ISSUE TITLE
Feat: Fetching README files to frontend.

### ISSUE THREAD

**Issue by Apurv7777** [mdazfar2/HelpOps-Hub#308]
### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/65327303/4fa40b36-6a71-4a2c-98fb-b525428e8654

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Great issue found @Apurv7777, Will this be for only one folder or for all folders?

- If someone uploads another folder in the future, will it automatically fetch? Or we will do it manually for each folder one by one?

**Comment by Apurv7777** [comment]
> Great issue found @Apurv7777, Will this be for only one folder or for all folders?
> 
> * If someone uploads another folder in the future, will it automatically fetch? Or we will do it manually for each folder one by one?
> * Don't forget to share demo video while creating pr

No, It will automatically fetch.

**Comment by Asymtode712** [comment]
@mdazfar2 I want to work on this issue, can you please reopen and assign it to me

**Comment by mdazfar2** [comment]
@Asymtode712 assigned
