### ISSUE TITLE
Feat: Adding Animation

### ISSUE THREAD

**Issue by harshmishra19** [mdazfar2/HelpOps-Hub#309]
### Describe the feature

Your landing page already looks fantastic, but incorporating animations on the image used on the landing page could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.
If you could assign me this task under GSSOC24, I would be thrilled to work on it.

### Add ScreenShots

![hel](https://github.com/mdazfar2/HelpOps-Hub/assets/115486960/bc4a5c3c-17b9-4b90-ab64-fb9337c0b917)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@harshmishra19 assigned, send demo video while creating pr
