### ISSUE TITLE
Feat: Adding error 404 page.

### ISSUE THREAD

**Issue by taneeshaa15** [mdazfar2/HelpOps-Hub#312]
### Describe the feature

I will add the error 404 page.

### Add ScreenShots

![md](https://github.com/mdazfar2/HelpOps-Hub/assets/157527085/0912e072-7ae5-4155-81e5-874016ae15a0)
Will somehow look like this (not exactly)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@mdazfar2 Please assign me this issue under gssoc'24 level 2

**Comment by mdazfar2** [comment]
@taneeshaa15 send demo video while creating pr

**Comment by taneeshaa15** [comment]
Sure
