### ISSUE TITLE
Feat:New design for resourse page 

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#313]
### Describe the feature

@mdazfar2  Here is new design for your resource page
### Add ScreenShots

![Screenshot 2024-06-09 154547](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/305ff4e2-7d45-42d6-8a43-a9be083fac0c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 assigned ✔️
