### ISSUE TITLE
BUG:Search function is not working in new website

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2
in  website2.0 search function is not working 
![Screenshot 2024-06-09 171056](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/a1529566-520f-4efe-8ef3-3afb26ec0749)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 assigned
