### ISSUE TITLE
Feat: Making Home Page Responsive 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#321]
### Describe the feature

I will make the home page responsive 

### Add ScreenShots

![Screenshot 2024-06-09 201019](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/116d9769-0625-42af-a8ac-7056b847653f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you are assigned
