### ISSUE TITLE
Feat:Applying logo hover effect using tilt.js

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#323]
### Describe the feature

Applying logo hover effect using tilt.js

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
go ahead we need it @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
solved with PR #371
