### ISSUE TITLE
Feat: I will create about us page for the website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#324]
### Describe the feature

I will create about us page for the website will completely match with the theme .

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 it's already work in progress.

**Comment by Ayushmaanagarwal1211** [comment]
Ok
