### ISSUE TITLE
BUG:Making Teams Page Responsive

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

Teams Page is not responsive.Cards overflow the screen width when its decreased.

**ScreenShot:**

![screencapture-127-0-0-1-5500-website2-0-contributor-html-2024-06-09-21_46_47](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/b8b14742-9024-421b-abce-10bf60ab9131)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 Try to make responsive with hamburger, I hope you know about Hamburg and also send demo video while creating pr.

**Comment by shreyash3087** [comment]
@mdazfar2 why is the issue closed,i havent made a pr yet

**Comment by shreyash3087** [comment]
@mdazfar2 

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/bef92f33-f5af-460d-bafa-207c23c553a1

**Comment by mdazfar2** [comment]
@shreyash3087 try to add two contributor box in one row or three

**Comment by shreyash3087** [comment]
@mdazfar2 the no. of contributor box in one row depends on the screen width - if there is space for two or three contributor boxes,it puts them in one row like this-

![Screenshot (5)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/a1cb9628-33be-4a47-8f41-7e9640f46212)

**Comment by shreyash3087** [comment]
@mdazfar2 also kindly reopen the issue,so i can atleast make a pr

**Comment by Ayushmaanagarwal1211** [comment]
Hii @shreyash3087 Thanks for contributing for teams page but as you can see i already opened an issue for responsive and on dc i did conversation with the owner of the repo i successfully created the home page responsive with teams page as well and will make a pr  for teams page as well .
Please consider it and try to find new issues hope you understand

**Comment by mdazfar2** [comment]
No problem @Ayushmaanagarwal1211 you will work on this issue. I will not assign it to anyone else! sorry @shreyash3087 I should not say like that but you can work on any other issue.

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/02625aff-c224-45c2-8f2e-ca29b65f267d

You can also check out this video i can't able to make pr for that just because of making the navbar responsive with the hamburger menu so it takes lot of time so my work left is to just open integrate the updated navbar code with the teams page

**Comment by Ayushmaanagarwal1211** [comment]
> No problem @Ayushmaanagarwal1211 you will work on this issue. I will not assign it to anyone else! sorry @shreyash3087 I should not say like that but you can work on any other issue.

Thanks

**Comment by shreyash3087** [comment]
@Ayushmaanagarwal1211 its alright,if you have made the teams-page responsive then that great,although i dont know if you are also working on adding a hamburger in every page or not,if you have not,i can take up on just that part.

**Comment by Ayushmaanagarwal1211** [comment]
> @Ayushmaanagarwal1211 its alright,if you have made the teams-page responsive then that great,although i dont know if you are also working on adding a hamburger in every page or not,if you have not,i can take up on just that part.

@shreyash3087  Thank you so much for understanding yes actually i have to make the navbar behaviour same for all tabs so i just started working on navbar first

**Comment by shreyash3087** [comment]
@Ayushmaanagarwal1211 alright,good luck
