### ISSUE TITLE
Feature: Maven Installation on Linux(Ubuntu)

### ISSUE THREAD

**Issue by patelkiran185** [mdazfar2/HelpOps-Hub#326]
### Describe the feature

Maven is a project management and build automation tool widely used in the Java world.Maven is a project management tool popular in the Java world. It automates the software build process, including compiling code and packaging it with dependencies. This ensures a consistent build across environments and reduces errors.

### Add ScreenShots

![Screenshot from 2024-06-09 21-55-03](https://github.com/mdazfar2/HelpOps-Hub/assets/138752385/272acfbc-551d-4b8b-9131-16c45bd11ad5)
Example of terminal. This is older version

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @patelkiran185 

- & don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And also ⭐our repo

**Comment by patelkiran185** [comment]
may i know why was this closed?

**Comment by mdazfar2** [comment]
Hey @patelkiran185, sorry, I realized that you raised an issue for getting points. I visited your GitHub profile and did not find anything related to DevOps, so how can you contribute to our project?

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Comment by patelkiran185** [comment]
@mdazfar2 Though I didn't do any projects for DevOps but i can learn and make use of GSSOC'24 as an opportunity to learn and contribute. I didn't raise issue for mere points but to learn and have some experience.

**Comment by mdazfar2** [comment]
@patelkiran185 this is awesome! If you really want to learn and share your experience, I have another issue, please let me know if you want to work on it, I will share it with you

**Comment by patelkiran185** [comment]
Yes okay. Share the issue.

**Comment by mdazfar2** [comment]
@patelkiran185 Here is the video I want on my landing page. Please ensure it matches the background color.

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/2cd29a35-b1a9-46e7-b2b0-501e8bbf65f9

<br>

- This is what I want on my landing page. You can see the preview of the website [here](https://www.xceedesigns.com/).
- You will get the whole source code [here](https://github.com/XceeDesigns/Website).
- I hope you understand what I want exactly.
