### ISSUE TITLE
Feat:Desing Stylish Scrollbar.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#329]
### Describe the feature

I will create stylish scrollbar in this website.
Stylish scrollbar give more attractive looks.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/d78c0c1c-aaf7-47a6-9628-1bde2d44075d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 We need this or not ?

**Comment by mdazfar2** [comment]
@zalabhavy as of now, we are not thinking about this. If this feature is needed in the future, we will let you know.

**Comment by zalabhavy** [comment]
@mdazfar2 any need of work hover effects on navbar or anything ?

**Comment by mdazfar2** [comment]
@zalabhavy, try to add a hover effect that matches the profile background color. If someone has a green background, add a green hover effect. Hope you understand.

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/1b3bf80c-f64a-4623-a30e-b33d49f80abc)

<br>
<br>

- **Look at the video**

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/7fb1106d-ec8c-41da-b261-5b32a35b9d01

**Comment by zalabhavy** [comment]
@mdazfar2 I understand i will do it.
please assign #333

**Comment by mdazfar2** [comment]
hi @zalabhavy 

- & don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And also ⭐our repo
