### ISSUE TITLE
Feat :Design Contact page

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#330]
### Describe the feature

I will design contact page with use of html , css and js.
also show message when submit button hits.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/95dc0228-9714-487f-8421-ca85713f2438)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy Thanks for your issue, but the contact page is already in progress.

**Comment by zalabhavy** [comment]
@mdazfar2 ok no problem close this issue !!
