### ISSUE TITLE
Project Proposal: Kubernetes On-hand project

### ISSUE THREAD

**Issue by Raghucharan16** [mdazfar2/HelpOps-Hub#336]
### Overview

As you have Kubernetes Installation, it will be good if we add basic usage of it with any example [something like minicube]. I just want add a small project in which a docker image will be deployed in k8's cluster. 

### Key Features

> Basic Understanding of Kubernetes
> Writing basic deployment files
> Hands On Deployment of a small docker image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this project proposal

**Comment by mdazfar2** [comment]
@Raghucharan16 Great issue raised, we need it.

- Create folder `k8s Hands-on Project`
- Add each and everything after hands-on 
- and add also with screenshot with highlight color of red box
- please don't copy and paste from anywhere
- Create in your own language
- try to write it with some emojis to enhance the user interface.

  - **The documentation you have created will help many people 🚀**

**Comment by Raghucharan16** [comment]
@mdazfar2 are you now merging it into main? If yes please add the level label. Thanks.

**Comment by mdazfar2** [comment]
sorry @Raghucharan16 I can't merge please try to work another issue or documentation)
