### ISSUE TITLE
Feat: New Contact Us Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#338]
### Describe the feature

**Description:**

The Current Contact US Button Doesnt Work.I  can make a new Contact us page with the current theme.

### Add ScreenShots

![Screenshot (7)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/98c33211-ef1a-4cb1-9048-fd11a6723f31)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 can i work on this??

**Comment by mdazfar2** [comment]
@shreyash3087 work in progress

**Comment by shreyash3087** [comment]
@mdazfar2 would implement something like this but just with the current theme-

![screencapture-127-0-0-1-5501-Html-Files-Contacts-html-2024-06-10-01_10_08](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/efcbbf54-fc2e-46f5-ba46-23a082cddc61)

**Comment by shreyash3087** [comment]
@mdazfar2 alright
