### ISSUE TITLE
Feat:Add Scroll to Top Button

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#340]
### Describe the feature

**Description:**

Add a scroll to top button on the website,that takes the user to the top of the page when clicked.

### Add ScreenShots

![Scroll (2)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/aa702e37-e765-46ab-9a1d-d362c6e9d475)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 this?

**Comment by mdazfar2** [comment]
@shreyash3087 as of now we are not think to add this, if there is need in future then we will let you know about it.

**Comment by mdazfar2** [comment]
@shreyash3087 will share you the figma design of `about us` could you work on it?

**Comment by shreyash3087** [comment]
> @shreyash3087 will share you the figma design of `about us` could you work on it?

@mdazfar2 sure

**Comment by mdazfar2** [comment]
@shreyash3087 here is the Figma design. As soon as possible, try to create it exactly as it is in [Figma](https://www.figma.com/design/eqORN85KL4gsh5qxqNMVFx/Helpops-hub?node-id=0-1&t=lkbkJLifOB62TCUN-0).
