### ISSUE TITLE
Feat:Add About Us Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#343]
### Describe the feature

**Description:**

There's no About Us Page on the Helpops 2.0 website.I'll create one as instructed in the design.

### Add ScreenShots

![Screenshot (8)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/d9b71312-b154-40f4-98f0-ceb163be4754)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 where can i get that youtube video,shown in the figma design?

**Comment by mdazfar2** [comment]
@shreyash3087 assigned.

- you will get the youtube video [here](https://www.youtube.com/watch?v=MCCc5mT5Pio).
- Add the current logo in place of the previous one. Apply the logo that matches the favicon on our website.
- Enter the exact answer as per your understanding. If you don't understand, then read the [README.md](https://github.com/mdazfar2/HelpOps-Hub/blob/main/README.md) file of the repository or use ChatGPT, but remember to make sure it makes sense according to your text.
