### ISSUE TITLE
Feat:proposal New of contact us page

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#347]
### Describe the feature

@mdazfar2 New website need new contact us page 
kindly take a look
and assign me for this feature

### Add ScreenShots

![Screenshot 2024-06-10 191455](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/0edf2da7-9d02-4d0d-bd8a-b0ea1eb8a726)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 assigned
