### ISSUE TITLE
BUG:toggle button design 

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

we can implement toggle button light and dark 
in light mode display sun and in dark mode button display moon

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Varsani2520 I am watching you. You are creating issues again and again. It is not a good way to work on open source. Why don't you describe all your issues in just one?

**Comment by Varsani2520** [comment]
Ok next time i do that

**Comment by Varsani2520** [comment]
@mdazfar2 you are assigns many issues to `pandeyji....`add everytime `level 3`
if it is valid than why this not...

if you doing this everytime than i will complain this in gssoc flag

**Comment by Varsani2520** [comment]
also invalid ,let you know,no need  ...that kind  of  tags are not valid in  GSSOC

**Comment by mdazfar2** [comment]
@Varsani2520, I have an issue. If you work on it, I'll give you a level 3 label. Don't forget that I always give you a level 3 label. How can you forget about it? I consider you part of my team.

**Comment by Varsani2520** [comment]
@mdazfar2 ,assign this issue

**Comment by Varsani2520** [comment]
also add the label

**Comment by mdazfar2** [comment]
@Varsani2520, sounds good. Work on Dark mode and Light mode. When the user clicks on Dark mode, it must be applied on every page. Hope you understand. Go ahead, and I will assign this to you. Please do it well. after complete of it please create pr as soon as possible then i have other work on that

**Comment by Varsani2520** [comment]
i will do it first assign this issue to me

**Comment by mdazfar2** [comment]
@Varsani2520 Sure, If I don't assigned it to you, then whom will I assign it to 

- you are assigned ✅

**Comment by Varsani2520** [comment]
Thank you for giving this oppertunity

**Comment by mdazfar2** [comment]
@Varsani2520
 -  Don't forget to ⭐ our repo
