### ISSUE TITLE
Feat: Add feedback section

### ISSUE THREAD

**Issue by Saimanjari777** [mdazfar2/HelpOps-Hub#354]
### Describe the feature

I would like to add the feedback section so that the users can rate the performance of the website.

### Add ScreenShots

I will add  the form which will be consistent with the theme of the website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Saimanjari777 as of you now we are not thinking about it, let you know if there is need in future
