### ISSUE TITLE
Feat: Add Copyrights Section at footer

### ISSUE THREAD

**Issue by MuraliDharan7** [mdazfar2/HelpOps-Hub#358]
### Describe the feature

I want to add copyrights section at the bottom of the page in Resource page. There is no copyrights section in resource page.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/130668745/810aff03-5a5b-40be-8674-68d3618ef860)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@MuraliDharan7 Thanks for your issues but it is already in our web try to work on different issues.
