### ISSUE TITLE
Feat: Add ScrollToTop button

### ISSUE THREAD

**Issue by MuraliDharan7** [mdazfar2/HelpOps-Hub#359]
### Describe the feature

I want to add scroll to top button in resource page

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/130668745/9fadb76f-18c3-424e-9e75-66ae08d88136)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@MuraliDharan7 assigned
