### ISSUE TITLE
Add proper issue templates

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#36]
Issue templates are very helpful for a collaboration repo. When users identify a bug or want to add a new feature, you can provide templates so you can collect all the pertinent information you need to fix a bug or add a new feature.

**Some suggested prompts/questions you can add to a “Report Bug” template are:**

- Briefly describe the bug
- What is the expected behavior?

**Some suggested prompts/questions you can add to a “Feature Request” issue template are:**

- Briefly describe your feature request
- What problem is this feature trying to solve?

**Some suggested prompts/questions you can add to a “Documentation” issue template are:**

- Briefly describe the documentation update
- What's wrong with the existing documentation

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 Also add `Project` issue template. 
- You are assigned
