### ISSUE TITLE
Feat: Add Google translate feature

### ISSUE THREAD

**Issue by MuraliDharan7** [mdazfar2/HelpOps-Hub#361]
### Describe the feature

I want to add google translate feature in resource page.

### Add ScreenShots

![GoogleTranslate](https://github.com/mdazfar2/HelpOps-Hub/assets/130668745/a16778e3-6612-4e00-a38c-40c73aa0cd21)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@MuraliDharan7 I am watching you. You are creating issues again and again. It is not a good way to work on open source. Why don't you describe all your issues in just one?
