### ISSUE TITLE
Contact us page responsive 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#373]
### Describe the feature

I will make the contact us page responsive

### Add ScreenShots

![Screenshot 2024-06-12 113116](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/7134d88e-6e73-4915-939e-69e672a1f1bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned
