### ISSUE TITLE
BUG: Footer is not present in resources webpage

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

At homepage and in all other pages , footer is visible but when we click on get started(resources) , footer is not visible.

![footer-home](https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/52eee174-2545-4e58-930e-13840e36d096)
![footer-resource](https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/63cea8c2-a514-4c9b-ac01-d3cb63b0aa1a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 I have fixed this issue and created a pull request for the same . Please assign this issue to me and merge my pull request under gssoc level .

**Comment by mdazfar2** [comment]
@Maana-Ajmera assigned ✅

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And also ⭐ our repo
