### ISSUE TITLE
Feat: Running a Server Container and Creating Docker Images

### ISSUE THREAD

**Issue by revanth1718** [mdazfar2/HelpOps-Hub#38]
### Describe the feature

I would like to contribute to the repository by adding comprehensive content on the following topics related to Docker:

1.Running a Server Container

->Introduction to Docker containers and their benefits.
->Step-by-step guide to running a server container using Docker.
->Example: Running a basic web server container.
->Explanation of essential Docker commands for managing server containers.
->Tips for optimizing and maintaining server containers.
->Creating Docker Images

3.Introduction to Docker images and their role in containerization.
->Detailed guide on creating custom Docker images.
->Example: Building a Docker image for a simple application.
->Instructions on writing an effective Dockerfile.
->Best practices for creating and managing Docker images.
->How to push and pull Docker images from Docker Hub or other registries.

I am Participating in GSSOC'24.

### Add ScreenShots

![Screenshot (555)](https://github.com/mdazfar2/HelpOps-Hub/assets/109272714/74eca9d0-eb63-4dcb-af62-3df91bafe437)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Impressive, go ahead @revanth1718 
- create a folder `Docker Knowledge` and write each and everyone

**Comment by revanth1718** [comment]
thank you
