### ISSUE TITLE
Feat:Add Hover effects on social icons 

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#381]
### Describe the feature

I want to add Hover effects on social icons.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/3f48821b-e510-4bf8-9463-0d198b8d1780)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Please assign me this task.

**Comment by mdazfar2** [comment]
@zalabhavy The hover effect in the footer will not look good. I have an issue. If you want to work on it, let me know.

**Comment by zalabhavy** [comment]
@mdazfar2 Yes please tell me i will work on that issue.

**Comment by mdazfar2** [comment]
@zalabhavy Here is the video I want on my landing page. Please ensure it matches the background color.

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/2cd29a35-b1a9-46e7-b2b0-501e8bbf65f9

<br>

- This is what I want on my landing page. You can see the preview of the website [here](https://www.xceedesigns.com/).
- You will get the whole source code [here](https://github.com/XceeDesigns/Website).
- I hope you understand what I want exactly.

**Comment by zalabhavy** [comment]
@mdazfar2, I believe I am not yet able to handle this big task. I have recently progressed from a beginner to an intermediate level, and I think it would be best to assign this task to someone with more experience.

**Comment by Asymtode712** [comment]
@mdazfar2 I would like to work on making the above desired updation to landing page, please assign me and rename the issue

**Comment by Asymtode712** [comment]
@mdazfar2 I would like to work on making the above desired updation to landing page, please assign me and rename the issue

**Comment by mdazfar2** [comment]
@Asymtode712 it is already updated please check we are working on another [issue](https://discord.com/channels/1247249565682237683/1247255340756504716/1250922662666965032) please let me if you want to work on it

**Comment by mdazfar2** [comment]
@zalabhavy can you add effect on footer social icons as it is-

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/d559e871-828f-4560-85df-15fa71ea2c4d

**Comment by Asymtode712** [comment]
@mdazfar2 Sure would like to work on that mentioned feature

**Comment by mdazfar2** [comment]
@Asymtode712 Sounds good. We will work on the Figma of it and share it with you soon after completion.

**Comment by mdazfar2** [comment]
@Asymtode712 Can you add effect on the footer social icons as it is? If yes, create pr as soon as possible.

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/d559e871-828f-4560-85df-15fa71ea2c4d

**Comment by Asymtode712** [comment]
@mdazfar2 Sure, working on it

**Comment by Asymtode712** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/8f4aea2c-c1d9-4c1a-a085-6dc7010fd67c

@mdazfar2 Take a look at it and suggest me any changes if needed

**Comment by mdazfar2** [comment]
> HelpOps-Hub.-.Personal.-.Microsoft.Edge.2024-06-15.22-38-39.mp4 
> @mdazfar2 Take a look at it and suggest me any changes if needed

<br>

@Asymtode712 shown me on `light mode` as well

**Comment by Asymtode712** [comment]
Uploading HelpOps-Hub - Personal - Microsoft​ Edge 2024-06-15 23-02-02.mp4…

@mdazfar2 Is this okay??

**Comment by mdazfar2** [comment]
Great @Asymtode712 create pr

**Comment by Asymtode712** [comment]
Sure, raising a PR, in the meantime please assign me this issue

Thank you!
