### ISSUE TITLE
BUG:When Submit contact details message not shown

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/758ada0e-a139-46dc-a485-a6092ee7d946)

I will make it more attractive show message when user submit details.
Message will be seen under submit button.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy go ahead and send demo video while creating pr.

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo
