### ISSUE TITLE
BUG: join us button is not working

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/4c276828-13d6-4135-aae9-d2d9f6724eb4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal You just send screenshots, what type of changes tou want to do please describe that's why i can assign you.

**Comment by mdazfar2** [comment]
Hey @RamakrushnaBiswal Here is the video I want on my landing page. Please ensure it matches the background color.

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/2cd29a35-b1a9-46e7-b2b0-501e8bbf65f9

<br>

- This is what I want on my landing page. You can see the preview of the website [here](https://www.xceedesigns.com/).
- You will get the whole source code [here](https://github.com/XceeDesigns/Website).
- I hope you understand what I want exactly.

**Comment by RamakrushnaBiswal** [comment]
solved with PR #391
