### ISSUE TITLE
Feat:Add sticky Navbar 

### ISSUE THREAD

**Issue by parikhitritgithub** [mdazfar2/HelpOps-Hub#385]
### Describe the feature

adding sticky navbar in all pages for better navigation 

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124444610/73cbe02a-97a6-455f-a165-44f470118d1e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@parikhitritgithub Go ahead, but send a demo video while creating the PR. Add a navbar with a color similar to the background.

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo
