### ISSUE TITLE
Feat: Adding particle.js in landing page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#389]
### Describe the feature

Adding particle.js in landing page

### Add ScreenShots

https://vincentgarreau.com/particles.js/
chek this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal go ahead 🚀

**Comment by RamakrushnaBiswal** [comment]
solved with PR #401
