### ISSUE TITLE
Project Proposal: Automatic Deployments - Create a CI/CD Pipeline using AWS

### ISSUE THREAD

**Issue by revanth1718** [mdazfar2/HelpOps-Hub#39]
### Overview

To create a complete CI/CD pipeline using CodeBuild, CodeDeploy, and CodePipeline.

### Key Features

Create an S3 Bucket
Create a Stack
Create a Build Project
Create a Deployment Role
Create a CodeDeploy Application
Create a Deployment Group
Create a CI/CD Pipeline
Test the Pipeline
Clean Up

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this project proposal

**Comment by mdazfar2** [comment]
You are assigned @revanth1718

**Comment by mdazfar2** [comment]
@revanth1718  What is the status? Let me know whether you are working on it or if I have to close this issue.

**Comment by revanth1718** [comment]
no i am working i will submit by today night
