### ISSUE TITLE
Making team page look responsive in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#393]
### Describe the feature

I would like to make teams page responsive in mobile view

### Add ScreenShots

![Screenshot_20240613_211113](https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/68cf238d-4a32-4d13-b3c6-1f27893d4a84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhairyagothi assigned
