### ISSUE TITLE
Fixing height and width of boxes in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#394]
### Describe the feature

Fixing height and width of boxes in mobile view

### Add ScreenShots

![Screenshot_20240613_211545](https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/e2657a33-8ea0-41dd-9d0a-551a85431d15)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhairyagothi assigned
