### ISSUE TITLE
Feat: Add a website friendly loader while loading the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#404]
### Describe the feature

Add a website friendly loader while loading the website

### Add ScreenShots

https://uiverse.io/Nawsome/young-goat-78
this one

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal Nice issue found! go ahead

**Comment by RamakrushnaBiswal** [comment]
solved  with #405 PR
