### ISSUE TITLE
Feat: Adding hover to social icons on all webpages

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#409]
### Describe the feature

It looks more good if social icons are given hover and transition effects . It will make it more user-friendly.

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/f58540aa-e6e1-425e-b268-c8044b0d1146

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 I want to work on this issue ,kindly assign it to me .

**Comment by mdazfar2** [comment]
Hi @Maana-Ajmera, We can skip the hover effect on the footer for now.
