### ISSUE TITLE
BUG:Two Navbar On All Pages

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

Dropdown Navbar doesnt disappear if its opened in mobile devices and the size of window is increased while it being opened.

**Steps to Reproduce:**

- Go to Helpops Website:https://www.helpopshub.com/
- Reduce the Screen Width
- Open The Hamburger Menu
- Without Closing the Menu Increase the Screen Width.
- Notice the Navbar Doesnt Disappear

**Video**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/f97b0a23-e336-4720-8ed7-08a3d93115d6

**Additional Context:**

I am happy to contribute by fixing this bug myself. Please let me know if you have any feedback or additional requirements.

[X] I am a GSSOC'24 Contributor

Thank you for considering my request!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 Kindly assign me this issue

**Comment by mdazfar2** [comment]
@shreyash3087 send demo video while creating pr
