### ISSUE TITLE
DOC: Add point in KEYCONCEPT section 

### ISSUE THREAD

**Issue by poushmitaPaul** [mdazfar2/HelpOps-Hub#42]
### What's wrong with the existing documentation

I want to add `security and compliance` in the `learn.md`.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/161232111/7c5559f2-c4c9-47c9-befe-5a4a21e191ba)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@poushmitaPaul Nice issue, you are assigned.
