### ISSUE TITLE
Feat: ENHANCEMENT Of Navbar 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#420]
### Describe the feature

I will enhance the navbar 

### Add ScreenShots

I will create the hovering effect on buttons 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
hi @mdazfar2 i want to work upon it

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal assigned
