### ISSUE TITLE
Feat:Make sponsor and get start button more attractive.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#421]
### Describe the feature

Add hover effect on buttons and make it attractive.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy could you please share the screenshot how's is it looks like

**Comment by zalabhavy** [comment]
@mdazfar2 Please check out this !!
https://www.loom.com/share/680ca9024d0f4ad691c3b2c089d260b8

**Comment by mdazfar2** [comment]
@zalabhavy it's not matching with the background color

**Comment by zalabhavy** [comment]
@mdazfar2  I think if I keep Hover effect like background theme everything looks like yellow and orange so no need to give effects keep it as it is.
I will open another issue tomorrow after finding that i can able to solve.
