### ISSUE TITLE
BUG: Add some animation effect on  sponser button

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/aae82cf8-649b-41df-9b13-5aa26714ae1f)

we can add some animation effect on sponser button

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Varsani2520 There is no level required for this type of issue according to `GSSOC rule`, but I will give you level 1 just for you.

- Applying a nice effect as per your requirement that suits the website.

**Comment by Varsani2520** [comment]
@mdazfar2 

as you say, "i will give you level 3 on new issue"
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/5a3b7fe5-9ca9-4554-bb24-ff7063405f8e)

than why you give `level1` and you don't even merge theme pr
also you give others `level3 `for just 2 lines changes

if you are doing kind of this than i will complain in Gssoc Flag

**Comment by mdazfar2** [comment]
@Varsani2520 There should be an issue worthy of being given a Level 3 label. The Level 3 should be worth giving.

- Go and complain
