### ISSUE TITLE
Add Icons to Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [mdazfar2/HelpOps-Hub#426]
### Describe the feature

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to Navbar items it will make the website to look Attractive and increases user Experience

Can you please assign me this issue under gssoc'24 @mdazfar2 

### Add ScreenShots

![nnn](https://github.com/mdazfar2/HelpOps-Hub/assets/161804629/f889e3ae-c092-4a62-b7cb-3c984aca0d7e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sailaja-adapa Could you please share the screenshot? It will help me assign this issue to you.

**Comment by sailaja-adapa** [comment]
i didn't done yet @mdazfar2 i will keep a Screenshot once i am done is it okay?

**Comment by mdazfar2** [comment]
@sailaja-adapa If you have any examples, please share!

**Comment by sailaja-adapa** [comment]
okk @mdazfar2

**Comment by sailaja-adapa** [comment]
i would like to add icons in this way @mdazfar2 

![iii](https://github.com/mdazfar2/HelpOps-Hub/assets/161804629/a50c470f-ea82-4c3b-a30d-49be594b4c74)
