### ISSUE TITLE
Feat: implementation of new theam at contributor page

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#429]
### Describe the feature

@mdazfar2
### Add ScreenShots

![Screenshot 2024-06-14 232933](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/7c5c7bbb-f345-4aa0-867f-5055d58a4abf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 go ahead
