### ISSUE TITLE
Feat: Floating Animation to the Image 

### ISSUE THREAD

**Issue by Damini2004** [mdazfar2/HelpOps-Hub#433]
### Describe the feature

Look more realistic in real life to grab more user attention.

### Add ScreenShots

https://private-user-images.githubusercontent.com/125206920/329776879-06cb321a-ce5c-4074-af9a-f29907d9caa1.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTY3NDUsIm5iZiI6MTcxODM5NjQ0NSwicGF0aCI6Ii8xMjUyMDY5MjAvMzI5Nzc2ODc5LTA2Y2IzMjFhLWNlNWMtNDA3NC1hZjlhLWYyOTkwN2Q5Y2FhMS5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQyMDIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmVkNTU1ODM2MmE3OWY5NzRkYzFjYWJjZTVkYmYyODFiODY5NGUwNDIxNGI4ZDJiYjgyOTQ0MDYxMzI4ZjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.17B5_j-4aiGqGxeSc0A9BdKBUCsLxxiv5eO9oe2tRLY

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Damini2004, please send a screen recording of any relevant website and elaborate on what exactly you want to add.
