### ISSUE TITLE
Feat: BackTOTOp button is not present in about and team secction

### ISSUE THREAD

**Issue by Damini2004** [mdazfar2/HelpOps-Hub#434]
### Describe the feature

It will help user to grab more number of user engagement.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/119414762/47b3fe65-443b-422c-8ef9-9f57e328fcb0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @Damini2004 
- If you want to work on this [issue](https://discord.com/channels/1247249565682237683/1247255340756504716/1250922662666965032), let me know and share some idea on [discord](https://discord.gg/UWTrRhqywt).

**Comment by mdazfar2** [comment]
@Damini2004 assigned add this icon to the `resource`page
