### ISSUE TITLE
Your Cool Repo Need Cool Website!!

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#44]
### Describe the feature

@mdazfar2 Hi! Your repo could benefit from a dynamic and cool website. I'd like to take on this issue as I have past experience with similar projects.
Please assign me under Gssoc24 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pandeyji711** [comment]
@mdazfar2 please assign this to me

**Comment by mdazfar2** [comment]
@pandeyji711  Thanks for raising this issue. Recently, I have been looking to develop a website for HelpOps-Hub. Go ahead and develop a static web for it.

**Comment by pandeyji711** [comment]
@mdazfar2  can you please connect me on linkedin so we can communicate ferther  https://www.linkedin.com/in/anuragpandey0711/

**Comment by pandeyji711** [comment]
@mdazfar2  thanks for assgning

**Comment by mdazfar2** [comment]
> @mdazfar2 can you please connect me on linkedin so we can communicate ferther https://www.linkedin.com/in/anuragpandey0711/

sure
