### ISSUE TITLE
Feat:Add a cool stylish button in darkmode toggle button 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#445]
### Describe the feature

Now the button is not styled

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal which type of button you are talking about?

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/6264a10a-9481-4bbd-8304-b5aab355c4e7)

**Comment by mdazfar2** [comment]
> ![image](https://private-user-images.githubusercontent.com/125277258/340067218-6264a10a-9481-4bbd-8304-b5aab355c4e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTcwMTgsIm5iZiI6MTcxODUxNjcxOCwicGF0aCI6Ii8xMjUyNzcyNTgvMzQwMDY3MjE4LTYyNjRhMTBhLTk0ODEtNGJiZC04MzA0LWI1YWFiMzU1YzRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwNTQ1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTBiMTc0OGU4M2E2NmJiYzI1YmMxMzM0MGMyYzI2ZDM0MWQyMDdjNWEyNTRhODU2NDQzZTEzZTg2MTAwZTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wgh0F1Tr991NCPOxYn3CImsj_bAD_ojX2m38Evd8AZU)

<br>

@RamakrushnaBiswal No, this icon looks a bit weird

**Comment by RamakrushnaBiswal** [comment]
solved #472
