### ISSUE TITLE
Feat: Add hovering effect for top contributors profile circles

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#446]
### Describe the feature

Wanted to add hovering effect for the below profile circles

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/cd54f0ca-c692-4d82-a1b9-e57f811c01cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by Asymtode712** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/ba2b03dc-2fff-498f-aade-be97c8ac8e88

@mdazfar2 Is this looking okay?? I have also updated the text for top contributors in dark mode

**Comment by mdazfar2** [comment]
@Asymtode712 great create pr

**Comment by Asymtode712** [comment]
@mdazfar2 Sure!!
