### ISSUE TITLE
Remove extra spaces from special cards

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#447]
### Describe the feature

I will remove the extra spaces from special cards

### Add ScreenShots

![Screenshot 2024-06-16 114244](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/e3ae625f-abdd-4731-ad93-68d9678116a8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by alpharsh** [comment]
I also want to work on this issue as a gssoc  contributor
