### ISSUE TITLE
Fixing the name color and style of Top 3 contributors on Dark Mode

### ISSUE THREAD

**Issue by alpharsh** [mdazfar2/HelpOps-Hub#449]
### Describe the feature

In the dark mode the name of the top 3 contributors are not clearly visible and also will improve the style

### Add ScreenShots

In the dark mode the name of the top 3 contributors are not clearly visible 
![Screenshot 2024-06-16 115048](https://github.com/mdazfar2/HelpOps-Hub/assets/108024082/23a6847d-b9e0-4f72-bf7b-7ea220658ebc)

I want to work on this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
#446 

Already done!!
