### ISSUE TITLE
Changing the color of the resources cards 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I will make the text color of the resources card white for dark mode and black for light mode

![Screenshot 2024-06-16 141009](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/bfffad9f-62d0-4b25-a428-ed0081e11628)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned 

- The color of the text should be `black` in light mode, but the text color should be white in dark mode.
