### ISSUE TITLE
Typography not looking professional of AboutUs page

### ISSUE THREAD

**Issue by alpharsh** [mdazfar2/HelpOps-Hub#456]
### Describe the feature

the typography of the about us page is not looking professinal it's UI can be made more visually appealing, i want to work on it.

### Add ScreenShots

![Screenshot 2024-06-16 153215](https://github.com/mdazfar2/HelpOps-Hub/assets/108024082/6c1c7f1d-70eb-443d-bae8-6e7cd01c29d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@alpharsh you are assigned
