### ISSUE TITLE
Header Enhancement

### ISSUE THREAD

**Issue by alpharsh** [mdazfar2/HelpOps-Hub#457]
### Describe the feature

To remove the underline of a link on Hover of Header and enhance the Header UI

### Add ScreenShots

![Screenshot 2024-06-16 154513](https://github.com/mdazfar2/HelpOps-Hub/assets/108024082/ecef2a16-a0b3-40bb-853a-560398f38e39)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@alpharsh Remove the black underline only
