### ISSUE TITLE
Feat: Fix the API fetching issue in Team page

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#458]
### Describe the feature

The contributors profiles on the Team page are not being fetched properly where some of the contributors are missing and the existing contributors are not being browsed in a proper way

### Add ScreenShots

![API](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/785ecccd-cc51-4f5a-a9f5-c5b37ef48081)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 assigned
