### ISSUE TITLE
Feat: Would like to add a few more information to the Linux section

### ISSUE THREAD

**Issue by Broken-Kaddu** [mdazfar2/HelpOps-Hub#464]
### Describe the feature

I have quite a lot of experience with Linux and its applications, i could enhance the Linux section with a lot of resources, such as including better cheat-sheets. Also giving a basic idea and implementation and the different distros where to look for how Linux works and all the information that would be required for a budding devops enthusiast looking into Linux.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/166910220/72454703-3460-42c7-9771-393fdfd1fbec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Broken-Kaddu go ahead
