### ISSUE TITLE
BUG: The fonts are not match in team page also hovering effect not good

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/18f54c54-eae2-4bab-b392-b54a6a0ec9de)
The fonts are not match in team page also hovering effect not good

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal assigned

**Comment by RamakrushnaBiswal** [comment]
solved #473
