### ISSUE TITLE
Feat: Add Social Media icons twiiter X and Instagram

### ISSUE THREAD

**Issue by GAVINESHWAR** [mdazfar2/HelpOps-Hub#467]
### Describe the feature

In the footer section there only 3 social media icons i would like to add Instagram and Twitter new Icon,Add these icons make good reach for the project. Along with that we can also add the email , phone and much more icons as well.

Assign me this issue @mdazfar2 to make contribution to the project.
Thank you

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124431955/afcd65d9-ffa2-4797-bfb3-5511cf39f177)
Here Instagram and Twitter icons are missing.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@GAVINESHWAR When we don't have a Twitter and Instagram account, what is the use of putting the icon?

**Comment by GAVINESHWAR** [comment]
It is better have the accounts @mdazfar2  sir to expose our projects, ideas , achievement for more impact in social media platform.

**Comment by mdazfar2** [comment]
@GAVINESHWAR will you take responsibility of creating and managing (proper uploading posts & story) insta and twitter accounts? 
- I'm not insta user

**Comment by GAVINESHWAR** [comment]
You are saying that i need to maintain social media accounts and do posts for the project, Ok i can maintain Instagram account, create posts and stories @mdazfar2 sir .

**Comment by mdazfar2** [comment]
I think there is no need for an Instagram account because Instagram is not a reliable platform for technical things.
