### ISSUE TITLE
BUG: Added Picture in landing page is not responsive.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/12740648-9fda-400b-bc06-2b0da7801a7f)

I will make it responsive.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 please assign me !

**Comment by mdazfar2** [comment]
@zalabhavy we are currently working to the landing page and will assign it to you once it is finalized.
