### ISSUE TITLE
DOC: Adding SECURITY.md file in the repo

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#475]
### What's wrong with the existing documentation

Adding SECURITY.md file in the repo

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal create an attraacative `SECURITY.md`

**Comment by RamakrushnaBiswal** [comment]
solved #478
