### ISSUE TITLE
Feat: Add transitions on hover to buttons

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#476]
### Describe the feature

I want to add shaking effect to "Sponsor," "Get Started," and "Star Us" buttons

### Add ScreenShots

Video demo:

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/69e003a8-4571-4e30-a6d8-b5ecbd7f6466

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Asymtode712 assigned

**Comment by Asymtode712** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/8fefc1a9-f42c-46e1-90a3-88676f3d8eb8

@mdazfar2 Please check this video and suggests any changes if needed

**Comment by mdazfar2** [comment]
> @mdazfar2 I have a suggestion that we can keep the background "white" for getting-started and sponsor button in dark mode, take a look at the video below:
> 
>  HelpOps-Hub.and.2.more.pages.-.Personal.-.Microsoft.Edge.2024-06-17.19-05-25.mp4

@Asymtode712 i think it looks attractive create pr of it
