### ISSUE TITLE
BUG: list of menu items is not visible in dark mode , hover of menu items in both mode 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

menu items is not visible in dark mode in all pages 

issue :
![Screenshot 2024-06-17 171229](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/dbf3d6d9-11d8-4754-babb-1d3d85c6e06d)

solved:

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/0ba0409c-760e-4909-b891-7ed4515a897c

added hover on list of menu items as per the theme 
 before : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/447d9653-a17a-4574-a7d4-8a48316d8ced

solved :

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/03f21abc-edb0-4769-810b-5bd8f60c6e52

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@ANKeshri assigned
