### ISSUE TITLE
Feat: Improve UI UX for contact us page

### ISSUE THREAD

**Issue by Madhu0-2** [mdazfar2/HelpOps-Hub#482]
### Describe the feature

We can improve the UI UX for the **Contact Us** page by changing the colour grading and making it more attractive in users eyes

### Add ScreenShots

![maxresdefault](https://github.com/mdazfar2/HelpOps-Hub/assets/126780854/a3af41f7-dbc3-44a8-9ba2-2672afb46287)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Madhu0-2 It doesn't match to the background color

**Comment by Madhu0-2** [comment]
Screenshot provided is just the skelton image will change color grading according to the website

**Comment by mdazfar2** [comment]
@Madhu0-2 assigned
