### ISSUE TITLE
BUG: Hovering effect of sponser is missing in team webpage 

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hovering effect of sponser button is missing in team webpage . 

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/aa023769-18bc-4a7e-b1db-e297e7600c05

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 I have solved this issue please assign me this issue under gssoc label.

**Comment by mdazfar2** [comment]
We will not apply this hover effect in this, please find some other issue

**Comment by Maana-Ajmera** [comment]
> We will not apply this hover effect in this, please find some other issue
@mdazfar2 In three pages it was hovering but in one team page only it was not hovering
