### ISSUE TITLE
Feat: Adding some description for contributors 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#487]
### Describe the feature

I will add a concise description for the contributors page .

### Add ScreenShots

![Screenshot 2024-06-18 142058](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/8cde7367-9abc-48d5-b4df-1b4232c15835)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned

**Comment by Ayushmaanagarwal1211** [comment]
Already Done
