### ISSUE TITLE
Feat: Adding Sonatype Nexus Repository setup

### ISSUE THREAD

**Issue by imksprateek** [mdazfar2/HelpOps-Hub#489]
### Describe the feature

This new section about Nexus repository setup will include:
- About Nexus
- Pre requisites
- Detailed step-by-setp installation
- set up
- Integration with Jenkins

I have experience working with Jenkins and Nexus. I'm requesting to assign this issue to me

### Add ScreenShots

![Nexus](https://github.com/mdazfar2/HelpOps-Hub/assets/122814422/a583ca79-86bc-46d4-bf60-0d4513c6e017)
![JenkinsCICD](https://github.com/mdazfar2/HelpOps-Hub/assets/122814422/bcbf0b09-90c7-42e1-bd22-99e13563b0de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by imksprateek** [comment]
Hey @mdazfar2
I was working on the issue

**Comment by mdazfar2** [comment]
@imksprateek everything that beginners can also do the same thing from scratch, hope you understand.
