### ISSUE TITLE
Feat: Tilty effect to all cards.

### ISSUE THREAD

**Issue by happyrao78** [mdazfar2/HelpOps-Hub#491]
### Describe the feature

on hovering the cards would have tilty effect making them more flexible and appearing.

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/138770813/f9c90e1a-d886-4042-a4a0-b6b4f067665c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@happyrao78 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
