### ISSUE TITLE
BUG: social icons link is not working of team page 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when clicking on social icons on team page it is not working .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/d60cf1b3-3afb-4da4-ae15-b16bbbe99ac5

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 sir please assign me this issue under gssoc label I want to work upon it .

**Comment by mdazfar2** [comment]
@ANKeshri Ooh shit! we are not looking at this.

- you are assigned ✅

**Comment by ANKeshri** [comment]
@mdazfar2  I have created the pull request for this issue please review it once and merge my pull request .
