### ISSUE TITLE
BUG: Text of some sections not properly visible in dark mode

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Text of some sections is not properly visible in dark mode.
Before:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/a4599402-bbc5-4f78-84f5-f875e8375835)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/078213ec-e513-48fe-aaa7-03a9896557fd)

After:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/c963fc12-5a60-46dc-a5ab-7782fbb16a8e)

Name and other inputs should be white in dark mode for proper visibility

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 Sir , please assign me this issue under gssoc level , I want to work on this issue.

**Comment by mdazfar2** [comment]
@Maana-Ajmera go ahead
