### ISSUE TITLE
BUG: contact and meet our team overlapping and hovering effect is not working on sponser in team page .

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

contact and meet our teem overlapping and hovering effect on sponser  is not working on sponser page .
![Screenshot 2024-06-19 004915](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/4089e021-8985-4ca2-a07d-4908dc2e0bc6)

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/dd51b440-1b1d-4db6-ba53-5229d5f181ba

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 sir I want to work on this issue , please assign it under gssoc label .

**Comment by mdazfar2** [comment]
@ANKeshri, `contact` and `meet our team` are not overlapping each other; they just cover the hamburger when it is open.

- Just work to add a `hover` effect on `Sponsor` on contributor page, which is same on the `landing page`, and leave the overlap thing.

**Comment by ANKeshri** [comment]
> @ANKeshri, `contact` and `meet our team` are not overlapping each other; they just cover the hamburger when it is open.
> 
> * Just work to add a `hover` effect on `Sponsor` on contributor page, which is same on the `landing page`, and leave the overlap thing.

@mdazfar2 sir I was thinking of doing it like this , please review it and if you like I will merge otherwise I will work on only hover of overlap.

**Comment by ANKeshri** [comment]
> > @ANKeshri, `contact` and `meet our team` are not overlapping each other; they just cover the hamburger when it is open.
> > 
> > * Just work to add a `hover` effect on `Sponsor` on contributor page, which is same on the `landing page`, and leave the overlap thing.
> 
> @mdazfar2 sir I was thinking of doing it like this , please review it and if you like I will merge otherwise I will work on only hover of overlap.


https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9a7cff22-fbf9-4038-a9d8-ab0be6bda356

**Comment by ANKeshri** [comment]
> > > @ANKeshri, `contact` and `meet our team` are not overlapping each other; they just cover the hamburger when it is open.
> > > 
> > > * Just work to add a `hover` effect on `Sponsor` on contributor page, which is same on the `landing page`, and leave the overlap thing.
> > 
> > 
> > @mdazfar2 sir I was thinking of doing it like this , please review it and if you like I will merge otherwise I will work on only hover of overlap.
> 
>  Recording.2024-06-19.012203.mp4

  earlier it was like this 


https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/a0a84948-ac1f-4d93-943b-60b68309e862

**Comment by mdazfar2** [comment]
> > > @ANKeshri, `contact` and `meet our team` are not overlapping each other; they just cover the hamburger when it is open.
> > > 
> > > * Just work to add a `hover` effect on `Sponsor` on contributor page, which is same on the `landing page`, and leave the overlap thing.
> > 
> > @mdazfar2 sir I was thinking of doing it like this , please review it and if you like I will merge otherwise I will work on only hover of overlap.
> 
> 
> https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9a7cff22-fbf9-4038-a9d8-ab0be6bda356
> 
> 

---

@ANKeshri that's nice create pr and also create pr for `sponsor` as well

**Comment by ANKeshri** [comment]
> > > > @ANKeshri, `contact` and `meet our team` are not overlapping each other; they just cover the hamburger when it is open.
> > > > 
> > > > * Just work to add a `hover` effect on `Sponsor` on contributor page, which is same on the `landing page`, and leave the overlap thing.
> > > 
> > > 
> > > @mdazfar2 sir I was thinking of doing it like this , please review it and if you like I will merge otherwise I will work on only hover of overlap.
> > 
> > 
> > 
> >   
> >     
> >     
> > 
> >     Recording.2024-06-19.012203.mp4
> 
> @ANKeshri that's nice create pr and also create pr for `sponsor` as well

@mdazfar2 sure sir I am working on it

**Comment by mdazfar2** [comment]
@mdazfar2 Please don't call me sir you can call me with my name

**Comment by ANKeshri** [comment]
> @mdazfar2 Please don't call me sir you can call me with my name

sure @mdazfar2
