### ISSUE TITLE
BUG: Link of Open source community not working and text not visible of new section added in dark mode

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- Sorry for creating similar issue of text not visible in dark mode but since it is new section added , I observed it just now.
- Also Open source community is directing to contributors in the code but the page is not found so there may be some error in the path provided.

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/2d983d98-8715-40e7-a80e-5ee7985cb742

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 sir , I want to work on this issue , please assign it to me.

**Comment by mdazfar2** [comment]
@Maana-Ajmera As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by Maana-Ajmera** [comment]
@mdazfar2 sure , thank you

**Comment by mdazfar2** [comment]
@Maana-Ajmera you are assigned for 'open-source community` not work and nothing else

**Comment by Maana-Ajmera** [comment]
@mdazfar2 Thank you I am working on it
