### ISSUE TITLE
Feat:Add Hover effects on We are creative section's cards.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#501]
### Describe the feature

I want to add hover effects like scale , shadow ect.
I will give better looks

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/aaf235d8-3ab8-4164-b03c-8623d73ebaab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Please assign me this task !

**Comment by mdazfar2** [comment]
@zalabhavy Right now it is not aligned properly, so once it is aligned I will tell you soon. I will assign it to you.

**Comment by mdazfar2** [comment]
Hi @zalabhavy, as you can see, there are many things on our landing page that don't look attractive. I will give you the Figma design for the landing page. Could you please try to make it the same as the Figma design?

- Here is the [Figma](https://www.figma.com/design/eqORN85KL4gsh5qxqNMVFx/Helpops-hub?node-id=0-1&t=R7VNx1nxOtRou001-0). Just look at the landing page design. You need to make it exactly like the Figma design. You have to work on only landing page. Hope you understand what I mean. 

- Raise an issue if you want to work on it.

**Comment by zalabhavy** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/8ad95a32-f246-49c4-8acb-ba9f7396a32f)
 @mdazfar2 now it is aligned please assign me !

**Comment by mdazfar2** [comment]
@zalabhavy Thanks for addressing me! You are assigned. According to your convenience, try to add an attractive hover effect that looks appealing.

**Comment by mdazfar2** [comment]
Hey @zalabhavy, haven't heard back from you yet. Are you currently working on this, or should I reassign it to someone else?

**Comment by mdazfar2** [comment]
@ANKeshri do you want to work on this issue?

**Comment by ANKeshri** [comment]
> @ANKeshri could you please handle this issue?

sure @mdazfar2 assign it to mee .

**Comment by mdazfar2** [comment]
@ANKeshri You are assigned.

**Comment by zalabhavy** [comment]
@mdazfar2 I have done please check it and merge !

**Comment by zalabhavy** [comment]
ANKeshri, you can create your own issue. I have already started my work, and if your pull request is completed, all my efforts will go to waste. Therefore, please refrain from interrupting others' tasks. I hope you understand.

**Comment by zalabhavy** [comment]
@ANKeshri Please don't work on it i have already created PR now ! 
Hope you will consider my condition and unassign this issue so i will get assign !
