### ISSUE TITLE
Feat: Add Kubernetes Commands Cheat Sheet

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [mdazfar2/HelpOps-Hub#502]
### Describe the feature

The feature aims to enhance user experience and productivity by integrating a comprehensive Kubernetes Commands Cheat Sheet directly within our platform. This cheat sheet will serve as a quick reference guide for users, allowing them to efficiently execute common Kubernetes tasks without having to leave the platform to search for command syntax and usage.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Already added

**Comment by Santhosh-Siddhardha** [comment]
But I Could not find in the repo

**Comment by mdazfar2** [comment]
@Santhosh-Siddhardha go ahead
