### ISSUE TITLE
BUG: color of Text in "Expert DevOps Insights"

### ISSUE THREAD

**Issue by rajdesai17** [mdazfar2/HelpOps-Hub#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when switching to dark mode, the text color appears to be similar to the background color in dark mode, making it difficult to read. This can make the text difficult to read, especially for users with visual impairments.

I recommend adjusting the text element's style specifically for dark mode to ensure adequate contrast with the dark background. Here are several possible solutions:

Change Text Color: Change the text color to a lighter shade, such as white or a light grey, in dark mode. This is the simplest and most common approach.

Add Text Shadow: Implement a subtle text shadow effect in dark mode. This can slightly improve readability without significantly altering the overall design.

Text Box with Background Color:  Create a text box element specifically for the navbar text in dark mode. This box would have a slightly lighter background color than the overall navbar background and house the text content. Ensure the text color within the box remains a contrasting color (e.g., black) for optimal readability.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@rajdesai17 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
