### ISSUE TITLE
Feat : enhancement of landing page 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#507]
### Describe the feature

doing it according to the figma dsign

### Add ScreenShots

![Screenshot 2024-06-19 173645](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/352482e3-1db6-4701-a3bb-449e09257575)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/268bd83d-e9b4-4fc8-a9d7-79f8c6c3d2d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@ANKeshri Please create PR as soon as possible because we have to design a new figma for other page.
