### ISSUE TITLE
BUG: Hover effect and Box shadow not found in your website

### ISSUE THREAD

**Issue by raviranjan0** [mdazfar2/HelpOps-Hub#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I want to add hover and box shadow effect in your website that makes your website impressive and provide a better experience of UI.

- @mdazfar2 Assign this issue to me. I want to work on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@raviranjan0 Great issue raised, Go ahead
