### ISSUE TITLE
Feat: Adding Top section to bottom section navigator 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#520]
### Describe the feature

I am thinking of adding a way through which when user visit the page then an moving down arrow will be shown and then when user clicked on that arrow the user will scrolled down to the next container or section .

### Add ScreenShots

![Screenshot 2024-06-19 235648](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/d31c5220-40b4-4888-a400-7921b2c287aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
