### ISSUE TITLE
Feat: wanted to add hovering effect to DevOps Arsenal icons 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#521]
### Describe the feature

according to the theme of project there must be hovering effect on the icons  of DevOps Arsenal and fix the night mode on Expert DevOps Insights .
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/cbb535cb-fb06-4776-b7c3-244d5f07804d)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/4bdaaa8c-2aaa-4743-b2b1-d77eb1a4497a)

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/b9d7fe3b-690d-4797-8e28-f6e31dc64088

wanted to hover like this .

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 I want to add this hovering effect on devops arsenal and fix text not visible in dark mode please assign me this issue

**Comment by mdazfar2** [comment]
@ANKeshri You are assigned to make the text visible in dark mode only.

- For the hover effect, we will think about changing and enhancing it. We will tell you what kind of effect we require in future.
