### ISSUE TITLE
BUG: hovering effect on get started button is not working .

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

while hovering on get started button it is not hovering and effect is not coming .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/49f9bca4-1c51-4d4b-a82c-b19cd90b9d6e

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign me this issue under gssoc label

**Comment by mdazfar2** [comment]
@ANKeshri go ahead
