### ISSUE TITLE
Feat: Enhancement of Projects theme 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#528]
### Describe the feature

 It has become apparent that certain colors used in the current design could be improved to provide better contrast and visibility . When scrolling so the whole color of the page looks like orange so i want to change the color like it will gradually becomes dark 

### Add ScreenShots

![Screenshot 2024-06-20 115802](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/3ca51fbe-384f-4ee5-8d68-4a0ae913eae3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 yes, we need it go ahead
