### ISSUE TITLE
Feat: Feature NavBar

### ISSUE THREAD

**Issue by Khushi-Pushkar** [mdazfar2/HelpOps-Hub#532]
### Describe the feature

Navbar is having very basic styling look i would like to work on it and make it look stylish

### Add ScreenShots

![Screenshot 2024-06-20 122151](https://github.com/mdazfar2/HelpOps-Hub/assets/142687709/aab85e26-7e77-445a-943b-2a558ba5324d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Khushi-Pushkar** [comment]
please @mdazfar2 assign this to me

**Comment by mdazfar2** [comment]
@Khushi-Pushkar What type of styling do you want to add? It would be great if you could share a demo video so I can assign this issue to you.

**Comment by Khushi-Pushkar** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/142687709/127b02bb-00d1-4a76-9411-0d458b224b59

Do you like this..??? I have more options otherwise

**Comment by mdazfar2** [comment]
@Khushi-Pushkar What's the difference? The same effect is available our website.

**Comment by Khushi-Pushkar** [comment]
If you require a dropdown navigation bar, I can implement that for you as well. Additionally, the navigation bar will include a search tab and a "Star Us" feature directly within the bar for easy access.

**Comment by mdazfar2** [comment]
@Khushi-Pushkar As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
