### ISSUE TITLE
Feat: Add Scroll to top button

### ISSUE THREAD

**Issue by MuraliDharan7** [mdazfar2/HelpOps-Hub#534]
### Describe the feature

The scroll to top button is not there in Home page. Whenever there is a website which has more elements into it, it should be having this feature. 

I can add this feature.

### Add ScreenShots

No need.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@MuraliDharan7 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
