### ISSUE TITLE
Feat: Add some message if user do not found the searched resources

### ISSUE THREAD

**Issue by Maheshwari-Love** [mdazfar2/HelpOps-Hub#537]
### Describe the feature

If user do not found the searched resource some message should be displayed to user

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142833275/32b45d87-759b-4424-9715-bc0942b95643)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@mdazfar2 please assign me this task...

**Comment by mdazfar2** [comment]
@pandeyji711 can you handle this issue?

**Comment by mdazfar2** [comment]
Hey @Maheshwari-Love , please let me know the status. It's been almost 5 days and you haven't responded.

- our code is converted to next.js is it possible to do this issue for you?

**Comment by Maheshwari-Love** [comment]
@mdazfar2 

> Hey @Maheshwari-Love , please let me know the status. It's been almost 5 days and you haven't responded.
> 
> * our code is converted to next.js is it possible to do this issue for you?

Yes I will, it has been late due to exams... within two days i will let you know

**Comment by vansh-codes** [comment]
I would like to work on this, please assign this issue to me.
@mdazfar2

**Comment by mdazfar2** [comment]
Hey @vansh-codes, thanks for commenting here. Actually, I need those bugs fixed, but @Maheshwari-Love is not replying, and it has been over 2 weeks.

- You are assigned.
