### ISSUE TITLE
Appear Navbar appear at top when user scrolling down

### ISSUE THREAD

**Issue by Utsavladia** [mdazfar2/HelpOps-Hub#538]
### Describe the feature

Make Navbar appear on top when user start scrolling down on website...

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/f2e60438-0be4-4840-bfa1-f6966a32fa46)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Utsavladia add this in `resources page` only resources page

**Comment by Utsavladia** [comment]
@mdazfar2  Should i add this navbar at top feature...?

**Comment by mdazfar2** [comment]
@Utsavladia Which navbar are you talking about? I think you want to add a bottom-to-top button.

**Comment by Utsavladia** [comment]
yes that i can add,
but also I was taking about the top Navbar that is only at the top of page and dissappear after scrolling so it should be fixed to access from anywhere in the page and if you dont want it to be seen alll the time then i can implement the functionality that it will appear only when the user start scrolling up on website so this top navbar will be visible at top.

i hope you understood else i can provide a video of this similar working

**Comment by mdazfar2** [comment]
> yes that i can add,
> but also I was taking about the top Navbar that is only at the top of page and dissappear after scrolling so it should be fixed to access from anywhere in the page and if you dont want it to be seen alll the time then i can implement the functionality that it will appear only when the user start scrolling up on website so this top navbar will be visible at top.
> 
> i hope you understood else i can provide a video of this similar working 
> 

<br>

@Utsavladia Yes, if you provide me a demo video then I might be able to understand it better.

**Comment by Utsavladia** [comment]
Navbar like this which appear again on scrolling up 

https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/46360f13-d83d-46c0-ad15-7316f28f4542

**Comment by mdazfar2** [comment]
@Utsavladia Exactly, I was thinking about adding it. But can you please wait? We are converting our code to Next.js, and the conversion is about 90% complete. We will deploy it this evening, and I will let you know to add this in Next.js.

**Comment by Utsavladia** [comment]
sure
@mdazfar2 
Please let me know after that so that i can start working on it .

**Comment by mdazfar2** [comment]
Hey @Utsavladia, now the code has been converted and deployed successfully on `Next.js`. Now you can work on this issue.
- The whole code is in the `website3.0` folder.
- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue as @Utsavladia hasn't responded till now

**Comment by mdazfar2** [comment]
> @mdazfar2 Please assign me this issue as @Utsavladia hasn't responded till now

@Asymtode712 
Sure, you are assigned

**Comment by Utsavladia** [comment]
@mdazfar2  I am working on this right now..
I have waited when you told you are converting into next.js...

**Comment by mdazfar2** [comment]
@Utsavladia This is not a good habit. You should have responded after seeing the message so that I know you are still active.

**Comment by Utsavladia** [comment]
@mdazfar2 
I have not responded but I was going to make pull request today only..
I want to work on it please assign to me
@Asymtode712  already have 14 merges in this repository

**Comment by mdazfar2** [comment]
@Utsavladia It does not matter who is merging & how much!

**Comment by Asymtode712** [comment]
> @mdazfar2 I have not responded but I was going to make pull request today only.. I want to work on it please assign to me @Asymtode712 already have 14 merges in this repository

No problem @mdazfar2 let him work on this....

**Comment by Utsavladia** [comment]
@mdazfar2  Thankyou I will try to complete it asap 😊

**Comment by Asymtode712** [comment]
@Utsavladia I thought you were working on some other issues and forgot about this.....So I thought that I should go for it......Sorry if I interrupted your work!! All the best for solving this!!

**Comment by mdazfar2** [comment]
Thanks @Asymtode712 

@Utsavladia Make sure that the logo is visible too.

**Comment by Utsavladia** [comment]
@Asymtode712  no issues.. I appereate your dedication towards contributing....
