### ISSUE TITLE
Add hover effect on Buttons

### ISSUE THREAD

**Issue by Utsavladia** [mdazfar2/HelpOps-Hub#539]
### Describe the feature

There should be a hover effect on some buttons

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/2474d185-6271-417c-88ff-156a8081947b)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/c3abd141-08f2-4d96-b4fc-bcce93a99ca7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by adi271001** [comment]
go ahead @Utsavladia

**Comment by mdazfar2** [comment]
Hi @Utsavladia I shouldn't say like that and sorry as well

- Yes, I know that, but we are creating another page for it. After the completion of this page, I will let you know to add this in the future.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@mdazfar2

**Comment by mdazfar2** [comment]
Hey @TheNikhilRaj yes it is under GSSOC.

- After completing the backend for the newsletter, I will definitely assign it to you. It will take some time, at least 1 week.

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Comment by TheNikhilRaj** [comment]
okay i can wait till and is there any work under gssoc as a fronted please reach me!
@mdazfar2

**Comment by mdazfar2** [comment]
@TheNikhilRaj yes sure will let you know if there any work related frontend.

- Please don't forget to join our official [Discord](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo
