### ISSUE TITLE
Fix We are creative section

### ISSUE THREAD

**Issue by Utsavladia** [mdazfar2/HelpOps-Hub#540]
### Describe the feature

The section is not having uniform design it should be arrenged arround the text properly with uniform distance around the text "we are creative"

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/bfc05144-2c85-490f-a3fe-902b040bf54f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hi @Utsavladia will let you know about that actually already someone working on it

**Comment by mdazfar2** [comment]
Already solved
