### ISSUE TITLE
Fixing the Contrast of the Contact Us Form in Dark mode

### ISSUE THREAD

**Issue by alpharsh** [mdazfar2/HelpOps-Hub#542]
### Describe the feature

The visibility of the Contact us form's name, email and comment is not properly visible in dark mode

### Add ScreenShots

![Screenshot 2024-06-20 224541](https://github.com/mdazfar2/HelpOps-Hub/assets/108024082/341c2e82-e68a-4674-b6ab-fbd3911356e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@alpharsh assigned
