### ISSUE TITLE
Project Proposal: Creating a 404 not found page for the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#543]
### Overview

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/595eb5c8-7360-4790-b8c7-ce77c58536ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this project proposal

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal assigned

**Comment by RamakrushnaBiswal** [comment]
solved via #572
