### ISSUE TITLE
BUG: Images and other parts of home page are not responsive

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- Images and other parts of page get cropped when we decrease the size of the screen .
- I  want to make the page RESPONSIVE.

Before :

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/6850ef5a-9bd4-4a3d-8777-de5b40295420

After:

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/58863594-6394-4fa5-a280-c6d1536a7342

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 I want to work on this issue and make the home page responsive , please assign me this issue.

**Comment by Maana-Ajmera** [comment]
@mdazfar2 should I work on it ?....if yes please assign it to me.

**Comment by adi271001** [comment]
@Maana-Ajmera go on

**Comment by Maana-Ajmera** [comment]
@adi271001 working on it

**Comment by mdazfar2** [comment]
@Maana-Ajmera I shouldn't say like that and sorry as well

- Actually, we are updating more things on the home page. We will let you know once everything is updated. Leave it for now; make it responsive later :)
