### ISSUE TITLE
Feat: adding splide.js in DevOps Arsenal part

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#546]
### Describe the feature

https://splidejs.com/

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/542024b8-f6f4-491f-8a46-ae951aeb6109)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal go ahead

**Comment by RamakrushnaBiswal** [comment]
solved via #553
