### ISSUE TITLE
BUG: Missing Favicon on HelpOps-Hub Web 

### ISSUE THREAD

**Issue by raviranjan0** [mdazfar2/HelpOps-Hub#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I  have found that there is missing favicon in this website. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@raviranjan0 you are assigned
