### ISSUE TITLE
Feat:Want to change color theme in dark mode 

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#551]
### Describe the feature

Currently the cards in dark theme is of orage color which is looking bit wierd i could fix that

### Add ScreenShots

![Screenshot 2024-06-21 041346](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/1b3bd384-7f4b-4cd1-88cf-65bba49ce52b)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/d47a5579-4919-4b50-b630-656c660b9d70)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/acd562fe-e956-4524-a56c-d3e401ae269c)

see orange color look wierd i will change this theme and Apply it everywhere

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 you are assigned fix it
