### ISSUE TITLE
Feat:Want to write backend of Contact Us page

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#552]
### Describe the feature

I want to add backend of Contact Us Page.In this  User Will Acknowledgment Mail And Admin will recieve mail Regarding Query

### Add ScreenShots

no ss required

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hi @nishant0708 please don't feel bad :)

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
