### ISSUE TITLE
Feat: Shrink the cards & banner icons on the Landing page

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#554]
### Describe the feature

Currently, the four cards and the banner icons at the lower part of our landing page are too spread out and one of them is partly visible on 100% normal zoom on desktop view. We would need to shrunk them in order to get a better view of those cards and icons.

### Add ScreenShots

Current :

![ISSUE1](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/60f56449-de41-4d55-b600-2e3dd878921e)

![Issue2](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/bb7c388b-a74a-489f-8690-8fbe7d39a9b5)

At 90% zoom:

![Issue1_90](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/61256ccf-8030-45ab-8114-881128da4a5a)

Solution discussed:

![solution](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/2df7e3d6-86a0-47ef-ab7a-564e97adcb48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 create PR
