### ISSUE TITLE
BUG: FIX day and night mode in all the resources 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in the resourse the page is same for the dark and light mode . 

BEFORE : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/de7dd607-588b-40a6-a885-5da9d23c3a9d

AFTER 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/c5d0eb37-df69-4f43-aa5f-675f4764eba9

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please review once and assign this issue to me i have already worked on it .

**Comment by mdazfar2** [comment]
@ANKeshri you are assigned.

- please do not add any extra code, you add useless codes all the time, you can change code by single as well.
