### ISSUE TITLE
Feat: Creating  a testimonial section

### ISSUE THREAD

**Issue by ayush-848** [mdazfar2/HelpOps-Hub#560]
### Describe the feature

There will be a testimonial section where review will be mentioned

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126975547/c65bdfc2-fe86-4f7b-a0fb-786773db8bd1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@ayush-848 Will we enter this manually or will it be automatic, meaning whenever someone comes and gives a review, it will show here like this?

**Comment by ayush-848** [comment]
> @ayush-848 Will we enter this manually or will it be automatic, meaning whenever someone comes and gives a review, it will show here like this?

Well for manually you have got the contact part here it will be just for display

**Comment by mdazfar2** [comment]
@ayush-848 Well, nice! I will tell you soon whether this section will be added or not.

**Comment by ayush-848** [comment]
> @ayush-848 Well, nice! I will tell you soon whether this section will be added or not.

ok

**Comment by mdazfar2** [comment]
@ayush-848 

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo
