### ISSUE TITLE
Feat: Adding Menu Bar Instead of Hamburger Menu

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#562]
### Describe the feature

I've noticed that our HelpOps-Hub website is not fully optimized for mobile view. The current navbar layout can be challenging to navigate on smaller screens. To improve user experience, I propose redesigning the mobile navbar by adding all navigation links to a stylish menu bar at the bottom of the screen.

## ✅ @sanjay-kv sir, this time there is no spam.
@sanjay-kv sir, please don't say that I am raising the same responsive issue again and again and creating PR for GSSOC points. This time it is completely different. Please check it yourself. This time I worked on genuine .

## Issue Details:
- 🖥️ Current State: The website's navbar is difficult to use on mobile devices, affecting overall usability.
- 📱 Proposed Solution: Implement a new menu bar at the bottom of the mobile view, containing all navigation links in a sleek and appealing style.

## Benefits:
- 🌟 Improved Usability: Enhances the ease of navigation for mobile users, making the site more user-friendly.
- 📈 Increased Engagement: A better mobile experience can lead to higher user engagement and satisfaction.
- 🎨 Modern Design: A stylish bottom menu bar will give the website a contemporary look, aligning with modern web design trends.

## Add Screenshot

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/079d7700-9a9c-4a4e-b535-1b3d3a384e7e)
> [!NOTE]
> It is just a design after implementation it looks also good and attractive.

***I would be happy to work on this enhancement to ensure the HelpOps-Hub website offers an excellent experience for all users, regardless of the device they are using.***

Looking forward to your feedback and the opportunity to contribute! 😊

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211, yes, that level of responsiveness is exactly what we're looking for. Can you try applying it to all pages except the "contributor" page?

**Comment by Ayushmaanagarwal1211** [comment]
Yes i can

**Comment by shreyash3087** [comment]
@Ayushmaanagarwal1211 if possible try to follow BEM naming convention as it would be better for readability and functionality,@mdzafar what do you say?

**Comment by mdazfar2** [comment]
> @Ayushmaanagarwal1211 if possible try to follow BEM naming convention as it would be better for readability and functionality,you can learn about it form here-https://getbem.com/naming/ ,@mdzafar what do you say? 
> 

<br>

@shreyash3087 It would be great if you could send some layout, example, or screenshot you used before with the BEM convention. This will give us an idea of how it works.

**Comment by shreyash3087** [comment]
![Screenshot (56)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/fa164d9b-039a-40a2-8717-af9e5357c9ea)

This is a good example,here card is a block,and its child component has been given name as card__content or card__title this is called block__element naming and this is helpful because normally people write like this
```
<div class="card">
   <div class="title">
   </div>
</div>
```
yaha pe sirf `title` likhne ki vajah se if we use the class `title` in another `block` so that will have effects form this class but if we write `card__title` so it will just limit this class to this block only aur iske styling ka effect dusre blocks pe nhi jayega

hope you understand

**Comment by shreyash3087** [comment]
@mdazfar2 and after this we have modifiers that is used to define variations of a element like ek button hai inside card block so you will give it a name as `card__block--primary` because a button can have various types like primary,secondary etc

Overall it makes the code much better

**Comment by mdazfar2** [comment]
Thank you, @shreyash3087 will implement this.

**Comment by mdazfar2** [comment]
issue solved
