### ISSUE TITLE
Feat:  Adding more styles to subscribe to newsletter section

### ISSUE THREAD

**Issue by SuhainaFathimaM** [mdazfar2/HelpOps-Hub#567]
### Describe the feature

 Adding more styles to subscribe to newsletter section

It can be styled more.. the text is not aligned.. buttons can be added with hovering effect

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/153417476/a784b8b9-431b-4f9a-921c-de195c712ded)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@SuhainaFathimaM but we are creating another page for it. After the completion of this page, I will let you know to add this in the future.

- Please search for another issue and raise it, which I'm happy to assign to you. :)
