### ISSUE TITLE
Feat: Removing unnecessary gap 

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#568]
### Describe the feature

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/bbbeeec2-f55b-4cdf-8e23-daab34f6ff74)

I can remove this gap please assign me this issue under gssoc

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/65805d3e-d045-4eb7-a632-8a33175a55be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hi @dhairyagothi, heads up! There's a potential conflict with the responsive design work being done by someone else. To avoid this, can you start on this task tomorrow? I'll brief you on the details then. :)

**Comment by mdazfar2** [comment]
Hi @dhairyagothi You are assigned. Now you can start your work, and please try to create a pull request today if possible, but there should not be any changes in the animation.

**Comment by mdazfar2** [comment]
@ANKeshri Do you want to work on this? Please let me know I'll assign it to you.

**Comment by ANKeshri** [comment]
@mdazfar2 yes i wil do that

**Comment by ANKeshri** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9728c1ac-5c3e-40c0-89d1-401e72e94daf

Should I raise this issue from resource pages contact us is not linked just like home page and other 2 .

**Comment by mdazfar2** [comment]
@ANKeshri Okay! I'll assign this issue to you

**Comment by ANKeshri** [comment]
> Recording.2024-06-22.102043.mp4 
> Should I raise this issue from resource pages contact us is not linked just like home page and other 2 .

@mdazfar2

**Comment by mdazfar2** [comment]
> 
> https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9728c1ac-5c3e-40c0-89d1-401e72e94daf
> 
> Should I raise this issue from resource pages contact us is not linked just like home page and other 2 .


@ANKeshri try to resolve this in one PR

**Comment by ANKeshri** [comment]
> > >>1.00<<
> >   
> >     
> >     
> > 
> >     Recording.2024-06-22.102043.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > Should I raise this issue from resource pages contact us is not linked just like home page and other 2 .
> 
> @ANKeshri try to resolve this in one PR

sure

**Comment by ANKeshri** [comment]
@mdazfar2 is this much fine now .
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/591e944e-69b3-4bcb-982f-3319958c05bb)

**Comment by mdazfar2** [comment]
@ANKeshri much better

**Comment by mdazfar2** [comment]
@ANKeshri also try to fix it

<br>

![image-2.png](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/ae118e71-5788-434f-83f4-1ab86ac7c6a3)
