### ISSUE TITLE
Feat: Feedback Type

### ISSUE THREAD

**Issue by AkhilaSunesh** [mdazfar2/HelpOps-Hub#569]
### Describe the feature

Users will be able to choose the type of feedback. 
When the user chooses other, The user will be asked to specify the topic.

### Add ScreenShots

![WhatsApp Image 2024-06-14 at 15 12 33_7ea25036](https://github.com/mdazfar2/HelpOps-Hub/assets/140897461/5a5ef9b9-0b89-4b0e-86f1-19aaee628e6b)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/140897461/f80b9b44-5e5e-486c-bd98-0323f84bf295)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @AkhilaSunesh please don't feel bad.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
