### ISSUE TITLE
Hover on card should not overlap other cards.

### ISSUE THREAD

**Issue by Utsavladia** [mdazfar2/HelpOps-Hub#57]
### Describe the feature

The card on hover shold not cover other cards to improve the user experience.

I would love to contribute to this project the enhhance the user experience.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/d5943d6e-d56e-4765-b48b-65ec4d41e591)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Utsavladia Do a very little size, just a little
