### ISSUE TITLE
BUG:remove unnecessary gap 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

there is unnecessary gab in landing page  as shown below  .
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/e80cba2c-7d9b-48e8-b698-05fc230d9f91)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign me this issue under gssoc . That was closed by the one who has opened .

**Comment by mdazfar2** [comment]
Hey @ANKeshri, I've already assigned the issue, and then you create a new issue? You can also work on the previous one and create PR in reference to someone else's issue

**Comment by ANKeshri** [comment]
> Hey @ANKeshri, I've already assigned the issue, and then you create a new issue? You can also work on the previous one and create PR in reference to someone else's issue

as soon as you assigned me the other person closed it so i have created new one but now you have opened it so i will work on this only
