### ISSUE TITLE
BUG: Nav Links redirect to Incorrect path in mobile devices

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:** 

The Nav Links redirect to incorrect path on mobile devices that cause this error - 

![Screenshot (57)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/8b321bc2-b534-4797-b014-57b3d576380c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 please check issue #543 you can comment there I'll assign this to you
