### ISSUE TITLE
BUG: ffixing CSS in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/5eef6445-8a08-46ae-b647-296e41daaaf5)

i can fix this in mobile

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhairyagothi This issue is a duplicate. The same issue has already been raised by someone else. Please review all issues before creating a new one.
