### ISSUE TITLE
changed the syle of submit feed back button

### ISSUE THREAD

**Issue by Krishna100604** [mdazfar2/HelpOps-Hub#576]
### Describe the feature

gave the submit feedback same styling as all other buttons to maintain  the consistency if website

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/110299021/dc1902fc-f68e-4b0b-a085-4103c838374e

@azfar-2 here is the demo of feature 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @Krishna100604, we are not working on that website you want to contribute to.
