### ISSUE TITLE
added hover effect in contact page and gave animation contact page 

### ISSUE THREAD

**Issue by Krishna100604** [mdazfar2/HelpOps-Hub#578]
### Describe the feature

when we hover on starts it will be filled with color

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/110299021/59e853b9-72eb-4b29-a1a9-27c01feb429c

hey @mdazfar2 can you assign me this

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @Krishna100604 please don't feel bad :) as of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
