### ISSUE TITLE
Feat: Add LOADING.. component while the cards are loading

### ISSUE THREAD

**Issue by Utsavladia** [mdazfar2/HelpOps-Hub#58]
### Describe the feature

There should be a loading ... component while the cards are being loaded.

this will improve the user experience.

### Add ScreenShots

![Screenshot 2024-06-02 125128](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/f18e3745-6cfe-49d9-ae64-fa9a6fe20426)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Utsavladia go ahead and add an impressive loading component which is similar to the website 

- you are assigned

**Comment by pandeyji711** [comment]
@mdazfar2 currectly working.. in this please assign

**Comment by mdazfar2** [comment]
@pandeyji711 you are assigned
