### ISSUE TITLE
BUG: the link of home/about/contact is not working when screen size is small .

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when the screen size is small at below the home/about/contact button is appearing but it is not redirecting to the actual page .
also i am thinking of removing those small icons and add hovering effect to the home/about /contact just as the hovering which is given to all the buttons at the nav bar .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/4bb2b5eb-a541-432a-926d-de6b5c0c311a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@ANKeshri Actually, it is work in progress on another issue. Please review all issues before creating a new one.
