### ISSUE TITLE
Feat:Want to fix some bugs in mobile view 

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#582]
### Describe the feature

Not working in Dark mode:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/80a862b6-315e-420c-b181-faffbb595873)

Overlapping:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/2ec5e9d0-7250-47d2-bb97-7996d1e7552f)

Some things getting Cut::
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/2520dd4a-1569-4392-85fd-a23ccf7cc899)

Not responsive:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/c76068af-cd18-4526-b3b3-4df1f52a40e0)

Navbar bug:
(in small screen)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/2b808e0d-6f97-4723-962b-2d12b8ff5614)

Not alinged properly:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/86000ecc-aa58-4228-9f96-7a430688c01c)

### Add ScreenShots

ss in description

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by nishant0708** [comment]
Okay thanks..
