### ISSUE TITLE
Feat: Add scroll up button 

### ISSUE THREAD

**Issue by heli0707** [mdazfar2/HelpOps-Hub#584]
### Describe the feature

A scroll-up button is a user interface element typically located at the bottom right corner of a webpage. When clicked, it automatically scrolls the page back to the top, enhancing user navigation and improving overall user experience by providing a quick way to return to the top of long pages.

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/95361125/c3b675d4-7cc1-49df-8704-3b1de7957d3f

something like this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@heli0707 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
