### ISSUE TITLE
Feat: Animated text "HelpOps-Hub" on main page 

### ISSUE THREAD

**Issue by heli0707** [mdazfar2/HelpOps-Hub#585]
### Describe the feature

Animated text can capture user attention and make the main page more dynamic and engaging.

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/95361125/a3607c3a-3f91-4433-bc05-362e07d23130

implement something like this on the main page text "HelpOps-Hub"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @heli0707, that's awesome, but we will let you know about that in the future because right now we have other plans. Please wait, and we will connect with you soon about it.
