### ISSUE TITLE
Feat: Enhanced Navbar Hover Effect

### ISSUE THREAD

**Issue by heli0707** [mdazfar2/HelpOps-Hub#586]
### Describe the feature

Improving the navbar hover effect can make the navigation more intuitive and visually appealing. A suitable enhancement could include adding smooth transitions, changing the background color, and incorporating subtle animations.

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/95361125/f3f646cf-e58d-478b-8035-346ff4199ee0

something looks like this!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@heli0707 You are assigned! But don't add unnecessary code. Just edit the code if needed; otherwise, it isn't necessary.
