### ISSUE TITLE
BUG:text Not Fitting + Newsletter background 

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

text is not fitting in the sceen
![Screenshot 2024-06-22 191621](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/33b7b431-5d68-4620-bdc3-d36a74a368da)

this is looking odd
![Screenshot 2024-06-22 191711](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/7ea3c8fd-46bb-4ea6-a6be-b752e53f9ee9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 It's look good and attractive as in the deployed.

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/c8e7c7c6-b72d-4ce8-b652-3ce89fc2630e)
