### ISSUE TITLE
Feat:Want to Add Custom Scroll bar

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#588]
### Describe the feature

Want to Add Custom scroll bar to Enhnace look of Website

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/31ed70e7-f0b4-4f3c-8ac3-06a192e155fd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 As I see that you create issues again and again, why don't you create all issues in one? This is not the way to work on open source.
