### ISSUE TITLE
Feat: adding a customized Scroll Bar

### ISSUE THREAD

**Issue by anagha-chaudhari** [mdazfar2/HelpOps-Hub#592]
### Describe the feature

It would be great if the website has it's customized scroll bar. I would like to work upon this. Can you please assign me this issue under Gssoc'24?

### Add ScreenShots

Right now, this is the default scroll bar. I would add a designed scroll bar that aligns with the color theme of the website

![helpops_scrollbar](https://github.com/mdazfar2/HelpOps-Hub/assets/143149376/bda27804-0c04-4915-af87-198fdcc8c429)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@anagha-chaudhari can you share some demo or any screenshot which type of change you want to contribute us.

**Comment by anagha-chaudhari** [comment]
Sure @mdazfar2 

![scrollbar](https://github.com/mdazfar2/HelpOps-Hub/assets/143149376/02b40296-2178-4705-9320-b4539170ef3a)

https://github.com/mdazfar2/HelpOps-Hub/assets/143149376/d1dab650-0589-452c-ab96-c8aa6427ea0c

**Comment by mdazfar2** [comment]
@anagha-chaudhari you are assigned
