### ISSUE TITLE
BUG: hovering efect on star us is not working

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when hovering on start us button it is not working .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/e09a4d49-a8bf-4f08-96fe-d33f59d5e124

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 i think someone has removed hovering effect on star us button . Please assign me I will fix it .

**Comment by mdazfar2** [comment]
@ANKeshri Exactly, I was thinking about it. But can you please wait? We are converting our code to Next.js, and the conversion is 90% complete. We will deploy it this evening, & will let you know to add this in Next.js.

**Comment by ANKeshri** [comment]
> @ANKeshri Exactly, I was thinking about it. But can you please wait? We are converting our code to Next.js, and the conversion is 90% complete. We will deploy it this evening, & will let you know to add this in Next.js.

sure

**Comment by ANKeshri** [comment]
@mdazfar2 now it has been removed from all the buttons like star , sponser and get started . I can fix them please assign me .

**Comment by mdazfar2** [comment]
@ANKeshri I have noticed that you always raise duplicate issues. Please go through all the issues once to see which ones are present and which ones are not.

**Comment by ANKeshri** [comment]
> @ANKeshri I have noticed that you always raise duplicate issues. Please go through all the issues once to see which ones are present and which ones are not.

@mdazfar2  oh sorry  , I was think you will assign me this after deployment so I have commented . Form next time I will surely keep in mind .
