### ISSUE TITLE
Feat : Add message in  newsletter after submition

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#599]
### Describe the feature

Want to make submit button active and message shown when anyone submit email under that input field.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/39745f47-2a9d-40cc-be53-6bd7102806e9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Please assign me !

**Comment by mdazfar2** [comment]
Hey @zalabhavy we are deploying our new code which is on Next.js so you have to wait until deploy till evening! THANKS
