### ISSUE TITLE
Add Documentation for Docker Installation on Ubuntu

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [mdazfar2/HelpOps-Hub#6]
## Description

We need to provide detailed instructions for installing Docker on Ubuntu to help our team set up and manage containerized applications. This documentation will serve as a guide for both new and existing team members to ensure a smooth setup process.

### Tasks
1. Create a new folder named `Docker Installation in Ubuntu`.
2. Add readme.md file which contains step-by-step instructions for installing Docker on Ubuntu.
3. Include necessary commands, expected outputs, and troubleshooting tips.

@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Santhosh-Siddhardha Sure, assigning it to you.

**Comment by Santhosh-Siddhardha** [comment]
@mdazfar2 May i know why you closed this issue

**Comment by mdazfar2** [comment]
@Santhosh-Siddhardha 
Sorry I should not say like that but someone else is create documentation on this issue and you were already late. And you didn't even reply anything, mean you did not give any confirmation.
