### ISSUE TITLE
one contributor section on HelpOps-Hub web 

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#60]
### Describe the feature

@mdazfar2 your website need contribution section that attract contributor to contribute
please assign this to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 Great idea! You are assigned

**Comment by GAGGZ1** [comment]
@mdazfar2 please also assign this issue to me and i'm recommended by @pandeyji711

**Comment by mdazfar2** [comment]
Sure you guys work together

**Comment by GAGGZ1** [comment]
thanks you soo much @mdazfar2

**Comment by Dark-S8uL** [comment]
@mdazfar2 please assign this issue to me, I'm recommended by @pandeyji711 .

**Comment by mdazfar2** [comment]
Let's do it 🔥🤝

**Comment by Dark-S8uL** [comment]
It was very thoughtful of you @mdazfar2 .
