### ISSUE TITLE
Feat: Making contact us page according to the dark theme

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#602]
### Describe the feature

On changing the theme the color of the contact us form is not changing so i want to fix that like all other elements in the dark mode 

### Add ScreenShots

![Screenshot 2024-06-23 223536](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/c0cac920-f46a-44a0-93dd-eac615fa414b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@Ayushmaanagarwal1211 It is changing the color,its changing from orange to dark brown for dark mode, tho @mdazfar2 can tell if he wants any other color

**Comment by Ayushmaanagarwal1211** [comment]
Oh ya it is changing but i want to change it to black like all other elements

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 I think all black doesn't look good.
