### ISSUE TITLE
DOC: Add Detailed Comments to All Pages in the New CodeBase

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#603]
### What's wrong with the existing documentation

**Description:**

Currently, the codebase for our website lacks sufficient comments, making it difficult for developers to understand the code and maintain it effectively. To improve code readability, ease of maintenance, and onboarding of new developers, we need to add clear, concise, and informative comments throughout the codebase. This will also help in debugging and updating the code in the future.

**Tasks:**

- Identify Key Areas
- Add comments to explain the purpose of complex functions and classes.
- Describe the functionality of important code blocks.
- Clarify the logic behind key algorithms and data manipulations.
- Update or create documentation to reflect changes and provide guidelines on how to comment code effectively in the future.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 Thanks for the suggestion! Task assigned to you for adding detailed comments.
