### ISSUE TITLE
Feat: Convert Classnames on All Pages to follow BEM naming Convention

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#604]
### Describe the feature

To improve the maintainability, scalability, and readability of our CSS, we need to refactor the class names across all pages of the website to follow the BEM (Block, Element, Modifier) naming convention. The BEM methodology helps create reusable and modular code, making it easier to manage and less prone to conflicts.

**Tasks:**

- Review Current Class Names
- Refactor Class Names
- Update Stylesheets
- Update JavaScript

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 Issue acknowledged. Task assigned to you.
