### ISSUE TITLE
Feat: Adding hovering effects to all the buttons on new version of site

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#605]
### Describe the feature

Currently deployed version of our site which uses Next.js, lacks the hovering effects on the buttons like the previous version of the website. So I would like to add those effects for this version

### Add ScreenShots

Not Required

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 Issue acknowledged! You are assigned.
