### ISSUE TITLE
BUG: Mode is not working properly in resources page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When i reloading a page from resources page then then mode showing incorrect behaviour .

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/e01e784e-8d20-4111-8d43-1766319a6374

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Please don't add unnecessary code. If code is needed, then add it; otherwise, try to change the existing code and then create a PR. 

- Also, add a comment explaining the changes you made.

**Comment by Ayushmaanagarwal1211** [comment]
Ok
