### ISSUE TITLE
Feat:Adding hover effect to mode changing button

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#607]
### Describe the feature

I will add a hover effect to mode changing button 

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/42d4071d-2ada-4673-a5da-b294a1f97fcd

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211
