### ISSUE TITLE
✨ Feat: Add a "Scroll down progress bar"

### ISSUE THREAD

**Issue by MastanSayyad** [mdazfar2/HelpOps-Hub#608]
### Describe the feature

Hey @mdazfar2 

I would like to suggest adding **a scroll down progress bar** to the website to enhance user experience. 
- A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. 
- This feature can be especially helpful for long pages blogs and articles.

### Add ScreenShots

- **Like this**

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101971980/35e9e274-addc-4c2d-af7c-7bda886582e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@MastanSayyad you are assigned

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made on code.
- Please don't add unnecessary code if there is no need! Thanks :)
