### ISSUE TITLE
Feat: Create a Contact us Page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#61]
### Describe the feature

I will create a contact us page for the website .

### Add ScreenShots

I will create a contact us page for contact if any error.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 As of now, we think we don't need this. We'll let you know in the future if there is a need.
