### ISSUE TITLE
Feat: Visible particle.js only the hero section

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#611]
### Describe the feature

particle.js visible in all over the website

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/2e0a4854-35d4-4e00-8ef2-62879695ecaa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Go ahead

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Could please please assign this to me i will apply particles effect on only header ( Top of the page ) .

**Comment by mdazfar2** [comment]
Sure @Ayushmaanagarwal1211

**Comment by mdazfar2** [comment]
This issue solved by PR #633
