### ISSUE TITLE
Feat:Adding animations in the devops answer hub

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#613]
### Describe the feature

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/597ac63d-6fbf-4dae-8869-3ab7741b9f91)
we can add here

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/3de4b4f0-d5b0-47ee-aa8a-c28a5c44dcda)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal issue acknowledged! You are assigned
