### ISSUE TITLE
BUG:open source community link not working in all the pages .

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when clicking on open source community link it is not working and unerlining it as it was earlier .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/35028aa1-53f1-4759-98ea-45451098ef0d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign this issue to me under gssoc labels , I will fix it .

**Comment by mdazfar2** [comment]
@ANKeshri you are assigned

**Comment by ANKeshri** [comment]
@mdazfar2 earlier hovering effect on dark theme to social link icon and nav bar items were orange matching the theme of project . do you want me to fix it . 
earlier : 
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/de1e5a3f-41b2-4dfb-9895-b3b5fd7ae546)
![WhatsApp Image 2024-06-24 at 22 14 30_5934474e](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/a4121d1d-26b2-4a3a-8687-cd384f7ca216)

**Comment by mdazfar2** [comment]
Let me check first @ANKeshri

**Comment by mdazfar2** [comment]
> @mdazfar2 earlier hovering effect on dark theme to social link icon and nav bar items were orange matching the theme of project . do you want me to fix it . earlier : ![image](https://private-user-images.githubusercontent.com/159682348/342425179-de1e5a3f-41b2-4dfb-9895-b3b5fd7ae546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTgyODMsIm5iZiI6MTcxOTI1Nzk4MywicGF0aCI6Ii8xNTk2ODIzNDgvMzQyNDI1MTc5LWRlMWU1YTNmLTQxYjItNGRmYi05ODk1LWIzYjVmZDdhZTU0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxOTM5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDdkNzg3ZGM2MDJjN2JjZDMxNjdkOWE4Yzc3NzhlYzgxYTAyMmZlZDdkMTEwMTNiNjljNzMyNWZlMGY2OTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AX425IZYKYCpEgZGOo1zMraniRN6YzLFN5WVArGy6d8) ![WhatsApp Image 2024-06-24 at 22 14 30_5934474e](https://private-user-images.githubusercontent.com/159682348/342425329-a4121d1d-26b2-4a3a-8687-cd384f7ca216.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTgyODMsIm5iZiI6MTcxOTI1Nzk4MywicGF0aCI6Ii8xNTk2ODIzNDgvMzQyNDI1MzI5LWE0MTIxZDFkLTI2YjItNGEzYS04Njg3LWNkMzg0ZjdjYTIxNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxOTM5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2ZhMTQxNmZlNmM1NzRiZDliZDYzZjI2YmJlNzc5ODFkZjFkYTliMGQyYTRkYWYxMjhmYThmZmU1OTI0NGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pkv8gkJPAYG7q4HOrfaTRgHDK4i5ndQkfFL1bvH9K94)

hey @ANKeshri create issue for this one and thanks for addressing me this issue. and create PR
