### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [mdazfar2/HelpOps-Hub#616]
### Describe the feature

Hey @mdazfar2, 
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Screenshot(Mandatory):
![Capture1](https://github.com/mdazfar2/HelpOps-Hub/assets/129590267/a531ce07-c3af-44c6-ad51-6123fb24e78d)

@mdazfar2 ,Could you please assign me this issue under gssoc'24 ?
Are you contributing under any open-source program ?
GSSOC'24

### Add ScreenShots

![Capture](https://github.com/mdazfar2/HelpOps-Hub/assets/129590267/84ca438d-03f0-46bf-ba1c-83f1636c7a60)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@TheNikhilRaj You are assigned

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj You are assigned
> 
> * Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
> * Please try to add comments about where and what type of changes you made.
> * Please don't add unnecessary code if there is no need! Thanks :)

yes, i have raise the PR now you can check it!
@mdazfar2

**Comment by TheNikhilRaj** [comment]
@mdazfar2  My points not added yet of this PR?

**Comment by mdazfar2** [comment]
@TheNikhilRaj I'm just closing your issue, not your PR. If I merge your pull request, you will get points on GSSOC. Hope you understand and have read the GSSOC guidelines.

**Comment by TheNikhilRaj** [comment]
@mdazfar2 Why? but i have done my work.
