### ISSUE TITLE
Feat: Open Commit History of User on Clicking the Contributions

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#620]
### Describe the feature

**Descripiton:**

Clicking on the contributions text of a `user` should open their commit history on helpops website. This feature is essential to show the users contribution history in the Helpops community

### Add ScreenShots

![Screenshot (68)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/278dc70b-dee0-4074-b6d1-cee07d69ca27)

![Screenshot (69)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/49004b19-200d-4617-b5fa-fa7fe915e4be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 Kindly Assign 

Thanks

**Comment by mdazfar2** [comment]
@shreyash3087 go ahead and also add hover effect

**Comment by shreyash3087** [comment]
@mdazfar2 any changes?

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/557ae8bf-d27a-419d-83fd-1129857a8182

**Comment by mdazfar2** [comment]
@shreyash3087 that's great create PR of it
