### ISSUE TITLE
Feat: Add hover effects on start now button in Expert DevOps Insights section 

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#622]
### Describe the feature

I will make that button more attractive with add hover effects.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/7d707e60-be32-422a-bd4d-d6a06e42b9be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @zalabhavy I have been seeing that you are raising issues again and again. Why don't you describe all the bugs in a single issue? This is not the right way to work on open source.
