### ISSUE TITLE
Feat: After submit contact form message shown under div is not attractive 

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#623]
### Describe the feature

I will give that message green color that show success to send message also give font size and make font bold.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/95c1f079-ef3e-499d-8f13-63a388f19eda)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/6901408c-71e6-41dc-b94b-1cfa0125f1ef)
 Here some margin-bottom need after message 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy assigned 

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)
