### ISSUE TITLE
Feat: In team section in first four card add scale to image so on hover that will also looks attractive

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#624]
### Describe the feature

Add scale on profile image so hover that also scale up image and looks more attractive when hover on cards.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/d3a598ce-2526-4a14-9070-6b97b991d9df)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy I cannot understand what exactly you want.

**Comment by zalabhavy** [comment]
@mdazfar2 also add hover effects on profile image when we hover on card profile picture becomes some bigger.

**Comment by mdazfar2** [comment]
@zalabhavy I think that does not look as good.

**Comment by zalabhavy** [comment]
@mdazfar2 Ok no problem !
