### ISSUE TITLE
Feat:Redesigning the contact us page using tailwind css

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#627]
### Describe the feature

like the image is small and fields are not styled

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/6b9e04aa-4471-4caf-aec1-f5d0324503e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 should we use tailwind? if yes, then we can convert the whole website to use tailwindcss

**Comment by RamakrushnaBiswal** [comment]
solved #640
