### ISSUE TITLE
BUG:Making the Whole Landing Page Responsive

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the Landing Page of Helpops Website lacks Responsiveness for Mobile Devices.The page should be compatible with all the devices, as it is the landing page,the entry point for all users on helpops-hub it should be a priority to make it responsive for all devices

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/abd42251-12f1-42f9-a500-c75ca134cfca

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 You are assigned.
- Keep in mind that the desktop view of the landing page should not be affected.
