### ISSUE TITLE
Feat: I will add an about us page .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#63]
### Describe the feature

I will add a About us page so that user can get the abstract view of the website .

### Add ScreenShots

This helps the user to know or get details about the website .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 as of now, we think we don't need this, will let you know in future, if there is need
