### ISSUE TITLE
Feat: To add New darkmode button animation

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#636]
### Describe the feature

@mdazfar2 
Feature Request: New Dark Mode Animation
Description:
Add a smooth, visually appealing transition animation for toggling dark mode within the application. This feature aims to enhance the user experience by providing a seamless transition between light and dark themes.
take a look===>

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/a3f26506-d98d-46c4-9e5e-d14fe2d6a347

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 Issue acknowledged. Task assigned to you.
