### ISSUE TITLE
Change the color of floating Navbar

### ISSUE THREAD

**Issue by Utsavladia** [mdazfar2/HelpOps-Hub#638]
### Describe the feature

The Floating navbar color should be change to make it more attractive...

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/75129c9b-e6b2-4586-ac75-52d5c4ece0e7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Utsavladia you are assigned.

**Comment by Utsavladia** [comment]
@mdazfar2 

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/d474855f-a5a9-401b-ad5b-538ed6038193)

Is this fine? or want some adjustments?

**Comment by mdazfar2** [comment]
@Utsavladia update this in floating navbar only not stable navbaar

**Comment by mdazfar2** [comment]
@Utsavladia you may have made some changes in `Dark Mode`. Dark mode is not working properly. Please check it out.

**Comment by Utsavladia** [comment]
@mdazfar2 
I checked carefully all files chagnes i made in the last merge there is nothing related to dark mode that i changed... Kindly check others merge if that is related

**Comment by Utsavladia** [comment]
> @Utsavladia update this in floating navbar only not stable navbaar

We have only one Navbar we got the same functionality with the old navbar only...
So I thinks its easy to manage too

**Comment by mdazfar2** [comment]
Well, @Utsavladia, I shouldn't say it like that. Please close this issue for now. We will let you know in the future if there is any requirement for that. :)

**Comment by Utsavladia** [comment]
@mdazfar2 
ok no issues..
did you find the dark mode problem..

**Comment by mdazfar2** [comment]
@Utsavladia it is solved
