### ISSUE TITLE
Feat: Fixing the Resources header and adding Sort & Filter

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#641]
### Describe the feature

Currently, the header of Resources page of our site has components overlapping each other, also it lacks a Sort & Filter option for sorting the contents in a proper order.

### Add ScreenShots

![Nav](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/ffd5adf0-4c88-42c5-bab2-6e0a1be7e493)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 you are assigned.
