### ISSUE TITLE
Feat: Make the Team page responsive

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#642]
### Describe the feature

Currently, our Team page is not responsive for smaller screens, I would like to make this responsive

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/03d8b2f3-607b-49dd-a85c-84e9ab8edc88

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 go ahead
