### ISSUE TITLE
Feat:change the hovering colour of the navbar items and social icons in dark mode to the colour of theme of project 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in dark mode the hoverring colour over the social icons and navbar items is white . 
want to do it like this 

![WhatsApp Image 2024-06-24 at 22 14 30_129d7bf1](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/cbcc69a5-7a67-47ae-8fe0-abf9d79aaef1)
![WhatsApp Image 2024-06-24 at 22 17 35_27e27b1e](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/01484059-d4a1-44e6-b116-5568ad878f7e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@ANKeshri Which type of color do you want to change in dark mode?

**Comment by ANKeshri** [comment]
> @ANKeshri Which type of color do you want to change in dark mode?

as it was earlier see i have provided image

**Comment by mdazfar2** [comment]
@ANKeshri it would be great if you show me the difference b/w both as deployed website.

**Comment by ANKeshri** [comment]
current it is like this white hover is coming in night mode .
https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/ceada8d3-2ce3-497c-a0bf-ad8ce3178833

earlier it was like this 
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/70347018-e487-4c84-9f05-72398777c3b8)
and same in social icons also it was orange in colour .

**Comment by ANKeshri** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/93e2e98c-87f0-4fe5-8329-85e8eb4e5b43

@mdazfar2 i am saying like this

**Comment by mdazfar2** [comment]
@ANKeshri go ahead

**Comment by ANKeshri** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/54de6f49-6c38-45cc-9b67-feb3b9cad34a)

is it looking better than \

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/47e5f578-8a90-400c-ba8f-6be81df7bd02)

**Comment by mdazfar2** [comment]
Create PR @ANKeshri That's look great
