### ISSUE TITLE
Feat: Make one button type div under that mode change button present.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#647]
### Describe the feature

i want to make one div under that put change mode button.
so it will looks better.
as we can see sponsor button looks good i will create button like that and in that i will set mode change button.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy please elaborate it and also share some screenshot or demo video which i can understand easily what do you want contributing to HelpOps-Hub?

**Comment by zalabhavy** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/62718d1d-4418-4e59-84f6-50ad8567ab9d)
 
@mdazfar2 Here you can see outer round  yellow part that i want to create so it mode changer looks good.

**Comment by zalabhavy** [comment]
@mdazfar2 I will add another color that matches the theme of website ! i am think to add white like sponsor button and when we hover it becomes orange like sponsor button !

**Comment by mdazfar2** [comment]
@zalabhavy yes you are assigned for that but i have a great idea about sponsor emoji can we use this type if heart as see in the below screenshot-

<br>

![Screenshot_2024_0625_190446.jpg](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/135d6162-92a4-46d9-b2a6-02fa36a93033)

**Comment by zalabhavy** [comment]
@mdazfar2 yes sure , if you want this type of heart I will add that in sponsor button.

**Comment by mdazfar2** [comment]
Okay @zalabhavy 

- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need!
