### ISSUE TITLE
Feat: Changing background color of contact us card in dark mode

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#648]
### Describe the feature

We can change the color of contact us card in dark mode for better UI .

### Add ScreenShots

Before:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/5255f84f-1312-4922-aaaf-01a45f663b9e)

After:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/5913cad8-0df2-4ad7-8d8f-7d6708b591e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 I want to work on this , please assign it to me

**Comment by mdazfar2** [comment]
@Maana-Ajmera I think full black isn't look good
