### ISSUE TITLE
BUG: Commit history of top 3 contributors is not linked

### ISSUE THREAD

**Issue by Maana-Ajmera** [mdazfar2/HelpOps-Hub#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Commit history of all contributors have been linked but that of top 3 contributors is not linked, I would add link to commit history of top 3 contributors

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/9bea5347-d377-4f31-90a7-5fc32de19e04

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@mdazfar2 I want to work on this , please assign it to me

**Comment by mdazfar2** [comment]
@Maana-Ajmera As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
