### ISSUE TITLE
Feat: change the hovering colour in both mode of resources cards 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#652]
### Describe the feature

in light mode the hover is orange which is not looking good and in dark mode also not looking good .

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9e3b9d24-b7b9-4453-8c3c-a5417f250ec5

in light mode i will make black and in dark mode orange .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign me this issue i am working on it .

**Comment by ANKeshri** [comment]
light mode 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/1248fb95-7945-411b-a0fd-a9ee902fbade

dark 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/2a5038d6-ac14-4fbc-b604-2137a5156145

@mdazfar2 is both ok should i create pr ?

**Comment by mdazfar2** [comment]
@ANKeshri yes nice I like that

**Comment by ANKeshri** [comment]
@mdazfar2 can i raise a isse for making similar hovering effect on below shown items . 


https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/030b40a6-62f9-4066-9b90-e3c90bb618ea

**Comment by ANKeshri** [comment]
> @mdazfar2 can i raise a isse for making similar hovering effect LIKE ON nav bar items on below shown items .
> 
>  Recording.2024-06-26.095909.mp4

@mdazfar2 should i work on it

**Comment by mdazfar2** [comment]
@ANKeshri sure
