### ISSUE TITLE
BUG: The background color of pages is not changing correctly 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When going to any page and reloading it is not changing its background color according the dark mode 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/6c14dc86-ef16-4880-8eb4-daae6bc58bc8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Issue acknowledged! you are assigned.
- Don't forget to add comment which and what type of place you are change or add
