### ISSUE TITLE
BUG: Fix hover underline effect in resource pages in webiste3.0

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/9f6ee969-b742-4709-8c4e-122625382aa9)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/d12109fc-2171-4457-a2b2-2384c1b42176)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/66dd7922-0080-4a31-b688-c57a6370ccd7)

Hovering effect of the navbar in the resources page adds a white underline also disturbing the ui of the website.
Also fix the background color from white to the theme color and router **/abouts** to **/about**
 
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes you are assigned
