### ISSUE TITLE
BUG: "Alignment Issues with Website Header - Need Enhancements"

### ISSUE THREAD

**Issue by Saksham2k3s** [mdazfar2/HelpOps-Hub#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The header of the website has several alignment issues, which negatively impact the overall user experience. The elements within the header are not properly aligned, causing a disorganized appearance. Additionally, there are areas within the header that need enhancements for better functionality and design.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [ ] I want to work on this issue

**Comment by mdazfar2** [comment]
@Saksham2k3s It is not the correct way to work on open source. I have noticed that you raise issues again and again. Why don't you create one issue and define every problem in it?
