### ISSUE TITLE
BUG: "Incorporate Sponsor Button and Dark/Light Toggle Button into Header"

### ISSUE THREAD

**Issue by Saksham2k3s** [mdazfar2/HelpOps-Hub#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The current layout of the website does not include the Sponsor button and the Dark/Light toggle button within the header. Additionally, their alignment is not perfect, affecting the overall aesthetics and usability of the site. Incorporating these buttons into the header and fixing their alignment would enhance accessibility and improve the user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Saksham2k3s It would be great if you share some screenshot or any relevant video about your issue.

**Comment by Saksham2k3s** [comment]
![header](https://github.com/mdazfar2/HelpOps-Hub/assets/129402285/54fd9492-48bd-41d0-ac6b-585014dcd6b6)
The login/signup button, sponsor button, and dark/light mode toggle are not properly aligned.

**Comment by mdazfar2** [comment]
@Saksham2k3s It is aligned! Thanks

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/f1c9cec1-41c6-4e5d-b141-4eeaefe38683)
