### ISSUE TITLE
Feat: Enhancement of Contact Us Page for Improved User Experience

### ISSUE THREAD

**Issue by Saksham2k3s** [mdazfar2/HelpOps-Hub#662]
### Describe the feature

For the issue titled "Enhancement of Contact Us Page for Improved User Experience," you should categorize it under "Enhancement" or "Feature Request." These categories typically focus on improving existing functionality or adding new features to enhance user satisfaction and usability. Here’s how you can frame it:

### Add ScreenShots

![contact-from](https://github.com/mdazfar2/HelpOps-Hub/assets/129402285/06ad4120-25bb-42a8-80f1-48139289623b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Saksham2k3s, can you highlight with a red square box? I cannot understand which enhancement you are talking about. Is it the navbar or the form? Please send a screenshot with a red highlight box.

**Comment by Saksham2k3s** [comment]
Hi @mdazfar2,
I'm talking about the contact form.
