### ISSUE TITLE
Feat: Reduce the extra gaps 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#663]
### Describe the feature

I want to reduce the extra gaps from the Main cards of the Teams page 

### Add ScreenShots

![WhatsApp Image 2024-06-26 at 17 19 53_12573f8d](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/298efe96-3e6c-4981-b719-f5121952d00b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
