### ISSUE TITLE
Feat: adding similar hovering effect on items of drop down list as it is in nav bar items 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#664]
### Describe the feature

i will be adding hovering effect on buttons of drop down list just as the hovering effect present in nav bar items .

### Add ScreenShots

as we hover there is nothing happening .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9fcabfbb-4d6c-46b1-93d6-d6cc201e87ae

i wil add hovering effect like shown below .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/0a94b50d-3649-4b4b-afac-ce2319462800

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign me this issue under gssoc labels

**Comment by mdazfar2** [comment]
@ANKeshri You are assigned.
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

**Comment by ANKeshri** [comment]
@mdazfar2 as shown in the video i want to add similar hovering effect to the team card and also contributor card as the hovering is present in resources in both mode . 
If you want please let me know . thank you

**Comment by ANKeshri** [comment]
@mdazfar2 should i work on that
