### ISSUE TITLE
Feat: Adding Kubernetes Commands Cheat Sheet

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [mdazfar2/HelpOps-Hub#67]
### Describe the feature

The new feature aims to add a Kubernetes cheat sheet to the Repo. This cheat sheet will provide users with a quick reference guide for essential Kubernetes commands and operations, facilitating easier management of Kubernetes clusters and resources.

### Add ScreenShots

I will create new folder called `Kubernetes Cheat Sheet`, and will add into it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Santhosh-Siddhardha Go ahead 

- Create folder `Kubernetes Commands Cheat Sheet`
- You have to create `README.md` file inside `Kubernetes Commands Cheat Sheet` directory & whole documentation of k8s cheat sheet
- Try to write each and every command related to K8s with explanation; Please do not miss a single command.
- A few years ago, I made a repository of k8s, which includes all the important commands for K8s. You can check it out [here](https://github.com/mdazfar2/kubernetes-conc/blob/main/README.md).

**Comment by mdazfar2** [comment]
@Santhosh-Siddhardha, also try to update with emojis according to their use cases because it looks impressive to the user interface. Keep the documentation simple; you're not writing a college assignment. 😑

- The documentation you have created will help many people 🚀
