### ISSUE TITLE
Feat: hover effect of the cards on team page as per the theme of the project 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#674]
### Describe the feature

i will add hovering effect on the cards of the team page in both the mode as per the theme of the project  as shown below .

### Add ScreenShots

BEFORE : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/d965ca79-5a46-44ba-85d5-c92448ca7288

I want to make it like this 

- in dark : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/e06f6b06-141a-42e8-9b65-87b4fcdba129

- in light 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/6dbe7e44-ca54-4e70-bc1f-781c099243a3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please review it and assign me this issue I want to work on it

**Comment by mdazfar2** [comment]
hey @ANKeshri As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
