### ISSUE TITLE
Feat: Adding a notification on submit

### ISSUE THREAD

**Issue by DevGajjar28** [mdazfar2/HelpOps-Hub#675]
### Describe the feature

Add pop-up notification on submission on form

### Add ScreenShots

![Screenshot 2024-06-18 225618](https://github.com/mdazfar2/HelpOps-Hub/assets/145287513/acf0f662-dad5-47f3-8077-37a042221c21)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@DevGajjar28 what world you write in its place?

**Comment by DevGajjar28** [comment]
> @DevGajjar28 what world you write in its place?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/145287513/5740459f-890e-4fd0-b056-3d8243c438d4)
i would like to show like this

**Comment by DevGajjar28** [comment]
pop up notification show 1 or 2 seconds after automatic disappear and also close button to remove.

**Comment by mdazfar2** [comment]
@DevGajjar28 Yes that is correct but what will you write in the pop up notification?

**Comment by DevGajjar28** [comment]
> @DevGajjar28 Yes that is correct but what will you write in the pop up notification?

so for that i am gonna use toastify , it's<ToastContainer
position="top-right"
autoClose={5000}
hideProgressBar={false}
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light"
transition: Bounce,
/>
<ToastContainer />

toast('Message sent !', {
position: "top-right",
autoClose: 5000,
hideProgressBar: false,
closeOnClick: true,
pauseOnHover: true,
draggable: true,
progress: undefined,
theme: "light",
transition: Bounce,
});

writing this code on contact us page
