### ISSUE TITLE
BUG: Making Whole Teams Page Responsive

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the teams page for helpops-hub website isnt responsive,which impacts the user experience for mobile devices

**Steps to Reproduce:**

- Go to helpops-hub
- Open Teams Section
- Reduce Screen Width
- Notice the Incorrect Responsiveness

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/f15758b0-fa32-4dfc-af7d-7678ac7f9c84

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 Well. It would be great if you do the `Top 3 Contributor` like this

<br>


https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/9c89d70e-2376-4c6f-aa34-121f2f2e7d46
