### ISSUE TITLE
Feat: Making the Contact Us Form Work

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#678]
### Describe the feature

Currently the Contact Us Form Doesnt Work,The data entered doesnt get stored anywhere.
Since We have setup mongodb for the website now,we can integrate the contact form with mongodb so that the data entered in the contact form gets stored in mongodb.

**Benefits:**

The Owner gets the responses from the contact form in his mongodb atlas account,from where he can then send mails to the user regarding his contact form.
Suppose I want to give feedback about the website,i go to contact form type in my details and in comments i type in my feedback message,if the data is stored in mongodb,the owner can see the form data,and contact me back.

### Add ScreenShots

![Screenshot (221)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/7e6c9522-94a2-4762-98c6-20477fcf45af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned
