### ISSUE TITLE
Feat: Add Signup & Login components UI

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#679]
### Describe the feature

Currently, our website was lacking a Login/Signup page.....So I would like to add the UI for both of these components with discussed effects

### Add ScreenShots

Proposed:

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/e7470f06-94a6-4a4c-bc2d-67215879dc3f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 you are assigned
