### ISSUE TITLE
Feat: Style to Scrollbar for better UI.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#68]
### Describe the feature

I want to add style to scrollbar that looks good and give better user experience.

I expect to add **level2** on this task because it takes time and try-error for fix style for scrollbar.

Thank you !

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/a991b343-2c60-4df6-803f-4e14ae39281b)
In this website default scrollbar is here i will styled it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy You are assigned

- Whenever you make changes to the files, please describe in the comment section what changes you are making.
