### ISSUE TITLE
Feat: Adjusting Login/Signup for making it compatible with Dark mode and making it responsive

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#681]
### Describe the feature

Currently, Login/Signup is not compatible with Dark mode and changes are to be made and we also have to make it responsive for smaller screens

### Add ScreenShots

![DM1](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/c01f4584-de19-45ad-b17c-6f193c62af03)
![DM2](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/51c4f368-5317-4948-bfc2-27893eb97ab4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 Issue acknowledged! You are going to be assigned.
