### ISSUE TITLE
BUG: Login/Singup button Radius not matches other two buttons.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I will fix that Login/Singup button Radius.

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/93a7cd3e-a451-40d5-b300-04c7e7679d0e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy go ahead
