### ISSUE TITLE
FEAT: hide and view password functionality 

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in light mode filter button is not visible and also orange hovering is not visible in light mode want to add black hovering as you can see in the video .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/2f0626de-417f-4a75-a3a3-0220feca7089

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@ANKeshri As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by ANKeshri** [comment]
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/f84138b0-0dd7-4717-a65a-1fcc8af2c4dd)
![Screenshot 2024-06-27 134716](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/450fc25f-3df8-4011-a628-791f6c636a66)
@mdazfar2 see things are not visible in dark mode

**Comment by mdazfar2** [comment]
@ANKeshri 
You have raised a duplicate issue; it was already raised by issue- #681. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by ANKeshri** [comment]
@mdazfar2 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/fdca4cd7-17e3-4e3f-8a5f-d14a41596564

do you want me to add this functionality to our login page . In all the website it is present . 

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/6ff9ea5d-e3db-4a09-9b00-33246ac1513f)

**Comment by mdazfar2** [comment]
@ANKeshri you are assigned for password `visible or not option` and thanks for addressing, we are not thinking about it :)

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/37fcd0f8-7e46-4c20-ac49-a3b20b4fa328)

**Comment by mdazfar2** [comment]
@ANKeshri You are assigned for `password visible or not` option still we are not about it but you are addressing us thanks :)

- and also add forget password option

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/7a740114-ceff-4b3a-b811-90fc8f2f11a8)

**Comment by mdazfar2** [comment]
Hey @ANKeshri, please confirm if you are working on the issue I assigned to you, or should I assign it to someone else?

**Comment by ANKeshri** [comment]
> Hey @ANKeshri, please confirm if you are working on the issue I assigned to you, or should I assign it to someone else?

i am working n it

**Comment by ANKeshri** [comment]
@mdazfar2 within 1 hour i will do

**Comment by ANKeshri** [comment]
https://github.com/mdazfar2/HelpOps-Hub/asse@mdazfar2159682348/aaba0030-1fe9-4b86-ae36-5e65c80b5422

@mdazfar2 this is a bug

**Comment by mdazfar2** [comment]
@ANKeshri create new issue for this I'll assigning you
