### ISSUE TITLE
Feat: Add Comprehensive Documentation for Monitoring and Logging

### ISSUE THREAD

**Issue by arunimaChintu** [mdazfar2/HelpOps-Hub#687]
### Describe the feature

adds comprehensive documentation for the Monitoring and Logging section of HelpOps-Hub. It includes guides on setting up and using Prometheus, Grafana, ELK Stack, and Graylog, along with best practices for effective monitoring and logging. This enhancement aims to assist DevOps professionals in maintaining application health, optimizing performance, and ensuring robust security.

### Add ScreenShots

<img width="600" alt="Screenshot 2024-06-27 at 1 12 33 PM" src="https://github.com/mdazfar2/HelpOps-Hub/assets/99474881/f55e8ac2-e9b1-4109-ad61-dfd8306f7291">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by arunimaChintu** [comment]
@mdazfar2  Please assign me this issue

**Comment by mdazfar2** [comment]
@arunimaChintu, why are you raising the same issue again and again? Sorry, I have to close this one as well. Now you have only one open issue that you must complete. :)
