### ISSUE TITLE
Feat: Configuring the newsletter for its proper functioning

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#688]
## Description
I've noticed that the newsletter component is not implemented correctly like it doesn't showing any pop up on submitting and email , not consist of any validation . 
The design of the search bar is not looking so cool so i will enhance that as well
So it needs that when user click on submit so a popup will be shown with some kind of message telling about the error or submission .
Currently On submitting it is showing alert message that doesn't looking good 
And also when someone click on submit so the processing is happening in the backend so user doesn't know is anything happening or not 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/f50954fd-b882-4b5e-98c7-955ff3e76ab6

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/fd2405ea-63c0-45df-806c-8550c362df8a

## Issue Details:
- 🖥️ Current State: The website's newsletter is not well implemented 
- 📱 Proposed Solution: Implement a newsletter correctly with all validations

***I would be happy to work on this enhancement to ensure the HelpOps-Hub website offers an excellent experience for all users, regardless of the device they are using.***

Looking forward to your feedback and the opportunity to contribute! 😊

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/f50954fd-b882-4b5e-98c7-955ff3e76ab6

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/fd2405ea-63c0-45df-806c-8550c362df8a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Amruta7203** [comment]
@mdazfar2 Pls assign this issue to me since it's open from 2 weeks and no action is being taken yet..

**Comment by mdazfar2** [comment]
hey @Amruta7203 now it is functioning fine please check from your side on homepage newsletter.
