### ISSUE TITLE
Add Content on Version Control (GitHub, GitLab, or Bitbucket)

### ISSUE THREAD

**Issue by Shouryabhardwajj** [mdazfar2/HelpOps-Hub#69]
Description
Version control helps by:
•Tracking changes
•Enabling collaboration
•Providing backup and recovery
•Supporting experimentation
•Offering traceability
•Facilitating deployment
•Enhancing code review

@mdazfar2  Please assign me this issue

**Comment by mdazfar2** [comment]
@Shouryabhardwajj Please write everything related to `GitHub`, `GitLab`, and `Bitbucket` with hands-on practices. Try to cover topics like `GitHub Actions`, `GitHub runners`, `SSH keys`, and much more.

- I will add your name in the contribution section of our Official website if you create a full documentation about it.

- you are assigned ✔️

**Comment by Shouryabhardwajj** [comment]
@mdazfar2 can you reopen this issue please

**Comment by mdazfar2** [comment]
Sorry It's already solved @Shouryabhardwajj
