### ISSUE TITLE
Feat: CI/CD Pipelines: Automating Software Delivery

### ISSUE THREAD

**Issue by arunimaChintu** [mdazfar2/HelpOps-Hub#693]
### Describe the feature

CI/CD Pipelines: Automating Software Delivery

### Add ScreenShots

![Uploading Screenshot 2024-06-27 at 1.12.33 PM.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@arunimaChintu I have been observing for some time. You are raising issues again and again. That's not a good way to work on open source. Why don't you raise and describe everything in a single issue?
