### ISSUE TITLE
BUG: Fix login/signup 'X' button area

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/4ea26f90-709e-46b1-8525-7d8e0369836b)

The area (width) for 'X' button on login signup page is too big allowing user to click on the 'X' the area outside 'X' as well. I want to imporve this by correcting its css to make it perfectly fit to the size.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes, the user can also close it by tapping outside the square area as well as by clicking on the cross button, so I think there is no need for a change. Could you please close this issue?

**Comment by vansh-codes** [comment]
> @vansh-codes, the user can also close it by tapping outside the square area as well as by clicking on the cross button, so I think there is no need for a change. Could you please close this issue?

@mdazfar2 
It's not good if we think of the UX because in the extra area the cursor becomes pointer which makes the user click and eventually close the login popup even when not wanted to close. Still if you think thats really not needed then okay I will close the issue let me know.

**Comment by mdazfar2** [comment]
@vansh-codes  As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
