### ISSUE TITLE
BUG: Navbar Responsiveness and Hamburger Bug

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

The Navbar On the Helpops Website isn't responsive and have bugs in the Hamburger Menu.

**Steps to Reproduce:**

- Go to Helpops website
- Reduce the screen width
- Notice the incorrect responsiveness
- Open Hamburger Menu
- Notice the Hamburger Bug

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/8145e4bd-b887-4f2a-bcad-42cf44a58bee

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned
