### ISSUE TITLE
Feat:Adding Mode options dark mode and light mode

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#70]
### Describe the feature

I want to make mode button that toggles mode.
There will be 2 type of mode dark mode and light mode.
It give better user experience.
I expect **level2 or level3** as per your wish i will use html , css and js for create this.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/947da108-910e-4fc5-82cb-ba58dac16294)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy, someone is already working on it.

**Comment by zalabhavy** [comment]
@mdazfar2 Ok. can you assign me issue #68 ?

**Comment by mdazfar2** [comment]
> @mdazfar2 Ok. can you assign me issue #68 ?

Let me check
