### ISSUE TITLE
Feat: Changing the loader and improvement of input field

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#703]
### Objective
Changing the loader and placing it inside the subscribe button .

### Use Case
It will make the website more attractive  and looks amaing

### Add ScreenShots

![Screenshot 2024-06-28 000407](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/bd16cd06-34d2-46f3-b036-3e9ace931e17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
