### ISSUE TITLE
Feat: Make Otp and Profile page compatible to dark mode and add responsiveness

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#707]
### Describe the feature

Currently, the `OTP` and `Profile` pages lacks the responsiveness and compatibility with dark mode....I would like to fix these things

### Add ScreenShots

![Screenshot (79)](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/09c990f0-2dee-492e-aa77-6447aa324992)
![Screenshot (80)](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/73f9282e-4771-4835-ad96-1d25394efe98)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 you are assigned
