### ISSUE TITLE
Feat: Enhance the Newsletter template and fix link positions

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#708]
### Describe the feature

Would fix the ui of the newsletter template and make it more attractive.

### Add ScreenShots

**NOW**
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/c8dba60a-9601-4762-8a2e-0a1bce7d5660)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes you are assigned
