### ISSUE TITLE
Feat: Adding a page scroll UP icon

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#709]
### Describe the feature

i would like to add a scroll up icon on home page

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhairyagothi Please share some demo video or screenshot if you worked before

**Comment by dhairyagothi** [comment]
updates @mdazfar2

**Comment by mdazfar2** [comment]
hey @dhairyagothi I apologize, but I need to close this pull request for now. Please don't be discouraged! can we work on another issue :)
