### ISSUE TITLE
Feat: Make Navbar buttons scale effects like Star us and Get Started it looks good

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#710]
### Describe the feature

I want in Navbar section when we hover that transformation is left to right not looks good i will add scale effects like star us and get start so when we hover on that it looks some bigger like star us and get start button 

On hover background will same only scale effect i want to change.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/54785549-6a8d-4455-a47e-fbcf99c88ba1)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/4a08cf2f-d018-4877-9630-282d8dbc1ee7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Can you please assign me this task ?

**Comment by mdazfar2** [comment]
@zalabhavy, which type of effect do you want to add to the `Star US` and `Get started` buttons? Could you share a demo video?
- I think we don't need to change the effect on the `login/signup`, `sponsor`, and `dark mode` buttons. We need some attractive effect on the `Star US` and `Get started` buttons only.

**Comment by zalabhavy** [comment]
@mdazfar2 here are some options to make Star Us and Get started buttons attractive
https://www.loom.com/share/45a269896fd143acaa0231f119f553dd

**For Star Us Button**
https://www.loom.com/share/5855f867a10a4aac9848915cc62e7a6a

**For Get Start Button**
https://www.loom.com/share/83d8c0824be7497999b32d8e48037c3b

**Comment by mdazfar2** [comment]
@zalabhavy After hovering over the `Get Started` button, the hover should show an arrow. I like that. Add this to the `Get Started` button so that when you click on it, the arrow should be visible, and only this in `Get Started`.

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/da303f2e-f31f-4702-b032-161cb1a54b8b)

**Comment by zalabhavy** [comment]
@mdazfar2  Ok i will do that.
