### ISSUE TITLE
BUG: In team main 4 cards social icons hover effects overlapping

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/a2a09bf4-7ca5-4a8f-9048-4f776c578d36)

**I will give it proper margin from left and right and make it perfect.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy, issue acknowledged! You are going to be assigned.
