### ISSUE TITLE
BUG: Database can be accessed when API endpoint is hit through Postman 

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

The Database of helpops hub can be currently accessed if a user hits the api endpoint of helpops hub through postman,this allows unauthorised access of helpopshub database to the user.

**Expected Result:**

Any User should not have any access to the Helpops hub database,this maintains security of other users personal information on the helpops hub website.

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/2a1fae99-97d0-4a42-b6b9-17f6113ce7b5

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 kindly assign

**Comment by mdazfar2** [comment]
- Go ahead @shreyash3087
