### ISSUE TITLE
Feat: Adding Proper validations to the form 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#721]
### Describe the feature

I saw on signin it is also taking invalid emails and also password do i want to fix it 
I will add a proper validation for the email with pop up so that on entering the wrong email it will show us a popup with proper validation

### For Password
I will add min 8 length , 1 uppercase , 1 lowercase , 1 number and 1 special charachter validation

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/37cd50c4-c44d-4ec1-bb65-aaa2026b9b0c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211, go ahead! Try to add validation in such a way that it looks like on any professional website.
