### ISSUE TITLE
BUG: Add proper msg popup in newsletter

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When the user already have subscribed and then again if user tries to subscribe then user doesn't gets proper message. To tell user know that he is already subscribed and shouldn't subscribe again this feature is needed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes you are assigned
