### ISSUE TITLE
Feat: UI enhancement in the newsletter component

### ISSUE THREAD

**Issue by alpharsh** [mdazfar2/HelpOps-Hub#726]
### Describe the feature

UI look will be enhanced with more visually appealing 

### Add ScreenShots

![Screenshot 2024-06-28 201825](https://github.com/mdazfar2/HelpOps-Hub/assets/108024082/b2e166bd-2082-460c-9598-083f9bc554f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@alpharsh, how can you enhance our newsletter? If you share a demo video or any relevant screenshots, it would be great for me to assign this to you.

**Comment by alpharsh** [comment]
![Screenshot 2024-06-28 215754](https://github.com/mdazfar2/HelpOps-Hub/assets/108024082/08321a39-4806-472c-96c5-084e20f1ed76)
something like this as in this the newsletter is standing out so which is better for CTA

**Comment by mdazfar2** [comment]
@alpharsh Actually our newsletter's UI was like this so we changed it. Please close this issue if you have any other please try to raise different issue
