### ISSUE TITLE
Feat: Enhancement of User Interface in Contact Form

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#728]
### Describe the feature

The user interface of the contact form can be enhanced by adding loading animations and button effects to improve the overall user experience.

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/94c1fe4b-ff59-4097-9bfb-676694c60637

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned. Add the same hover effect on `login/signup` all pages
