### ISSUE TITLE
BUG:new here / sign up now button when screen size is reduced

### ISSUE THREAD

**Issue by ANKeshri** [mdazfar2/HelpOps-Hub#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when screen size is reduced then new here/ sign up now is not in position

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/4c8b4c39-8920-4706-969b-3c916d6a3e80

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@mdazfar2 please assign me

**Comment by mdazfar2** [comment]
@ANKeshri go ahead
