### ISSUE TITLE
Feat: Enable key event for submission in login/signup, contact us and subscribe newsletter 

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#737]
### Describe the feature

Currently,  the "Enter" key on our keyboard does not work when you enter your email ID and want to continue, clicking the "Enter" button on our keyboard doesn't work, for login/signup subscribe button and contact us too. I wish to add this key event

### Add ScreenShots

![sample](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/fd2cd741-e653-4883-a39e-ea7d9f147b47)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 go ahead
