### ISSUE TITLE
Feat:Forgot Password Functionality

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#738]
### Describe the feature

in this if user forgots his password he can reset it .what we can do is we can send him a mail which will consist of reset link and that reset link will take him to the page where he can reset password

### Add ScreenShots

no ss required

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 can you do it with full functionality?

**Comment by mdazfar2** [comment]
Hey @nishant0708 Actually our work is going on in the login signup, I will let you know after it is completed, then you can work on the forget one. Is it ok for you?

**Comment by nishant0708** [comment]
Uhh okay no issues even if you need help with signin signup page as well you can let me know

**Comment by mdazfar2** [comment]
> Uhh okay no issues even if you need help with signin signup page as well you can let me know

<br>

@nishant0708  Ooh thanks! It would be great if you could join our [Discord server](https://discord.gg/UWTrRhqywt) for easier communication.

**Comment by nishant0708** [comment]
hey @mdazfar2 can i start working on it now?

**Comment by mdazfar2** [comment]
@nishant0708 You did not reply anything, so now Ayushmann is doing this work of forgotten password, thank you!

**Comment by nishant0708** [comment]
Hey @mdazfar2  i replied on every message ..you told me that login and signup module is in development and  after that you will let me know .so I kinda don't get it which message are you talking about

**Comment by mdazfar2** [comment]
@nishant0708 I thought that after completing the login/signup, I would discuss it with you on Discord. But you didn't join Discord or send any messages indicating that you joined or anything else where you would like to discuss. So, I think that you are not interested. By the way, sorry for the inconvenience. Can we work on another issue if you don't mind? And please don't be discouraged.

**Comment by nishant0708** [comment]
> @nishant0708 I thought that after completing the login/signup, I would discuss it with you on Discord. But you didn't join Discord or send any messages indicating that you joined or anything else where you would like to discuss. So, I think that you are not interested. By the way, sorry for the inconvenience. Can we work on another issue if you don't mind? And please don't be discouraged.

Yaa but still I don't get it I can't see any issues of ayushman related to forget password so how he got assigned .

**Comment by mdazfar2** [comment]
It's ok @nishant0708 if you don't use Discord, but you should have replied that you don't use Discord. We could have discussed it on LinkedIn or any platform.

- And regarding Ayushmann, we have already discussed the forgotten password on Discord. He will raise the issue after implementing it.

- It is not a good thing to see a message and leave. Please take care of it :)

**Comment by mdazfar2** [comment]
It's ok @nishant0708 if you don't use Discord, but you should have replied that you don't use Discord. We could have discussed it on LinkedIn or any platform.

- And regarding Ayushmann, we have already discussed the forgotten password on Discord. He will raise the issue after implementing it.

- I have no animosity towards you. You can raise another issue. I will be happy to assign you.

- It is not a good thing to see a message and leave. Please take care of it :)

**Comment by nishant0708** [comment]
Okay @mdazfar2 thanks for response I will take care of it from now
