### ISSUE TITLE
Feat: `.hamburger` close icon add

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#751]
### Describe the feature

- In this project `mobile` site  `nav-item` open to click the `.hamburger` this is only open icon not added the close icon.
- If i want to implement the close icon.
- please assign me.

### Add ScreenShots

[Screencast from 2024-06-30 09-33-32.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/9c3c8b17-aee7-4a7b-bac2-12b23eb19707)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sivaprasath2004 how did you implement this? If you share any demo video related to this, I can understand it very well, and it will be easy to assign this issue to you.

**Comment by sivaprasath2004** [comment]
[Screencast from 2024-06-30 16-43-34.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/2afd6005-294e-4ad0-9ff0-b63cf721010e)

**Comment by sivaprasath2004** [comment]
@mdazfar2 menu click the close `X` icon change

**Comment by mdazfar2** [comment]
@sivaprasath2004 
Thanks for your clarification! You are going to be assigned.
