### ISSUE TITLE
Feat: Want to add hover effect to all buttons 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#755]
### Describe the feature

I want to add the hover effect to all the buttons in the website 
Like for simple buttons i want to add a dark color when user hovers 
And for the login signup button i want to add grayish like color 

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/10c22881-0f09-47f9-a6f5-66cbd54f8b58

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead
