### ISSUE TITLE
Feat: Addition of Blog's Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#756]
### Describe the feature

**Description:**

We can add a blog's section in our website,in which the owner can write and post blogs on different topics related to devops or general technology.The users can read the blogs and gain valuable insights about various topics related to devops.

**Requested Additions:**

Addition of Blog's page template to have a base to work on the Blog's Page

### Add ScreenShots

![screencapture-localhost-3000-blogs-2024-06-30-16_41_33](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/c0f5979f-bd3c-4889-86d5-562d79945644)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 kindly assign

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned
