### ISSUE TITLE
Feat:Improving the drop down menu

### ISSUE THREAD

**Issue by YadlaMani** [mdazfar2/HelpOps-Hub#758]
### Describe the feature

I would like to improve the drop down in resources page the whole website is good but this one component feels out of place would like to improve it

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/133841094/f048ac45-11fd-4b6b-9d92-1ad563d09509)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@YadlaMani I don't know if you can improve it, but I'll still assign this to you. Hope you improve it very well. Improve it in a way that is easy for me to merge your PR.
