### ISSUE TITLE
Feat: Add Scroll to top button

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#762]
### Describe the feature

I will add scroll to top button in home , about and team page.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 This issue is created but not solved can i work no this ?

**Comment by mdazfar2** [comment]
hey @zalabhavy As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
