### ISSUE TITLE
Feat: Want to add Github provider with mongobd backend integration

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#763]
### Describe the feature

I want to add a Github Login / signup provider like google
Because many users may want to login with github
I will add this with proper integration with Mongodb database so that user will store in backend as well 

### Add ScreenShots

![Screenshot 2024-07-01 171746](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/280abdd8-bb55-4ec1-a48d-f32639db9019)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 aasigned
