### ISSUE TITLE
Feat: In contact page's image add hover effects

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#765]
### Describe the feature

I will add 3d hover effects on contact page's image.

https://www.loom.com/share/be8003c634474fd58b227a10425a2ffc

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/f5d5f9d3-bc4b-421a-88a4-a54d39cfd701)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Please assign me this task !

**Comment by mdazfar2** [comment]
hey @zalabhavy As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
