### ISSUE TITLE
Feat: Adding website visitors count section in the footer

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#770]
### Describe the feature

Adding website visitors count section in the footer

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/3df5e47e-bbf1-4488-bc7c-7a1113c0804a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. :)
