### ISSUE TITLE
BUG: Text cannot visible

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- In this project `.container1` sections `.header` text cannot visible , because `cards` can be hidding the text.

### ScreenShot

![Screenshot from 2024-07-02 09-12-01](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/a7b0529c-06a7-4e2e-b8f6-ca866ca497a2)

- please assign me...

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sivaprasath2004 It's well from my side

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/acae67a1-af12-4b6e-86e3-6a98662fbcbb)

**Comment by sivaprasath2004** [comment]
Hello @mdazfar2  Not perfect in my 2 computers.

![Screenshot from 2024-07-02 14-37-59](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/1eb35585-4a88-43f4-814e-eab17b1941c1)

**Comment by sivaprasath2004** [comment]
@mdazfar2  

- please assign me..

### Live video

[Screencast from 2024-07-02 21-35-33.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/d18c8c02-cf4e-4cfa-a3e8-437553f5d4f2)

**Comment by mdazfar2** [comment]
@ANKeshri @Asymtode712 @RamakrushnaBiswal @Ayushmaanagarwal1211 

- Can you guys share a screenshot of the 'We are creative' section from your Desktop just to confirm?

**Comment by RamakrushnaBiswal** [comment]
Hi @mdazfar2 it works perfectly no need any changes

**Comment by sivaprasath2004** [comment]
@RamakrushnaBiswal this is can Desktop screen size issue..

**Comment by RamakrushnaBiswal** [comment]
@sivaprasath2004 check your screen size wether it 100% or not ig

**Comment by sivaprasath2004** [comment]
Hello @RamakrushnaBiswal My screen size will be 100% .
I'm clearly explain and live video upload , why you can't assign me?

**Comment by Asymtode712** [comment]
@sivaprasath2004 

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/4ea58b25-05b8-4c5e-80bc-d183ec4490a1

Its working fine.....

**Comment by RamakrushnaBiswal** [comment]
@Asymtode712 yes 👍

**Comment by mdazfar2** [comment]
@sivaprasath2004 It is right there on everyone's screen, now tell me how do I assign it to you and even if I assign you, may create this further problem.


- Can you please close this issue and try to raise another issue, which I would be happy to assign to you :)

**Comment by sivaprasath2004** [comment]
[Screencast from 2024-07-02 21-35-33.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/d18c8c02-cf4e-4cfa-a3e8-437553f5d4f2)

- Please tell me , How i can prove that ...
- I am already added live site video , but you can't assign guys .. 
- It's ok, but there is something miss ...
- My suggestion please fix .. 
- Thank you for Discussing ...
@Asymtode712  @mdazfar2  @RamakrushnaBiswal

**Comment by Ayushmaanagarwal1211** [comment]
@sivaprasath2004  bro i think you are using mac

**Comment by RamakrushnaBiswal** [comment]
@Ayushmaanagarwal1211 it's Ubuntu

**Comment by Ayushmaanagarwal1211** [comment]
@RamakrushnaBiswal  that's why their is a difference between 100% of windows and ubuntu

**Comment by RamakrushnaBiswal** [comment]
Yes @Ayushmaanagarwal1211
