### ISSUE TITLE
BUG:Want to Fix Alignment of Eye Icon + Want to Signup Not Saying at same place on different Screen

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/cbf1bbc9-37de-4ab7-a64f-e2747b764392)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/79d92e58-fab8-4a2b-ad2d-4ae057dc45b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 go ahead

**Comment by nishant0708** [comment]
I will complete it by tomorrow morning thanks @mdazfar2
