### ISSUE TITLE
Feat: Forgot Password Functionality 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#773]
### Describe the feature

I want to  Make a feature for forgot password .
Like when user forgot the password so that user can reset the password after clickinn on the forgot password .
It will be very helpful for users 

### Add ScreenShots

![Screenshot 2024-07-02 130812](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/b3839b00-eb91-4f9e-a687-0c6751b81d6d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you are assigned
