### ISSUE TITLE
Project Proposal: How to deploy Websites using netlify

### ISSUE THREAD

**Issue by Saipradyumnagoud** [mdazfar2/HelpOps-Hub#775]
### Overview

Gives how to deploy website using netlfy

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this project proposal

**Comment by Saipradyumnagoud** [comment]
@mdazfar2 Please Assign me the issue

**Comment by mdazfar2** [comment]
Hi @Saipradyumnagoud,  I don't think this particular question is directly related to DevOps.  Would you mind raising a separate issue for a more DevOps-focused topic where your documentation can be most helpful?

**Comment by Saipradyumnagoud** [comment]
> Hi @Saipradyumnagoud, I don't think this particular question is directly related to DevOps. Would you mind raising a separate issue for a more DevOps-focused topic where your documentation can be most helpful?

i hope that this will also be helpful for hosting the website.
