### ISSUE TITLE
BUG: Removing the extra scroll bar

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/72c4002f-ff38-490d-86e2-62c3a2fa9ca1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @RamakrushnaBiswal, I was just about to mention this, but I see you've already raised an issue for it. Thank you so much

- You are assigned

**Comment by RamakrushnaBiswal** [comment]
solved via #806
