### ISSUE TITLE
Feat:Switch Login and Newsletter Email Setup from EmailJS to Nodemailer

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#780]
### Describe the feature

We currently use EmailJS for handling email functionalities in our project, including user login and newsletter subscriptions. While EmailJS has been a convenient solution, its free plan limits the number of emails we can send each month. To enable unlimited email transfers and gain more control over the email-sending process, we should switch to Nodemailer.

### Add ScreenShots

And Checked it works with multiple mail services as well
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/b4fdf43d-6646-4249-ae10-14c6923da7db)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/fb4bdd92-d23e-408a-b631-84905dbd0c24)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 you are assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

- And don't forget to ⭐ our repo

**Comment by vansh-codes** [comment]
@nishant0708 The newsletter feature is already done using nodemailer bro. Please dont make false claims
