### ISSUE TITLE
Feat:Shift Contact Page Setup from EmailJS to Nodemailer and Send Acknowledgment Mail

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#781]
### Describe the feature

We need to transition the current email handling on the Contact page from EmailJS to Nodemailer. This change is motivated by the need for unlimited mail transfers, which Nodemailer supports. Additionally, the new setup should include functionality to send an acknowledgment email to the person who submits the contact form.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 go ahead

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)
