### ISSUE TITLE
Feat:Encoding of api token fetch code

### ISSUE THREAD

**Issue by pandeyji711** [mdazfar2/HelpOps-Hub#784]
### Describe the feature

@mdazfar2 
### Please assign this task to me!

![Screenshot 2024-07-03 004929](https://github.com/mdazfar2/HelpOps-Hub/assets/154527778/831246ca-ce40-4647-8f71-df404cacc281)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@pandeyji711 you are assigned
