### ISSUE TITLE
Feat:Want to Organize Login-Signup file 

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#787]
### Describe the feature

Currently all the logic of login and signup lies in one file only i want to organize them so that it will be easier to understand code . And We can use Potential of Nextjs fully

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 go ahead
