### ISSUE TITLE
Feat: New Darkmode Toggle Button 

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#791]
### Describe the feature

The current dark mode toggle button is simple and lacks animations. Introducing a new dark mode toggle button with more animations and smooth transitions between dark and light mode would enhance the website's attractiveness and overall user experience.

### Add ScreenShots

**Current Design -** 

![Screenshot (257)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/5e331270-c019-43b9-b28a-bdc319b5ea58)
![Screenshot (256)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/6a932275-999f-468d-8fd5-144678e19ace)

**Proposed Design -** 

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/b55ceceb-b937-44f6-bc99-10022c47e1ea

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Go ahead
