### ISSUE TITLE
Feat: Make the Resource Details page responsive

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#796]
### Describe the feature

Currently, our Resource details page is not responsive for smaller screens, I want to fix this

### Add ScreenShots

![Responsive](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/7977e4a9-bc8a-4d9f-bfa0-513d55aea138)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 you are assigned.
