### ISSUE TITLE
Feat: Add Hovering Effect for Social Media Icons

### ISSUE THREAD

**Issue by thevijayshankersharma** [mdazfar2/HelpOps-Hub#80]
### Describe the feature

Enhance the user interface by adding a hover effect to the social media icons. When a user hovers over these icons, the effect will provide visual feedback, improving interactivity and user experience. The effect can include color changes, scaling, or subtle animations. This feature will make the icons more engaging and visually appealing, encouraging users to interact with them. Ensure the effect is smooth and consistent across all browsers and devices.

### Add ScreenShots

Once I get assigned I will send screen shot

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dark-S8uL** [comment]
@mdazfar2 I can efficiently add hover effect for social media icons. So, Please Assign this to me.

**Comment by mdazfar2** [comment]
as of now, we think we don't need this, will let you know in future, if there is need
