### ISSUE TITLE
BUG:In mobile screen newsletter subscribe button not in centre 

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![IMG_20240703_225429](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/264d1d80-c00b-4891-8d4a-e93aeebb8d30)

I will fix it in centre.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 please assign me this task.

Thank you !

**Comment by mdazfar2** [comment]
@zalabhavy Good issue found! you are assigned.
