### ISSUE TITLE
BUG: Fix github link of team member github link

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/571b2a18-d789-43dd-9d67-5c56543ef6e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes you are assigned
