### ISSUE TITLE
BUG: The background of contact form in dark mode is not looking good

### ISSUE THREAD

**Issue by JagjeetChauhan** [mdazfar2/HelpOps-Hub#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The background of contact form in dark mode is not looking good
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/98844703/27127806-8b8a-40c8-aef1-6f84b7116f42)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@JagjeetChauhan As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
