### ISSUE TITLE
BUG: Fix login/signup button hover color along with more minor ux updates

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/fc9140ae-cf50-4944-b785-c5a4a2cde09e)

The blue color of the login/signup page doesnt goes with the theme of the website. I will fix this along with more issues like:
- the text 'New here' should be a normal text instead of a anchor link to another route
- the 'forgot password' and 'sign up now' text should have some hover effects

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes go ahead
