### ISSUE TITLE
DOC:When User Signup Successfully want to add functional logout button on homepage

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#811]
### What's wrong with the existing documentation

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/f8378a75-52ad-45c7-b22b-5d49343293f4)
See No Logout button

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
Oo so you are making it right?

**Comment by Ayushmaanagarwal1211** [comment]
Yes bro

**Comment by nishant0708** [comment]
Uhh okay no issues closing this pr

**Comment by Ayushmaanagarwal1211** [comment]
@nishant0708 Thanks bro for understanding
