### ISSUE TITLE
Feat: Upgrade the Teams page UI and add Tailwind CSS

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#815]
### Describe the feature

Would like to upgrade the Teams Page UI by changing the theme and adding Tailwind CSS for its styling

### Add ScreenShots

![Team page](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/c2020b0d-8932-4fa9-976d-6f3fcdb7d3cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 you are assigned
