### ISSUE TITLE
Feat:Redesigning the About us page using tailwind css

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#820]
### Describe the feature

we use tailwind for styling using better icons and images

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/60cb5a8e-3581-4774-addf-917428c73cd8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal go ahead

**Comment by RamakrushnaBiswal** [comment]
Solved
