### ISSUE TITLE
Feat: Redesigning the contact us page using tailwind css

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#821]
### Describe the feature

.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/07650af2-d9b6-420d-a4ff-a90584acd9af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal you are assigned

**Comment by heli0707** [comment]
@mdazfar2 I really want to work on this can you assign it to me?

**Comment by mdazfar2** [comment]
Hi @heli0707, thanks for your enthusiasm!  Unfortunately, this issue is already assigned to RamakrushnaBiswal However, I'd be happy to assign you a different issue. Would you like to see our current list of unassigned issues?

**Comment by RamakrushnaBiswal** [comment]
solved #839
