### ISSUE TITLE
Feat: Want to redesign Create account and Create profile page using tailwind css 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#835]
### Describe the feature

I want to redesign these pages using tailwind css and want to change the design that will looks cool 
I want the background color of these pages as the combination of white and gray 

### Add ScreenShots

![Screenshot 2024-07-05 101615](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/f14c4300-2434-456f-8715-24c41414cfe6)
![Screenshot 2024-07-05 101558](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/c34ebcf2-ffa6-4260-b2ad-488a50ce9189)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 go ahead.
