### ISSUE TITLE
BUG:add footer

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

i can add footer where quick links and social media links added 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dark-S8uL** [comment]
@mdazfar2 I can contribute by adding footer with quick links and social media links to the website. Please Assign this to me.

**Comment by Dark-S8uL** [comment]
@mdazfar2 Footer is required in the website with quick links and social media links. Please Assign it to me.

**Comment by mdazfar2** [comment]
@Dark-S8uL, this issue is related to another one you're working on. Can you please switch to the another issue?

**Comment by mdazfar2** [comment]
@Dark-S8uL I saw a issue on my web.

<br>

![Picsart_24-06-04_14-47-41-113.jpg](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/d691e685-78b9-47ac-8b7f-f54fde6a4193)

<br>

- If you want to work on it you can raise new issue for it.

**Comment by Dark-S8uL** [comment]
@mdazfar2 Yes, I can do it. Please Assign it to me in the issue raised
