### ISSUE TITLE
Feat: Redesign the Resource Page for good Looking using TailwindCSS

### ISSUE THREAD

**Issue by SadafKausar2025** [mdazfar2/HelpOps-Hub#840]
### Describe the feature

I want to make more  beautiful to this page 
the page looks very simple 

### Add ScreenShots

![Screenshot (2075)](https://github.com/mdazfar2/HelpOps-Hub/assets/137484958/854c67f9-e636-43ed-bd6c-132ba3797c84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by SadafKausar2025** [comment]
hello @mdazfar2 
please assign me this issue 
I want to work in this issue

**Comment by mdazfar2** [comment]
Hey @SadafKausar2025 you have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
