### ISSUE TITLE
Feat: Adding Scroll to top Button in Resource Page

### ISSUE THREAD

**Issue by SadafKausar2025** [mdazfar2/HelpOps-Hub#841]
### Describe the feature

There are many resource in Resouce Page
I want to add  scroll to top button to bottom right corner of the page
which is very necessary

### Add ScreenShots

![Screenshot (2075)](https://github.com/mdazfar2/HelpOps-Hub/assets/137484958/071e02b3-a4bb-459e-8066-b91891fd8e53)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by SadafKausar2025** [comment]
hello @mdazfar2 
can you please assign me this issue?

**Comment by mdazfar2** [comment]
@SadafKausar2025 
As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
