### ISSUE TITLE
BUG: Correcting the Disturbed UI of Contact Page

### ISSUE THREAD

**Issue by SadafKausar2025** [mdazfar2/HelpOps-Hub#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Screenshot (2074)](https://github.com/mdazfar2/HelpOps-Hub/assets/137484958/cac0856c-0018-41af-9396-3fccabf7e7f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
hi @SadafKausar2025 i think it works 
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/7f91f8f3-e132-44c5-93c7-a269ea64014d)
