### ISSUE TITLE
Feat: Making contact us page responsive

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#846]
### Describe the feature

it is not responsive for mobile view

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/69ecc6db-4530-4c89-a3af-4e248c421a19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
hi @mdazfar2 can i work upon it

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal you are assigned.

**Comment by RamakrushnaBiswal** [comment]
solved #851
