### ISSUE TITLE
BUG: Making HomePage Responsive and Fixing DarkMode

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The dark mode for the homepage is not fully functional, and the homepage itself lacks responsiveness. I will address these issues by making the homepage responsive and ensuring that the dark mode works seamlessly across all elements. This will enhance the user experience by providing a consistent look and feel, regardless of the device or theme preference. Additionally, I'll perform thorough testing to ensure that both features integrate smoothly with the existing design and functionality.

**Screenshot:**

![screencapture-localhost-3000-2024-07-05-18_44_33](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/97252edf-59f9-4c59-a244-317439998eb0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 go ahead
