### ISSUE TITLE
Project Proposal: Setting up a CI/CD pipeline using GitLab CI/CD

### ISSUE THREAD

**Issue by Apurv7777** [mdazfar2/HelpOps-Hub#85]
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this project proposal

**Comment by mdazfar2** [comment]
@thevijayshankersharma Great issue raised, we need it.

- Create folder `CI/CD Pipeline Using Gitlab`
- Add each and everything after hands-on 
- please don't copy and paste from anywhere
- Create in your own language
- try to write it with some emojis to enhance the user interface.

  - **The documentation you have created will help many people 🚀**

**Comment by thevijayshankersharma** [comment]
@mdazfar2 Don't accept Apurv7777 as it was assigned to me.

**Comment by Apurv7777** [comment]
### It was assigned to me. @thevijayshankersharma 

![Screenshot_20240603_153902_GitHub.jpg](https://github.com/mdazfar2/HelpOps-Hub/assets/65327303/524e10b1-c911-4431-9617-6e572a97287b)

### I request @mdazfar2 to merge whichever is best suitable for your project.

**Comment by thevijayshankersharma** [comment]
He told me to do that

**Comment by mdazfar2** [comment]
@Apurv7777 @thevijayshankersharma 

- Both of you create documentation, which seems attractive and impressive, I will merge it an give GSSOC'24 level3 label.

**Comment by thevijayshankersharma** [comment]
@mdazfar2 we both have raised the pull request check it.
