### ISSUE TITLE
Feat: Add the missing close icon for relevant components

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#854]
### Describe the feature

In the process of upgrading our website, it seems like the close icon for some components got removed......I want to add the icon back for all relevant components

### Add ScreenShots

![image (1)](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/4ce04588-4594-4e57-a738-9c0e02879425)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 assigned.
