### ISSUE TITLE
Feat: Modify the buttons and their hovering effects as per website's theme

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#855]
### Describe the feature

Currently, some buttons on Teams page are not matching to the other buttons on different pages....so would like to modify them and their hovering effects tooi

### Add ScreenShots

![btn](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/2c2951f6-85cb-46ad-853f-55b5748150b7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
Hi @Asymtode712, Right now we are not working on buttons. We will discuss and add some good buttons in the future after seeing the design. I will let you know if there is any need for it later.

**Comment by Asymtode712** [comment]
@mdazfar2 Sure
