### ISSUE TITLE
Feat: Make the Signup/Login page Responsive

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#859]
### Describe the feature

Currently our Login/Signup components are not responisve for Mobile-S,M,L screens......I would like to add proper responsiveness for the respective screens

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/843c7095-123c-419d-afdd-02498ac05fd2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Hlo can you please assign this to me this issue is still pending

**Comment by mdazfar2** [comment]
Try making a pull request by today
