### ISSUE TITLE
Feat: Add hover effects on about sections images with tailwind

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#870]
### Describe the feature

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/de0fb853-507a-47af-9ba4-38e7dde8be8f)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/6d337901-d977-42ca-a84c-42d6cdcdf804)

I will add hover effects on this three images with tailwind.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@zalabhavy I apologize, but I need to close this issue for now. Please don't be discouraged!
