### ISSUE TITLE
BUG: For mobile screen in team page social icons size is very big

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/1c3d4694-05da-4a15-b056-544a6f31175c)

I will fix it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @zalabhavy You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source.
