### ISSUE TITLE
Feat:  Want to fix design of about us page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#873]
### Describe the feature

I want to fix the design of the about us page

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/5f2ad936-c0c3-45f2-83f4-24ee4738450d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Already done this changes ✅
