### ISSUE TITLE
Feat: Converting Blog's Page to TailwindCSS According as Per New Theme

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#879]
### Describe the feature

As our website has been upgraded to Tailwind CSS, I want to convert the blogs page to use Tailwind CSS as well. This conversion will include updating the layout, typography, and component styles to align with the Tailwind design system.

### Add ScreenShots

![screencapture-help-ops-hub-git-main-shreyash3087s-projects-vercel-app-blogs-2024-07-07-10_16_16](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/bad10d5e-c77d-4146-b33f-9a479ba77b6f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned
