### ISSUE TITLE
BUG: Anchor tag is not added in the logo

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/41549426-8dd2-4946-ab9e-a91ea4757838)
here we need to add a anchor tag and it should be redirect into to the home epage

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dark-S8uL** [comment]
@mdazfar2 I can make the website logo hyperlink by adding anchor tag to the logo. Please Assign this to me

**Comment by RamakrushnaBiswal** [comment]
@Dark-S8uL i create the issue you can find more issues

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal @Dark-S8uL 
<br>
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/6330c3d4-acf5-4878-832e-f54fae858ee3)
<br>
- Instead of this, add `DevOps`  logo which is similar to the current one. If you guys can do it, I will assign it.

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 yes i can

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 i want to work upon it please assign it to me

**Comment by Dark-S8uL** [comment]
@mdazfar2 I have redesigned the logo. So, now i can add hyperlink to the logo. Please assign it to me.

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal @Dark-S8uL 

- I guess it is working fine. When the user clicks on the logo, it automatically goes to the homepage. You guys have to check it once.

**Comment by Dark-S8uL** [comment]
@mdazfar2 Ok then.

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 yes sir 😀

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 can you assign it to me

**Comment by mdazfar2** [comment]
> @mdazfar2 Ok then.

@Dark-S8uL, I just checked and it seems the logo redirection isn't working. Can you add an anchor tag to the logo so it directs users to the homepage when clicked? Let me know if you have any questions.

**Comment by Dark-S8uL** [comment]
@mdazfar2 Ok I will do it.

**Comment by RamakrushnaBiswal** [comment]
solved
