### ISSUE TITLE
Feat: fixing css of navbar in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#880]
### Describe the feature

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/0d81466b-5471-4ef9-ba53-c1fb9b9c8476)

fixing this

### Add ScreenShots

*

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@dhairyagothi Again you create duplicate issue checkout the issue #864
