### ISSUE TITLE
BUG: text colour in dark mode

### ISSUE THREAD

**Issue by dhairyagothi** [mdazfar2/HelpOps-Hub#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/00f5eb8a-e290-4233-9353-c679a1c6ab45)

text colur of website in dark mode

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @dhairyagothi You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source.
