### ISSUE TITLE
Feat: Want to implement the dark mode for all pages of login and signup 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#887]
### Describe the feature

I want to implement the dark mode for all the pages related to the login and signup using tailwind according to the website new theme 

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/45a90058-37df-4ff2-a302-b0dc7c09ebaa)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/71d9bb50-7cbd-4eb8-a66a-a483520e0f42)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/428be7cf-b131-4adf-8f07-1b11b4934757)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 You are assigned.
