### ISSUE TITLE
Feat: Improve the key event functioning for Login

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#888]
### Describe the feature

Currently, if you have enterend an email in the email field and left the password field empty and press the enter key then too the login operation directly executes instead of checking whether the password field is filled or not.......I want to fix this so that proper field validation takes place before going for execution

### Add ScreenShots

![Screenshot_20240707-131039_Chrome](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/48c05b4f-e55a-4bb5-8d28-3efc991b64ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 you are assigned.
