### ISSUE TITLE
Feat: Add some Hover effect on the Our team page[cards]

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#89]
### Describe the feature

**Add some Hover effect on the Our team page[cards]**

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/25b87981-7b0d-4705-b6ba-6e8d1417efe4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dark-S8uL** [comment]
@mdazfar2 I can efficiently add hover effect on cards in contributor page as I have made the cards. So, Please Assign this to me.
