### ISSUE TITLE
BUG: Fix resource page search bar cursor and click effect

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/4c8553bf-4828-4225-8afc-b44fa52f4038

- Fix this outline issue on the search bar.
- Add letter spacing between the word 'Resources'
- Remove the comment box unwanted area

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/70baa1b3-0622-4196-bfd8-2959177bde07)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes you are assigned
