### ISSUE TITLE
Light/Dark theme is not working

### ISSUE THREAD

**Issue by sharmi4590** [mdazfar2/HelpOps-Hub#896]
The dark mode and light mode changes are only on the Navbar , which should be applicable to the whole screen . I would like to work on it.
![Screenshot_20240707-220308](https://github.com/mdazfar2/HelpOps-Hub/assets/102676949/160a728a-1640-46f2-a88f-7c1c044035ec)
![Screenshot_20240707-220300](https://github.com/mdazfar2/HelpOps-Hub/assets/102676949/b05bc9fa-30fe-4de5-816b-ddce6a17c314)

**Comment by mdazfar2** [comment]
Hey @sharmi4590, thanks for finding that out, but it is solved. Can you please check it again and tell me whether it is working or not?
