### ISSUE TITLE
BUG: Dark mode is not working in Team page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/ae67728c-4d4c-43a9-8ba7-a23d06454082

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pandeyji711** [comment]
@RamakrushnaBiswal jus i have to link js to this page

**Comment by RamakrushnaBiswal** [comment]
i know after assign me i can do it @pandeyji711
