### ISSUE TITLE
Feat:Change the button

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#909]
### Describe the feature

the button didn't match with the UI

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/47523515-ab97-41ff-a330-dab918c80417)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/1baa7233-f320-4a81-887d-2681f47b7082)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal go ahead
