### ISSUE TITLE
Feat: Changing the image in `solve issue together` part

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/HelpOps-Hub#910]
### Describe the feature

Changing the image in `solve issue together` part

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/ed61c884-c4a5-4524-9472-5190cbd3593b)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/7387b149-4422-4f06-9575-b27f5d82d99c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal issue acknowledged! You are assigned.
