### ISSUE TITLE
Feat: Modify the key event handling for and some minor UI fix for Profile modal

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#912]
### Describe the feature

There are two issues:

- First, we must add proper field validation in addition to the key event handling for `Profile` modal
- Second, we must fix the positining of Pen icon in the same modal

### Add ScreenShots

![problem](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/392caed1-8ebc-4a32-a262-a0617070718b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 issue acknowledged! You are assigned.
