### ISSUE TITLE
[BUG]: Input box `Text` cannot visible

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hello @mdazfar2 ,
- In this project  subscription `input` box cannot text visible 
- please assign me..

[Screencast from 2024-07-08 14-03-21.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/a7df8af6-6ee0-4d7c-a40d-dd82a1f2763d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sivaprasath2004 I am noticing that you raise issues again and again without checking anything.

- This time you have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- You guys raise issues to get points but don't try to enhance the website
- This is not the way to work on open source.
