### ISSUE TITLE
BUG: Fix dark mode issue, enhance SEO

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/8fd5acd5-3d49-4818-af61-b78c61256d4a)

- Add relevant alt attributes to enhance SEO

---
https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/a85d446f-13a1-4f3c-9b4e-b322b282a6d7

- fix darkmode issue in input box of newsletter subscription
-  fix resource not found color according to theme

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes Issue acknowledged! You are assigned.
