### ISSUE TITLE
Feat:When User Refresh he is getting Logged Out 

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#916]
### Describe the feature

When User refreshes the page he gets Logged Out I want to fix that please see below video.

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/01b0f083-9fea-415e-99c1-f15a9710f264

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 assigned
