### ISSUE TITLE
BUG: Change image format to .webp for better SEO

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Changing the format of images from .png to .webp for better performace and decreased loading time.

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/7fafbbf0-2226-4b86-a5a7-ad8cab33ceac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes assignedm
