### ISSUE TITLE
Feat: Add Scroll to Top Button 

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#92]
### Describe the feature

I want to make button that will help to reach top of website.

To save time scrolling up, I'll create a button and use JavaScript to provide this functionality.

I expect to provide me **level3** for this task that motivates me for work hard and finish works as soon as possible.

I will use html , CSS , JavaScript for this.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/a6d84019-a989-4876-8f10-be911b1b2da2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 can you please assign me i will do it as soon as possible.

**Comment by mdazfar2** [comment]
@zalabhavy you are assigned ✔️

- Add comments on whatever changes you make in the web file.
