### ISSUE TITLE
BUG: `Under maintance`  pop up message

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hello @mdazfar2 

- In this button click show for the `under maintance` pop up message.

![Screenshot from 2024-07-08 18-45-30](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/56499d49-47d2-4b98-bffe-7d52160044a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sivaprasath2004 assigned.
- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)
