### ISSUE TITLE
[Feature]: Crown cannot visible in `Dark mode`

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#923]
### Describe the feature

 - In this project `/team` page top 3 `Contributors` section crown object cannot visible
 - please assign me

### Expected 
![Screenshot from 2024-07-08 20-50-46](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/8a21893e-766b-4fb1-91b5-cda92a5143e4)

### Acutal
![Screenshot from 2024-07-08 20-49-57](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/9e8244be-36d1-449d-b718-2d65fe53485f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@sivaprasath2004 It is visible very well I think there is no need to assigning you:

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/64dd9e95-76c1-4116-918c-e061843ff8a3)
