### ISSUE TITLE
BUG: Fix popup message spelling & add metadata to improve SEO 

### ISSUE THREAD

**Issue by vansh-codes** [mdazfar2/HelpOps-Hub#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/114163734/7976114e-ea34-4988-aacf-6b743c0350dd)

- fix the spelling in the popup message along with a proper message for user
- Add meta data to the pages for better SEO ranking 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@vansh-codes you are assigned.
