### ISSUE TITLE
BUG: Dark Mode Icon Not Changing When Clicked

### ISSUE THREAD

**Issue by GAGGZ1** [mdazfar2/HelpOps-Hub#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The dark mode icon on the website does not change its appearance when clicked. The expected behavior is for the icon to indicate the current mode (dark or light) after being clicked, but it remains the same regardless of the action.
![Screenshot 2024-06-03 110723](https://github.com/mdazfar2/HelpOps-Hub/assets/81284966/c685e8e7-2274-4d16-9496-0e5282cb5ac2)
![Screenshot 2024-06-03 110706](https://github.com/mdazfar2/HelpOps-Hub/assets/81284966/56ecc964-c534-410f-aaf3-aaacc44ee9d6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GAGGZ1** [comment]
@mdazfar2  please assign me as i am working with @pandeyji711

**Comment by GAGGZ1** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@GAGGZ1 You are assigned ✔️

- Once I click on dark mode, the entire page should be dark mode. Make it like this
