### ISSUE TITLE
BUG: Fix Minor Bugs On Blogs Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

There are a Few Minor Bugs on the Blogs page which need to be addressed for the proper funtioning of blog's page,the bugs are mentioned below - 

**1. Long Title overflows recent post cards**

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/a5d1b1e1-2a01-4d0c-828f-f6e13061781c)

**2.Clicking on any blog opens blog 1's page in just the recent post section**

**3. Making Cursor Pointer for the blog cards**

I will fix these bugs and ensure the proper functioning of the webpage

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned
