### ISSUE TITLE
BUG:card not display in 1 perfect line

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/90c6c563-0f36-4493-8468-cc6fb097453c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@mdazfar2 ,please assign me

**Comment by mdazfar2** [comment]
Hey @Varsani2520, welcome back after a long time. Hope all is well. 

- This is the same as what we had in our Figma design, so we haven't made any mistake in the alignment. Thank you :)

<br>

![IMG_20240709_110922.jpg](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/2551a4cc-69c8-4f95-9184-ed820706cae8)
