### ISSUE TITLE
Feat: Implementing Dark Mode on Blog's Page

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#937]
### Describe the feature

The Blogs Page Currently Lacks Dark Mode Implementation which makes it look odd form other pages in Dark-Mode
.Implementation of Proper Dark Mode on Blog's Page is necessary to provide good user experience.

**Proposed Changes:**

- Addition of Dark Mode Using Context API

### Add ScreenShots

![screencapture-helpopshub-blogs-2024-07-09-11_50_16](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/45e6f599-b225-486f-8b28-c1772e9e67eb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 you are assigned
