### ISSUE TITLE
Feat: Make the Blogs Page Responsive

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#942]
### Describe the feature

Currently, Our blog page is not yet responsive for smaller screens......I would like to add responsiveness to it

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/5d4f62fb-0454-4095-a2b9-3d6e36eec4c3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 Issue acknowledged! You are assigned.
