### ISSUE TITLE
Feat: Hover effect on hamburger on opening and closing 

### ISSUE THREAD

**Issue by Amruta7203** [mdazfar2/HelpOps-Hub#945]
### Describe the feature

Hover effect on hamburger on opening and closing 

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/116087736/85388de6-2ab6-4d7d-84a1-baf0b2913925)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Amruta7203 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
