### ISSUE TITLE
BUG: Duplicate msg on subscription 

### ISSUE THREAD

**Issue by Amruta7203** [mdazfar2/HelpOps-Hub#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Duplicate messages are getting displayed when clicked the subscribe button

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/116087736/3d7e77aa-4bfc-4ada-82d0-df19d3e6496e)

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/116087736/968b607d-3bb8-409d-b7f8-d789d9b23eb9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @Amruta7203 I have been observing for some time. You are raising issues again and again. That's not a good way to work on open source. Why don't you raise and describe everything in a single issue?

**Comment by Amruta7203** [comment]
@mdazfar2 I would have raised a same issue if the issues were on a single page.. But since the issues are on different pages I thought of raising separate issues.

**Comment by Amruta7203** [comment]
Also if you clearly observe there are ppl who have raised multiple issues like I have raised

**Comment by mdazfar2** [comment]
@Amruta7203 I have no animosity towards you. You can raise another issue. I will be happy to assign you. :)

<br>

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) that's why we can discuss more about to enhance HelpOps-Hub.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Comment by mdazfar2** [comment]
@Amruta7203 We've actually added validation to check if the user is already subscribed. Please see the screenshot below.

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/1bf45e40-2b16-4a78-8026-9edfcdf55707)

**Comment by Amruta7203** [comment]
That's alright @mdazfar2 .. The issue is about the duplicate msg been displayed.. Once in black below the input field and the other in red..
