### ISSUE TITLE
Feat: Adding space between contact form and navbar 

### ISSUE THREAD

**Issue by Amruta7203** [mdazfar2/HelpOps-Hub#949]
### Describe the feature

Currently the contact page looks congested because of lack of space between navbar and contact form 
Also I would like to replace the current illustration with the same color of the website theme

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/116087736/62345372-af9b-4aef-8119-1432cfb41adf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
hey @Amruta7203 In my side it is well!

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/3d4104f3-84c2-475c-9b20-8bb2249df551)
