### ISSUE TITLE
Feat: Carousel section For enhancing user engagement

### ISSUE THREAD

**Issue by Damini2004** [mdazfar2/HelpOps-Hub#95]
### Describe the feature

Here the carousel section helps user to know more about the feature through latest tempting images regarding that topic. This will contribute in better user experience.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/119414762/312b2fdf-49b7-4a6e-9537-63ca90c5cbe6)
Design will may appear like this. 
This will helpl to catch more user engagement.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Damini2004 , instead of the screenshot you provided, could you please elaborate more on what you can add to the HelpOps-Hub web, or share a screenshot after the changes? This will help me assign you.

**Comment by AkhilaSunesh** [comment]
@mdazfar2 In the contributors page we can make it more presentable by using this feature.

**Comment by mdazfar2** [comment]
@Damini2004 @AkhilaSunesh 

- You both are assigned

**Comment by Damini2004** [comment]
PR Created KIndly review it 
Here is demo video.

https://github.com/mdazfar2/HelpOps-Hub/assets/119414762/5c82bbae-6fe7-4f9c-a3c4-b2eed0fee5d5

**Comment by mdazfar2** [comment]
@Damini2004 You have put the background that is too low quality, please drive to work on another issue. Thanks )
