### ISSUE TITLE
Feat: Adding pagination in resource page

### ISSUE THREAD

**Issue by MeetDOD** [mdazfar2/HelpOps-Hub#952]
### Describe the feature

In the resource page i will show first 9 posts and after that there will be pagination i.e previous 1,2,3 next like that.

### Add ScreenShots

current: 

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/120380073/4b5c1d09-a6a2-4408-abb7-f41f9dd93717)

eg:

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/120380073/a014da40-0bbf-4c10-8113-d3afd219474a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @MeetDOD could you tell me where you implemented this change?  If you have a chance to share a quick mockup using a tool like Paint, highlighting the specific area with a red square, that would be very helpful for assigning the task.

**Comment by MeetDOD** [comment]
> Hey @MeetDOD could you tell me where you implemented this change? If you have a chance to share a quick mockup using a tool like Paint, highlighting the specific area with a red square, that would be very helpful for assigning the task.

At the resource page where all the resources are fetching.

Overview:
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/120380073/39bc3fc7-a1c2-4fa6-9b45-18765e1adfec)

**Comment by mdazfar2** [comment]
@MeetDOD Nice that's great idea but we can use any other instead of these boxes because it looks weird hope you understand do you have any other option? please share if you have.

**Comment by MeetDOD** [comment]
> @MeetDOD Nice that's great idea but we can use any other instead of these boxes because it looks weird hope you understand do you have any other option? please share if you have.

Like you are talking about the css, it looks nice in frontend trust me i had applied it before also

**Comment by mdazfar2** [comment]
> Like you are talking about the css, it looks nice in frontend trust me i had applied it before also

@MeetDOD,
Heads up! We're currently transitioning away from CSS and using Tailwind instead.  Hold on a moment, and I'll share some reference designs for the previous and next.

**Comment by mdazfar2** [comment]
hey @MeetDOD, I like your suggestion!  Feel free to go ahead and implement it.  I can review the PR and discuss any further changes that might be needed afterwards.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- And try use tailwind instead of css
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

**Comment by nishant0708** [comment]
Hey @mdazfar2 can I work on this?

**Comment by MeetDOD** [comment]
Currently I am working on this !

**Comment by mdazfar2** [comment]
Hey @MeetDOD It has been 4 days. but I gave you the opportunity and you did not take it seriously. So now, I am assigning this to Nishant. Please don't discourage yourself, and I apologize for this all.

**Comment by MeetDOD** [comment]
> Hey @MeetDOD It has been 4 days. but I gave you the opportunity and you did not take it seriously. So now, I am assigning this to Nishant.

Ok do as you wish ! I am OUT ...
