### ISSUE TITLE
Feat: Changing the BlogPost Component

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#953]
### Describe the feature

The Current Blog Post Component is simple and need redesigning to look professional.

**Current Page -** 

![screencapture-helpopshub-blogs-668c51d1f2cabfcbda70f331-2024-07-09-22_25_19](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/ec1e5c0c-aa8b-40ea-b613-2e9329705241)

**Proposed Changes:**

Change the UI of Blog Post Component to something like this-https://dev.to/babichweb/mythbusting-dom-was-dom-invented-alongside-html-3fme

### Add ScreenShots

![screencapture-dev-to-babichweb-mythbusting-dom-was-dom-invented-alongside-html-3fme-2024-07-09-22_23_44](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/8bd58f8a-69a7-4da7-a7d8-46ac97e3d494)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 issue acknowledged! you are assigned.
