### ISSUE TITLE
Feat: Want to allow all users to see their profiles 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#956]
### Describe the feature

I want that when user access the profile of the user by the profile link then the user is able to see that person profile from their account 
For example on any social media handle like instagram and linkedin They provide a valid and unique id of the user so that user can access the profile of that person directly 

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/fdb543dd-039a-4d4c-be7b-c89fc1471f93)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you are assigned
