### ISSUE TITLE
Feat: Blog post page is not responsive

### ISSUE THREAD

**Issue by mukilan2815** [mdazfar2/HelpOps-Hub#958]
### Describe the feature

[W](https://www.helpopshub.com/blogs/668c4accf2cabfcbda70f158)
in this url you can see that this is not a mobile friendly.

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/71129858/42477d54-a8f8-4571-acb5-aaf52d8e1108)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hi @mukilan2815 you have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by mdazfar2** [comment]
hey @mukilan2815 sorry for interrupting you earlier.  I was actually referring to a different issue.  We have an unresponsive issue that needs attention.  Would you be interested in working on it?  I can assign it to you right away if you're available.  The goal is to ensure it's fully mobile-responsive.

**Comment by mdazfar2** [comment]
hey @mukilan2815 sorry for interrupting you earlier.  I was actually referring to a different issue.  We have an unresponsive issue that needs attention.  Would you be interested in working on it?  I can assign it to you right away if you're available.  The goal is to ensure it's fully mobile-responsive.

**Comment by mukilan2815** [comment]
Yeah I am ready to work on it and say me what are the things I need to do ?

**Comment by mdazfar2** [comment]
@mukilan2815 It depends on you that how you make it full responsive on mobile.
- btw I'm assigning this issue to you.

**Comment by mukilan2815** [comment]
I will make that blog page responsive and i will raise a PR

**Comment by mdazfar2** [comment]
@mukilan2815, can you create the PR by midnight today, or do you need more time?
