### ISSUE TITLE
Feat:Add rotate animation in Solve  DevOps Issues Together's picture

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#960]
### Describe the feature

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/d8b3468a-314b-4cc7-a157-63f4d2dfcbcd)

I will add rotate animation on this image.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Can You Please assign me this task ?

**Comment by mdazfar2** [comment]
@zalabhavy go ahead
