### ISSUE TITLE
BUG:video is in loading then display skeleton

### ISSUE THREAD

**Issue by Varsani2520** [mdazfar2/HelpOps-Hub#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

if video take a some time for load then display skeleton like a youtube type 

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/7eb143bc-2508-4afb-905c-9f3afd8c44b3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@mdazfar2 ,please assign me

**Comment by mdazfar2** [comment]
@Varsani2520 can you please elaborate it?

**Comment by Varsani2520** [comment]
@mdazfar2 ,

similar like youtube if video take time to load from api or Web Browser ,
We can display Skeleton

**Comment by mdazfar2** [comment]
@Varsani2520 I am not able to understand what you want to say exactly. If you show me a screenshot or a demo video, I will understand and it will help me to assign this issue to you.

**Comment by Varsani2520** [comment]
@mdazfar2 ,

https://github.com/mdazfar2/HelpOps-Hub/assets/137641079/e7e06d83-56cb-4968-a279-a2a3b03fd6df

**Comment by mdazfar2** [comment]
@Varsani2520 For which page do you want to add this?

**Comment by Varsani2520** [comment]
@mdazfar2 ,in about page video

**Comment by mdazfar2** [comment]
@Varsani2520 assigned.
- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Use Tailwind instead of css.
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks

**Comment by Varsani2520** [comment]
Thank you for giving me this opportunity
