### ISSUE TITLE
Feat: Enhance Blog Description to Include More Than Just Text

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#969]
### Describe the feature

The current blog description field only accepts text. Enhancing it to support various elements like images, videos, headings, horizontal lines, and code will significantly improve the quality of blog posts.

**Proposed Changes:**

Modify the description input field to allow inclusion of images, videos, headings, and other rich content.

### Add ScreenShots

![screencapture-help-ops-hub-git-feat-enhance-blogpost-shreyash3087s-projects-vercel-app-blogs-668ea41d1fadccc2480a1668-2024-07-10-21_51_24](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/a2355ffc-3e17-4f72-949f-e091b2e1cab5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@mdazfar2 kindly assign this

Thankyou

**Comment by mdazfar2** [comment]
@shreyash3087 assigned
