### ISSUE TITLE
DOC:New Section of Spring and Spring boot 

### ISSUE THREAD

**Issue by Yashgabani845** [mdazfar2/HelpOps-Hub#97]
### What's wrong with the existing documentation

will provide spring and sppring boot setup and tutorial
with proper documentation
about speing and how to perform web dev and Aop

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Yashgabani845** [comment]
@mdazfar2 please assign me this issue

**Comment by mdazfar2** [comment]
@Yashgabani845 It isn't DevOps related.
