### ISSUE TITLE
Feat: Integration of Non-Working Elements of Blog Post with the Database

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/HelpOps-Hub#970]
### Describe the feature

Some features of the Blog Post component, such as reactions, user profiles (including the follow button), and the "More From User" section, are currently non-functional.

**Proposed Changes:**

- Integrate all these components with the database to make the Blog Post component fully complete and functional.

### Add ScreenShots

![screencapture-help-ops-hub-git-feat-enhance-blogpost-shreyash3087s-projects-vercel-app-blogs-668ea41d1fadccc2480a1668-2024-07-10-21_51_24 (1)](https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/9f4db013-379f-4dd0-87da-31ee9ee11d69)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@shreyash3087 go ahead
