### ISSUE TITLE
DOC: Jenkins Installation and Setup

### ISSUE THREAD

**Issue by dharsanjilla** [mdazfar2/HelpOps-Hub#98]
### What's wrong with the existing documentation

Add Jenkins Installation and Setup

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dharsanjilla** [comment]
@mdazfar2 can you consider adding Jenkins in HelpOps-Hub , I can make the required documents ,let me know if you want to add

**Comment by mdazfar2** [comment]
@dharsanjilla  Great issue raised, we need it.

- Create folder `Jenkins Setup`
- Add each and everything after hands-on 
- please don't copy and paste from anywhere
- Create in your own language
- try to write it with some emojis that enhance the user interface.

  - **The documentation you have created will help many people 🚀**
