### ISSUE TITLE
BUG : Light mode contact form thank You message not visible

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/126322584/9a39e7e7-c76a-405d-b4ba-eda4f9de27c9)

In dark mode visible clear i will add text color black in light mode.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Can you please assign me this task !

Thank You !

**Comment by mdazfar2** [comment]
Go ahead @zalabhavy
