### ISSUE TITLE
Feat: Make comment button for post.

### ISSUE THREAD

**Issue by zalabhavy** [mdazfar2/HelpOps-Hub#989]
### Describe the feature

Comment button post comment.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@mdazfar2 Please assign me !

Thank You !

**Comment by mdazfar2** [comment]
@zalabhavy go ahead

**Comment by mdazfar2** [comment]
hey @zalabhavy did you start working on that!

**Comment by zalabhavy** [comment]
@mdazfar2 Yes i started. I will make PR soon !
