### ISSUE TITLE
Feat: Add a new team member card

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/HelpOps-Hub#992]
### Describe the feature

Would like to add a new team member card to the existing ones as discussed 

### Add ScreenShots

![team](https://github.com/user-attachments/assets/7cde34c1-5dc8-4df4-b876-f6f08a8612cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 Please assign me this issue

**Comment by mdazfar2** [comment]
@Asymtode712 you are assigned
