### ISSUE TITLE
Feat: Want to make skeleteon For Dark mode

### ISSUE THREAD

**Issue by nishant0708** [mdazfar2/HelpOps-Hub#994]
### Describe the feature

there is skeleton which are looking odd in dark mode i want to fix 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b5de11df-d16f-4176-94d1-7fcfa9203f73)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@nishant0708 great issue can you also add dark mode to the loading effect? I mean, when we are in dark mode, the loading effect does not change, as shown in the screenshot below.

<br>

![image](https://github.com/user-attachments/assets/9527e9ac-026a-41e2-a865-800d38f5d2ea)

<br>

> hope you understand

**Comment by nishant0708** [comment]
Okay I will add here as well

**Comment by mdazfar2** [comment]
@nishant0708 you are assigned.
