### ISSUE TITLE
Feat: Backend Integration for bookmark on blogs, fix navbar scroll view, Adding hovering animation on image adding a create post button 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/HelpOps-Hub#996]
### Describe the feature

I want to Integrate the backend for the bookmark facility 
I want to fix the navbar issue 
I want to add the hovering animation on the images of the blogs 
Want to just create a create post button 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f8bcae0c-1ad1-4ba2-81d4-ae96b25b7773)
![image](https://github.com/user-attachments/assets/f66e3e18-f2e4-404e-95bd-f9fe546ea70e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you are assigned
